### ISSUE TITLE
Bug: Milliseconds in LineCharts and timeofday

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1129]
```
Hi,

I have trouble using regular settings:

* LineChart
* timeofday
* Added some data: [0,0,50,800],[0,0,48,200], ...
* No special options used (only InterpolateNull)
* Using the API via DRUPAL

Problem:

* Milliseconds are not used for y-axis values, but only the seconds. So for "hi-res"
data the graph is useless since 50.8 seconds are rendered as 50.0 seconds. 
* See screenshot

How to make the gva render the data completely?

Thanks a lot












```

Original issue reported on code.google.com by `ulrich.mueller79` on 2013-01-27 13:10:58

<hr>
- _Attachment: Arbeitsfläche 1_001.png<br>![Arbeitsfläche 1_001.png](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1129/comment-0/Arbeitsfläche 1_001.png)_

**Comment by orwant** [comment]
```
Definitely a bug.  Thanks.
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2013-01-28 16:13:45

**Comment by orwant** [comment]
```
Thanks for the quick response.

How long might it take to fix it?
```

Original issue reported on code.google.com by `ulrich.mueller79` on 2013-01-29 15:33:39

**Comment by orwant** [comment]
```
I have a relatively simple fix that I am testing now.  I expect it will be part of the
1.1 release in a week or two.
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2013-01-29 15:49:25

**Comment by orwant** [comment]
```
Thank you very much :)
```

Original issue reported on code.google.com by `ulrich.mueller79` on 2013-01-30 06:05:34

**Comment by orwant** [comment]
```
Is there any progress on the issue?
```

Original issue reported on code.google.com by `ulrich.mueller79` on 2013-03-06 14:08:18

**Comment by orwant** [comment]
```
My change for this fix is part of the newly released version 1.1.  (The release had
been delayed while we repaired some unexpected problems.)
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2013-03-06 14:55:17

**Comment by orwant** [comment]
```
My mistake, the recent 1.1 release did not include the change to support milliseconds
in timeofday values, but the next 1.1 release will, hopefully in another week or two.
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2013-03-07 18:25:59

**Comment by dlaliberte** [comment]
This issue has been fixed for a long time.
