### ISSUE TITLE
Bug: Map of South Africa not ending below the coastline in GeoChart.  Formatting issues

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1233]
```
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.
1. Please see http://g-form.co.za
2. I am using the following code:
In the <head>
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1', {packages: ['geochart']});

    function drawVisualization() {
      var data = google.visualization.arrayToDataTable([
        ['State', 'Province', 'G-Form Outlets'],
        ['ZA-GP', 'Gauteng', 10],
        ['ZA-WC', 'Western Cape', 5],
        ['ZA-EC', 'Eastern Cape', 2],
        ['ZA-ZN', 'KwaZulu-Natal', 1],
        ['ZA-FS', 'Free State', 1],
        ['ZA-LP', 'Limpopo', 0],
        ['ZA-NW', 'North-West', 0],
        ['ZA-MP', 'Mpumalanga', 0],
        ['ZA-NC', 'Northern Cape', 0],  

      ]);

      var view = new google.visualization.DataView(data);
    view.setColumns([1, 2]);

      var geochart = new google.visualization.GeoChart(
              document.getElementById('visualization'));
          var options = {};
          options['region'] = 'ZA';
          options['resolution'] = 'provinces';
          options['width'] = 800;
          options['height'] = 500;
          options['colors'] = ['#cccccc', '#C01E24'];
          options['legend'] = 'none';

        google.visualization.events.addListener(geochart, 'select', function() {
            var selectionIdx = geochart.getSelection()[0].row;
            var stateName = data.getValue(selectionIdx, 0);
            var value = data.getValue(selectionIdx, 2); 

          if (value >= '1') {
          window.open('http://g-form.co.za/dealers/' + stateName + '.html');}
              });

          geochart.draw(data, options);
        }

    google.setOnLoadCallback(drawVisualization);
  </script>
And in the <body>
<div id="visualization"></div>

The map of South Africa does not cut off below the bottom edge of the country and is
causing formatting issues on the page.


What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)?

GeoChart


Are you using the test environment (version 1.1)?
(If you are not sure, answer NO)

NO
What operating system and browser are you using?
Mac OSX Mountain Lion w/ Google Chrome


*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************
```

Original issue reported on code.google.com by `geeb.productions` on 2013-06-11 11:48:08

**Comment by orwant** [comment]
```
sorry it is on http://g-form.co.za/dealer.html
```

Original issue reported on code.google.com by `geeb.productions` on 2013-06-11 11:51:05

**Comment by orwant** [comment]
```
I'm sorry that this is inconveniencing you, but this is not a bug. The reason that the
map is not being cut off below the coastline is because there is a region there at
the bottom of the map. I highlighted the region in the attached screenshot. The ISO
code for that region is TF, which Wikipedia says is the entry for the French Southern
Territories. You can read more about it here: http://en.wikipedia.org/wiki/ISO_3166-2:TF
```

Original issue reported on code.google.com by `grabks@google.com` on 2013-06-11 14:28:42

<hr>
- _Attachment: Screen Shot 2013-06-11 at 10.16.11 AM.png<br>![Screen Shot 2013-06-11 at 10.16.11 AM.png](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1233/comment-2/Screen Shot 2013-06-11 at 10.16.11 AM.png)_

**Comment by orwant** [comment]
```
Thanks... That does make sense now, but is there a way to exclude that region from ZA?
```

Original issue reported on code.google.com by `geeb.productions` on 2013-06-11 14:33:45

**Comment by orwant** [comment]
```
We're working on improving this, but there is currently no way to do it outside of serving
your own maps.
```

Original issue reported on code.google.com by `grabks@google.com` on 2013-06-11 14:37:12

**Comment by orwant** [comment]
```
Ok, so the map worked for a little bit but now my Gauteng and Kwa-Zulu Natal regions
are not showing.  Has the province code changed recently?  here is the code again,

<script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1', {packages: ['geochart']});

    function drawVisualization() {
      var data = google.visualization.arrayToDataTable([
        ['State', 'Province', 'G-Form Outlets'],
        ['ZA-GP', 'Gauteng', 10],
        ['ZA-WC', 'Western Cape', 5],
        ['ZA-EC', 'Eastern Cape', 2],
        ['ZA-ZN', 'KwaZulu-Natal', 1],
        ['ZA-FS', 'Free State', 1],
        ['ZA-LP', 'Limpopo', 0],
        ['ZA-NW', 'North-West', 0],
        ['ZA-MP', 'Mpumalanga', 0],
        ['ZA-NC', 'Northern Cape', 0],  

      ]);

      var view = new google.visualization.DataView(data);
    view.setColumns([1, 2]);

      var geochart = new google.visualization.GeoChart(
              document.getElementById('visualization'));
          var options = {};
          options['region'] = 'ZA';
          options['resolution'] = 'provinces';
          options['width'] = 800;
          options['height'] = 500;
          options['colors'] = ['#cccccc', '#C01E24'];
          options['legend'] = 'none';

        google.visualization.events.addListener(geochart, 'select', function() {
            var selectionIdx = geochart.getSelection()[0].row;
            var stateName = data.getValue(selectionIdx, 0);
            var value = data.getValue(selectionIdx, 2); 

          if (value >= '1') {
          window.open('http://g-form.co.za/dealers/' + stateName + '.html');}
              });

          geochart.draw(data, options);
        }

    google.setOnLoadCallback(drawVisualization);
  </script>
```

Original issue reported on code.google.com by `iso400ZA` on 2013-07-02 09:48:32

**Comment by orwant** [comment]
```
We recently regenerated our map data, which means that it's now using all the latest
ISO codes. Guateng's ISO code has been changed back to ZA-GT, and Kwa-Zulu Natal's
ISO code has been changed back to ZA-NL. You can find out more about the ISO codes
on this Wikipedia page: http://en.wikipedia.org/wiki/ISO_3166-2:ZA
```

Original issue reported on code.google.com by `grabks@google.com` on 2013-07-02 14:21:12

**Comment by orwant** [comment]
```
Hi there,

I'm curious to know if this issue has been fixed? The French Southern Territories are
not part of South Africa or the Exclusive Economic Zone (EEZ) of South Africa.

I'm also trying to display this chart correctly.

Would it be possible perhaps to use a zoom feature?
```

Original issue reported on code.google.com by `vanflymen` on 2014-06-18 11:11:18

**Comment by johnkareoke** [comment]
Just an FYI. This is not a bug per se. This is Marion and Prince Edward Islands, not the French Southern Territories, so they are part of South Africa: 

"19 km long by 12 km wide, and the two islands have a combined area of 316 square km and politically form part of South Africa's Western Cape Province."

https://en.wikipedia.org/wiki/Prince_Edward_Islands

**Comment by MackyMakita** [comment]
Any solution for the Democratic Republic of the Congo with new 26 provinces?

I'm desperating here...

**Comment by MackyMakita** [comment]
Here is the code for the Congo:
New provinces are not recognized:


  | <html>
-- | --
  | <head>
  | <script type='text/javascript' src='https://www.google.com/jsapi'></script>
  | <script type='text/javascript'>
  | google.load('visualization', '1', { 'packages': ['geochart'] });
  | google.setOnLoadCallback(drawMarkersMap);
  |  
  | function drawMarkersMap() {
  | var data = google.visualization.arrayToDataTable([
  | ['City', 'Population', 'Area'],
  | ['CD-BC', 138262, 18],
  | ['CD-KL', 38262, 11],
  | ['CD-KS', 138262, 18],
  | ['CD-HU', 38262, 11],
  | ['CD-LO', 138262, 18],
  | ['CD-LU', 38262, 11],
  | ['CD-MN', 138262, 18],
  | ['CD-MO', 38262, 11],
  | ['CD-NU', 138262, 18],
  | ['CD-SA', 38262, 11],
  | ['CD-SU', 138262, 18],
  | ['CD-TA', 38262, 11],
  | ['CD-TO', 138262, 18]
  | ]);
  |  
  | var options = {
  | region: 'CD',
  | displayMode: 'regions',
  | resolution: 'provinces',
  | colorAxis: { colors: ['orange', 'red'] }
  | };
  |  
  | var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
  | chart.draw(data, options);
  | };
  | </script>
  | </head>
  | <body>
  |  
  | <a href="javascript:hideshow(document.getElementById('adiv'))">Click here</a>
  |  
  | <script type="text/javascript">
  | function hideshow(which) {
  | if (!document.getElementById)
  | return
  | if (which.style.display == "block")
  | which.style.display = "none"
  | else
  | which.style.display = "block"
  | }
  | </script>
  | <br />
  | <div id="adiv" style="font:24px bold; display: block">Now you see me</div>
  |  
  | <div id="chart_div" style="width: 900px; height: 500px;"></div>
  | </body>
  | </html>

**Comment by MackyMakita** [comment]
`

  | <html>
-- | --
  | <head>
  | <script type='text/javascript' src='https://www.google.com/jsapi'></script>
  | <script type='text/javascript'>
  | google.load('visualization', '1', { 'packages': ['geochart'] });
  | google.setOnLoadCallback(drawMarkersMap);
  |  
  | function drawMarkersMap() {
  | var data = google.visualization.arrayToDataTable([
  | ['City', 'Population', 'Area'],
  | ['CD-BC', 138262, 18],
  | ['CD-KL', 38262, 11],
  | ['CD-KS', 138262, 18],
  | ['CD-HU', 38262, 11],
  | ['CD-LO', 138262, 18],
  | ['CD-LU', 38262, 11],
  | ['CD-MN', 138262, 18],
  | ['CD-MO', 38262, 11],
  | ['CD-NU', 138262, 18],
  | ['CD-SA', 38262, 11],
  | ['CD-SU', 138262, 18],
  | ['CD-TA', 38262, 11],
  | ['CD-TO', 138262, 18]
  | ]);
  |  
  | var options = {
  | region: 'CD',
  | displayMode: 'regions',
  | resolution: 'provinces',
  | colorAxis: { colors: ['orange', 'red'] }
  | };
  |  
  | var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
  | chart.draw(data, options);
  | };
  | </script>
  | </head>
  | <body>
  |  
  | <a href="javascript:hideshow(document.getElementById('adiv'))">Click here</a>
  |  
  | <script type="text/javascript">
  | function hideshow(which) {
  | if (!document.getElementById)
  | return
  | if (which.style.display == "block")
  | which.style.display = "none"
  | else
  | which.style.display = "block"
  | }
  | </script>
  | <br />
  | <div id="adiv" style="font:24px bold; display: block">Now you see me</div>
  |  
  | <div id="chart_div" style="width: 900px; height: 500px;"></div>
  | </body>
  | </html>

`
