### ISSUE TITLE
Bug: Timeline option colors

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1344]
```
Code:
...

var dataTable = {"cols":[
{"id":null,"label":"Title graph","type":"string"},
{"id":null,"label":"Description","type":"string"},
{"id":null,"label":"Start","type":"date"},
{"id":null,"label":"End","type":"date"}
],
"rows":[
{"c":[{"v":"Event1"},{"v":"#19deeb"},{"v":new Date(2013,10,21,20,50,0)},{"v":new Date(2013,10,22,20,10,0)}]},
{"c":[{"v":"Event1"},{"v":"#1921eb"},{"v":new Date(2013,10,21,20,45,0)},{"v":new Date(2013,10,22,20,50,0)}]},
{"c":[{"v":"Event2"},{"v":"#1921eb"},{"v":new Date(2013,10,21,20,0,0)},{"v":new Date(2013,10,23,20,10,0)}]},
{"c":[{"v":"Event2"},{"v":"#1921eb"},{"v":new Date(2013,10,21,20,20,0)},{"v":new Date(2013,10,22,20,30,0)}]},
 {"c":[{"v":"Event2"},{"v":"#ffd708"},{"v":new Date(2013,10,23,21,15,0)},{"v":new Date(2013,10,24,20,0,0)}]},
{"c":[{"v":"Event3"},{"v":"#ffd708"},{"v":new Date(2013,10,21,20,30,0)},{"v":new Date(2013,10,21,22,25,0)}]},
{"c":[{"v":"Event3"},{"v":"#1921eb"},{"v":new Date(2013,10,22,18,10,0)},{"v":new Date(2013,10,23,20,0,0)}]}
]};
var options = {
  title: "Graph",
  width: 940,
  height: 600,
timeline: {groupByRowLabel : true }
  colors: ["#19deeb","#1921eb","#1921eb","#1921eb","#ffd708","#ffd708","#1921eb"]
                }

var data = new google.visualization.DataTable(dataTable);

var chart = new google.visualization.Timeline(elm);

chart.draw(data, options);

...

Wrong colors appear in the timeline chart. Do not sit on the ranking and even some
colors do not appear at all.

I used version 1.0 and version 1.1

The browser you are using is 24.0 firefox, chrome 30.0.1599.69m
```

Original issue reported on code.google.com by `mbohovic` on 2013-10-23 13:18:31

<hr>
- _Attachment: [image.jpg](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1344/comment-0/image.jpg)_

**Comment by orwant** [comment]
```
Also, it appears that matching by Name takes precedence over the colors array. In the
code below, 'Thomas Jefferson' will have the same color in both instances, despite
the colors settings:
dataTable.addRows([
    ['President', 'George Washington', new Date(1789, 3, 29), new Date(1797, 2, 3)],
    ['President', 'John Adams', new Date(1797, 2, 3), new Date(1801, 2, 3)],
    ['President', 'Thomas Jefferson', new Date(1801, 2, 3), new Date(1809, 2, 3)],
    ['Vice President', 'Thomas Jefferson', new Date(1797, 2, 3), new Date(1800, 2,
3)]]);

var options = { colors: ['#cbb69d', '#603913', '#c69c6e', '#00ff00']};
```

Original issue reported on code.google.com by `Mikhail.St.P` on 2013-10-24 18:06:02

**Comment by orwant** [comment]
```
Colours array only works if there are no overlapping times for a single row. This has
to be fixed asap, colours in the colour array should exactly match the datatable input
when not grouping by row.
```

Original issue reported on code.google.com by `AdamGarner89` on 2014-05-19 11:54:42

**Comment by orwant** [comment]
```
This code is working as intended. See the documentation for "timeline.colorByRowLabel"
on the documentation page here: https://developers.google.com/chart/interactive/docs/gallery/timeline#Configuration_Options

By default, each unique bar label is assigned a color (from the "colors" option if
provided) as it is seen. See this fiddle to see what is going on: http://jsfiddle.net/gmadrid/T6MCq/

If you really need to control the color on a row-by-row basis, then you can use the
(I believe still undocumented) "style" role. Here is an example of that: http://jsfiddle.net/gmadrid/6nNgg/


Not sure what is meant by the last comment: "no overlapping times for a single row."
Can you give me a concrete example with this failure?

Thanks.

```

Original issue reported on code.google.com by `gmadrid@google.com` on 2014-05-19 14:17:57

**Comment by orwant** [comment]
```
Hey There,

The basis of the issue is that I need to not display the colour code on the bars. I
have a system whereby many bars on the same row may be taking place at the same time,
and each bar may have it's own user-defined colour.

This fiddle may clearly show what my issue is: http://jsfiddle.net/7A88H/21/

In the example you provided the colours only work correctly when the names are preserved
as the hex codes, which is obviously not a possibility for me.
```

Original issue reported on code.google.com by `AdamGarner89` on 2014-05-20 10:54:39

**Comment by orwant** [comment]
```
Is there no way to achieve this?
```

Original issue reported on code.google.com by `adam.garner.eposnow` on 2014-05-20 15:27:36

**Comment by orwant** [comment]
```
I am having same issue.
```

Original issue reported on code.google.com by `Klahnen` on 2014-09-01 20:38:59

**Comment by orwant** [comment]
```
This is still an issue for my company
```

Original issue reported on code.google.com by `adam.garner.eposnow` on 2014-09-02 08:55:59

**Comment by orwant** [comment]
```
Hi, 
I managed to solve this problem. 

The colors must be unique for each new Title graph!!! 

For our illustrative example would be as follows: 

var options = {
    title: "Graph", 
    width: 940, 
    height: 600, 
    timeline: {groupByRowLabel: true} 
    colors: ["#19deeb", "#1921eb", "#ffd708"] 
}
```

Original issue reported on code.google.com by `mbohovic` on 2014-09-02 09:06:13

**Comment by orwant** [comment]
```
Unfortunately we are using the both sets of v: and f: fields on each item to store encoded
data. There is just no way we would be able to store the colour directly on each bar,
it would have to be defined elsewhere.
```

Original issue reported on code.google.com by `adam.garner.eposnow` on 2014-09-02 09:16:03

**Comment by orwant** [comment]
```
I'm having the same issue here. I need bars on the same row to be represented with different
colors. I have the same number of colors as data items. I need a kind of 'traffic lights'
feature, so colors will be repeated. 

For instance, I have 6 items (not represented here) and my color options as are below
(6 colors, but they can be repeated in the array)

var options = {
colors: ["#19deeb", "#1921eb", "#ffd708", "#19deeb", "#1921eb", "#ffd708"] 
}

Was anyone able to sort this out?
```

Original issue reported on code.google.com by `xsebas21` on 2015-03-04 18:43:10

**Comment by sharadugalmugale** [comment]
hi
i am having same issue in single row its working but for multiple rows its not working
is anyone got solution???

**Comment by sjstebbins** [comment]
I ran into the same issue where I was trying to have multiple row items (potentially with the same title) on the same row and assign colors based on a 5th param. A workaround solution for those of you still facing this problem is for each new row item you add, iterate over the existing row items and check if an item with the same title already exists. If a row item with the same title exists, append an additional space to this new item's title for each duplicate, which will allow the chart to follow your color map as each title is now unique. *\* If you have chart events as well, just remember to add .trim() to your selection so it returns the appropriate title without the additional spaces.

**Comment by dustinsterk** [comment]
For anyone else that stumbles into this issue, all you have to do is use the style role and ensure it is in the proper order of the datatable.  See the following example:  http://jsfiddle.net/af8jq9aa/1/

**Comment by sohamray1990** [comment]
Hi @dustinsterk ,
You are god sent. Was struggling with this issue for so long. Was very critical to my project. 
Thank you so much, Sir.. if you only knew how much relieved I feel at the moment!

**Comment by ArsenyLL** [comment]
@dustinsterk  Thank you very much!!!!

**Comment by dustinsterk** [comment]
You are both very welcome, glad it was helpful!  :)

**Comment by vikas0121** [comment]
Hi, 
I'm facing issue while using multi-color in the same bar.
I'm assigning color to every row based on some condition.
I'm using this

					    var colors = [];
						var colorMap = {
							// should contain a map of category -> color for every category
							A: '#FF4500',
							B: '#19c362',
							C: '#592df7'
						}


							
							
}.
Please help

**Comment by dustinsterk** [comment]
See my example, you need to use "style":

http://jsfiddle.net/af8jq9aa/1/

**Comment by toujames** [comment]
@dustinsterk 

Using 'style' works but you **MUST** put the style column **AFTER** the name id

**Comment by nishanthan89** [comment]
Try this, its working for me            

var dataTable = new google.visualization.DataTable();
            dataTable.addColumn({ type: 'string', id: 'Name' });
            dataTable.addColumn({ type: 'string', id: 'JobType' });
            dataTable.addColumn({ type: 'string', role: 'style' });
            dataTable.addColumn({ type: 'date', id: 'Start' });
            dataTable.addColumn({ type: 'date', id: 'End' });

			
			for (var j = 0; j < model.JobType.length; j++)
            {
				var jbt = model.JobType;
				var ColorValue = null;
			
				if (jbt == "Job A"){
					ColorValue = "#AF0BEA";
				}
				else if (jbt == "Job B")
				{
					ColorValue = "#19c362";

				}
				else if (jbt == "Job C") {
					ColorValue = "#091F8B";

				}
				else if (jbt == "Job D") {
					ColorValue = "#592df7";

				}
				else if (jbt == "Job E") {
					ColorValue = "#d3401b";

				}
			
			dataTable.addRows([[name, jbt, ColorValue, startdate, endDate]]);
			}

**Comment by ljubic** [comment]
The Google Charts Timeline documentation should definitely be edited and provide an example for this use case. I was struggling because there was written that Column 2 has purpose for tooltip only:
https://developers.google.com/chart/interactive/docs/gallery/timeline#data-format
