### ISSUE TITLE
Bug: Annotated Time Line does not use formatting/pattern of DataTable

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1350]
```
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.
1. Create an Annotated Time Line using a DataTable with a column pattern and/or formatted
values (or use the attached file).
2. View the values displayed on the chart.  They are not formatted according to the
column pattern, nor is the cell's formatted value displayed.
3. The numberFormats option should override formatting given in the DataTable, and
not ignore them if it is not set.
4. If the chartType is changed to another type (ColumnChart, e.g.), the values are
displayed correctly.

This would also resolve issues like this:
https://code.google.com/p/google-visualization-api-issues/issues/detail?id=99#c6

What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)?
Annotated Time Line

Are you using the test environment (version 1.1)?
(If you are not sure, answer NO)
NO

What operating system and browser are you using?
Windows 7, Chrome Version 30.0.1599.101 m


*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************
```

Original issue reported on code.google.com by `bggardner` on 2013-10-29 13:17:38

<hr>
- _Attachment: [gatl.html](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1350/comment-0/gatl.html)_

**Comment by orwant** [comment]
```
The flash-based annotatedtimeline chart is being deprecated, but the new implementation
using corecharts should make it much easier to support this formatting feature.
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2013-11-19 18:41:35

**Comment by adamcrume** [comment]
This is more generic than Annotated Time Line.  DataTable.getFormattedValue ignores the pattern specified on a column.

**Comment by grabks** [comment]
Hi @adamcrume,

This issue should probably be closed, since it appears to be a misinterpretation of the data table specification. None of our charts use the 'pattern' field in the DataTable. The 'pattern' field is there primarily for Docs to use. If you need to apply custom formatting to your values, you should either use the chart-specific formatting options or use the NumberFormat or PatternFormat.

**Comment by adamcrume** [comment]
That should be made clear in the addColumn documentation, then.

**Comment by dlaliberte** [comment]
Adam,

I tend to agree that the pattern option should be supported, or at least documented that it is not supported.
