### ISSUE TITLE
Bug: Sanley do not trigger select event

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1472]
```
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.
1. See attached file


What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)?
Sankey


Are you using the test environment (version 1.1)?
(If you are not sure, answer NO)
YES


What operating system and browser are you using?
Chrome



*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************

```

Original issue reported on code.google.com by `pascal@clickndecide.eu` on 2014-02-06 15:58:48

<hr>
- _Attachment: [Sankey wrapper.html](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1472/comment-0/Sankey wrapper.html)_

**Comment by orwant** [comment]
```
Thanks for the bug report. We're on it. 
```

Original issue reported on code.google.com by `gmadrid@google.com` on 2014-02-13 03:22:31

**Comment by orwant** [comment]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `gmadrid@google.com` on 2014-02-13 04:16:50

**Comment by jonathansudhakar1** [comment]
Has this been fixed or is there a work around?

**Comment by grabks** [comment]
@jonathangizmo The Sankey chart has supported node selection since the v42 release (currently in 1.1), and will support link selection in the v43 release. [Here is an example of using the node selection functionality](https://jsfiddle.net/5mvx6bdr/).

**Comment by jonathansudhakar1** [comment]
@grabks Thank you. Any idea when v43 will be available?

**Comment by grabks** [comment]
@jonathangizmo We will probably cut it to 1.1 in a couple of weeks.

**Comment by jonathansudhakar1** [comment]
@grabks awesome thank you :-)

**Comment by ghost** [comment]
Has support for link selection been added?  Doesn't seem to work when I specify v1.1.  Node selection works.
