### ISSUE TITLE
Feature Request: Charts legend icon type such as "square", "circle", "star", etc.

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1548]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `None` on 1970-01-01T00:00:00.00Z

**Comment by eyaleee** [comment]
+1

**Comment by grabks** [comment]
This bug should actually be resolved. Symbols like 'square', 'circle', and 'star' are already supported as point styles, which will also be reflected in the legend.

Here is an example of doing that: https://jsfiddle.net/x68doe0L/

Is there something missing from our implementation that you would like to see, @eyaleee?
