### ISSUE TITLE
Bug: Putting 2 material bar charts on a single HTML page with different heights and widths causes the first chart to have it's display truncated

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1944]
```
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.

Putting 2 material bar charts on a single HTML page but each chart has different height
and width causes the first chart to have it's display truncated.
Code is attached.
Also attached are 2 screen grabs. 
1.One shows the charts displayed when the charts have the same height and width. 
2.The other show the display when the Upper chart has larger height and width that
the lower chart.

On Safari I've been able to observe that as the Upper chart is rendered on the display,
it gets shown correctly. As the second chart starts to render I can see the upper chart
display get truncated. 



What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)?
Material Bar chart


Are you using the test environment (version 1.1)?
(If you are not sure, answer NO) NO


What operating system and browser are you using?
Apple OSX v10.10.2, Firefox v36.0.4, Safari v8.0.4



*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************

```

Original issue reported on code.google.com by `andrewjoss25` on 2015-04-02 10:42:52

<hr>
- _Attachment: [twoChartTest.html](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1944/comment-0/twoChartTest.html)_
- _Attachment: Chart heights and width same.png<br>![Chart heights and width same.png](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1944/comment-0/Chart heights and width same.png)_
- _Attachment: Charts heights and widths different.png<br>![Charts heights and widths different.png](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1944/comment-0/Charts heights and widths different.png)_

**Comment by orwant** [comment]
```
Data for both charts is identical 
```

Original issue reported on code.google.com by `andrewjoss25` on 2015-04-02 10:46:52

**Comment by orwant** [comment]
```
This is a known issue and will be fixed with the next release.
```

Original issue reported on code.google.com by `grabks@google.com` on 2015-04-02 13:33:10

**Comment by grabks** [comment]
This issue should be fixed in the latest release.
