### ISSUE TITLE
tooltips not working in timeline

### ISSUE THREAD

**Issue by stephanecharette** [google/google-visualization-issues#1975]
The data format section of timeline describes tooltips:

https://google-developers.appspot.com/chart/interactive/docs/gallery/timeline#Data_Format

But when this column is added to a datatable, the rendered chart is a single error message that states:  "Invalid data table format: must have 3 or 4 data columns."

**Comment by orwant** [comment]
Stephane, I've added an example to the documentation that shows you how to customize tooltips in timelines:

https://developers.google.com/chart/interactive/docs/gallery/timeline#Tooltips

Note that until the current release of Charts goes to "stable" in a week or so, you'll have to load version 1.1 to get this behavior.

**Comment by stephanecharette** [comment]
Thanks, that extra information was exactly what was needed for me to get customized tooltips working.  Love the new timeline changes in 1.1. Colours look good on timelines with many rows.
