### ISSUE TITLE
DataTable class method `getProperties` returns empty object even if styling applied in Spreadsheet cells

### ISSUE THREAD

**Issue by stulees** [google/google-visualization-issues#1987]
When using the DataTable class provided from a Query response `response.getDataTable()`, no matter what styling is applied to a cell in a public spreadsheet, the `getProperties(rowIndex, columnIndex)` method of the DataTable returns an empty object `{}`. 

**How to produce**
1) Query a spreadsheet 
2) Within your successful response handle, use `getDataTable()` to store the response as a DataTable in a variable
3) Call `getProperties(row, col)` on the DataTable instance and pass a sample row index and column index to the method that correspond with a cell that you know you have styling for.

**Expected Results**
Should return a map of all the properties for the specified cell

**Actual results**
Returns an empty object

**Demo**
Spreadsheet: https://docs.google.com/spreadsheets/d/1MTchxNnlhjUuRwA256pXmLsCU4tfOsHo_A8k8sdusK4/edit#gid=1
Page: http://s3.amazonaws.com/Donna/visualization-demo/demo.html

**Comment by grabks** [comment]
Hi, there currently isn't any way to get the styling applied in a spreadsheet, except maybe using the Spreadsheets API. getProperties is intended to be used for properties that you specify yourself on the client, or perhaps on a server that you have control over.
