### ISSUE TITLE
Issue in tooltip position after scrolling

### ISSUE THREAD

**Issue by cms01** [google/google-visualization-issues#1988]
Reference URL: https://developers.google.com/chart/interactive/docs/customizing_tooltip_content

I am using this part( focusTarget: 'category' option.):
Issue:  If I add an horizontal scroll bar then tool tip  is not coming in proper position after scrolling
Find code here:  https://developers.google.com/chart/interactive/docs/customizing_tooltip_content
Custom HTML content can also include dynamically generated content. Here, we add a tooltip containing a dynamically generated table for each category value. Since the tooltip is attached to the row value, hovering over any of the bars will display the HTML tooltip.

This example demonstrates how a custom HTML tooltip can be attached to a domain column. (In previous examples, it was attached to a data column.) To turn on the tooltip for the domain axis, set the focusTarget: 'category' option.

Here are the  details of code:

<?php

function drawChart() {
  var dataTable = new google.visualization.DataTable();
  dataTable.addColumn('string', 'Country');
  // Use custom HTML content for the domain tooltip.
  dataTable.addColumn({'type': 'string', 'role': 'tooltip', 'p': {'html': true}});
  dataTable.addColumn('number', 'Gold');
  dataTable.addColumn('number', 'Silver');
  dataTable.addColumn('number', 'Bronze');

  dataTable.addRows([
    ['USA', createCustomHTMLContent('http://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_the_USA.svg', 46, 29, 29), 46, 29, 29],
    ['China', createCustomHTMLContent('http://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg', 38, 27, 23), 38, 27, 23],
    ['UK', createCustomHTMLContent('http://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_the_United_Kingdom.svg', 29, 17, 19), 29, 17, 19]
  ]);

  var options = {
    title: 'London Olympics Medals',
    colors: ['#FFD700', '#C0C0C0', '#8C7853'],
    // This line makes the entire category's tooltip active.
    focusTarget: 'category',
    // Use an HTML tooltip.
    tooltip: { isHtml: true }
  };

  // Create and draw the visualization.
  new google.visualization.ColumnChart(document.getElementById('custom_html_content_div')).draw(dataTable, options);
}

 function createCustomHTMLContent(flagURL, totalGold, totalSilver, totalBronze) {
  return  '<div style="padding:5px 5px 5px 5px;">' +
      '<img src="' + flagURL + '" style="width:75px;height:50px"><br/>' +
      '<table class="medals_layout">' + '<tr>' +
      '<td><img src="http://upload.wikimedia.org/wikipedia/commons/1/15/Gold_medal.svg" style="width:25px;height:25px"/></td>' +
      '<td><b>' + totalGold + '</b></td>' + '</tr>' + '<tr>' +
      '<td><img src="http://upload.wikimedia.org/wikipedia/commons/0/03/Silver_medal.svg" style="width:25px;height:25px"/></td>' +
      '<td><b>' + totalSilver + '</b></td>' + '</tr>' + '<tr>' +
      '<td><img src="http://upload.wikimedia.org/wikipedia/commons/5/52/Bronze_medal.svg" style="width:25px;height:25px"/></td>' +
      '<td><b>' + totalBronze + '</b></td>' + '</tr>' + '</table>' + '</div>';
}

?>

If I add an horizontal scroll bar then tool tip  is not coming in proper position after scrolling 

Please help me to resolve this issue
Thanks so much.

**Comment by grabks** [comment]
Hi,

It's a little difficult to diagnose your issue without access to an example of your code (a jsfiddle is preferable), but from what you're describing, it sounds like you're attempting to make the chart div scrollable. [Here is a working example that has a horizontal scrollbar](http://jsfiddle.net/5qboekks/).

[And here is what I suspect you were doing](http://jsfiddle.net/5qboekks/1/).

**Comment by vugar005** [comment]
@grabks  I checked the at example. There it does not work also
