### ISSUE TITLE
Google Motion chart not working in IE and Firefox 

### ISSUE THREAD

**Issue by pradeepgopal** [google/google-visualization-issues#1991]
Hi, 
Can anyone help me figure out how to make Motion Chart work in IE and Firefox? 
It works fine in Chrome browser

This is a big issue for me and the work I plan to be doing, so any 
help would be greatly appreciated!

Pradeep

**Comment by danabnormal** [comment]
The Motion Chart is a Flash component, so the first thing to check is whether IE and Firefox have Flash installed (Chrome uses its own built in Flash viewer). Other than that its hard to say without seeing your code.

**Comment by pradeepgopal** [comment]
Thank you danabnormal.Its working Now

Pradeep
