### ISSUE TITLE
PieChart & Chart_bar don't work with IE7 and IE8

### ISSUE THREAD

**Issue by annaschmalholz** [google/google-visualization-issues#1992]
Hello we are using https://www.google.com/jsapi . Charts are beautiful however in IE 7 and IE 8 they are not working. Please help to fix the problem and advice on steps I need to take to make it work 
1.  var chart = new google.visualization.PieChart(
                                      document.getElementById('chart_div'));
2.  var chart_bar = new google.visualization.BarChart(document.getElementById("barchart_values"));

Thank you,
AnnaSchmalholz

**Comment by orwant** [comment]
Hi, this isn't a specific issue that we can act on: our VML charts verifiably render in IE7 and IE8. Please post source code (or even better, a link to a jsfiddle) in the public forum, and perhaps someone will help.
