### ISSUE TITLE
Selecting/Deselecting rows in a table not working properly

### ISSUE THREAD

**Issue by heennkkee** [google/google-visualization-issues#1993]
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.
http://jsfiddle.net/heennkkee/5gyrdt2y/
1. Select row in a table, the selected row doesn't look like it used to (it stays at the color and look as when you hover)
2. Select new row, now both rows looks like they are hovered (it used to de-select the old row)
3. hover up and down with your cursor on the "old selection", it will be unselected after a hover.

(http://jsfiddle.net/heennkkee/n8omqgna/ same chart but using version 1.0, works like a charm).

What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)?
Table chart

Are you using the test environment (version 1.1)?
(If you are not sure, answer NO)
Yes.

What operating system and browser are you using?
Windows 8.1, Chrome version 43.0.2357.81 (32bit).

**Comment by dlaliberte** [comment]
I'm not seeing this with Chrome (version 40.0.2214.111 (64-bit)) on Linux.  I see the hover style override the select style while you are hovering a selected row, but returns to the select style when you move the mouse off the row.

I'd be surprised if there is a difference in versions of Chrome, or across OSes, but it is possible.

**Comment by heennkkee** [comment]
Sorry to ask but can you please check again if you pressed the link with 1.1? I'll try to create a video tonight showing my problems. Meanwhile, check this:
![namnlos](https://cloud.githubusercontent.com/assets/12745884/8051654/7e5ab840-0e7f-11e5-940b-1afb72c5fb56.png) 
1. Press first row (left click)
2. Move mouse down to second row and left click that
3. same as above for third row
4. move mouse to header (from third row upwards and hovering over all "previous" rows) without clicking anything.

And again, here is chrome version:
Google Chrome   43.0.2357.81 (Officiell version) beta-m (32 bitar)

Can I provide you with any more information?

edit: I apologize for the close/openings, never used github before :)

**Comment by dlaliberte** [comment]
I do see the same problem on the same version of Chrome as you listed, on Windows 7, so count me surprised.  It looks like a bug in the browser, however, since the css class that shows the selected state, google-visualization-table-tr-sel, is only present when it is supposed to be, when the table row is selected, and clicking a previously selected table row does make it unselected.  So the problem involves changes in the css styles that are not being updated according to what the classes indicate.

**Comment by dlaliberte** [comment]
Some further info.  The Chrome developer tools does show the correct background color for the unselected state, after unselecting the row, but the actual elements in the page still uses the wrong color. If I toggle the backgrond-color property of a table cell in that row, which has the value 'inherit', the background-color in the page is updated correctly, and toggling the property back on leaves it that way. This seems to be more confirmation that there is a browser bug here, but I haven't found any similar bug about this issue.

**Comment by heennkkee** [comment]
When setting the selection with "setSelection" it seems to work. I ran across someone elses jsfiddle and changed it to 1.1, and it still looks to be working.
http://jsfiddle.net/heennkkee/qpjkp9x8/
However I can see the same thing as you write about, it looks to be toggling color correct, but not updating the actual element. If you change the color to something else than the already selected value (select a row, then change the color with the debug tool) it updates to that color though.
I guess google charts API does what it's supposed to, as the color toggles in the code?

**Comment by dlaliberte** [comment]
Yes, the Google Charts API is doing the right thing, but that version of Chrome (at least on Windows) is not updating the display correctly.  There may be a workaround for this bug, but I'd rather wait to see if the bug gets fixed.

**Comment by heennkkee** [comment]
Sorry to bump this alive again, but I was just struck by a thought that I can not understand.

Why would 1.1 suffer from this bug, while 1.0 does not? If it's a problem with the browser.

Could you help me understand?

**Comment by dlaliberte** [comment]
There were significant changes in the table chart implementation from 1.0 to 1.1 that could explain the change in browser sensitivity.

**Comment by heennkkee** [comment]
Aha, thanks. I've submitted this to the chrome team as a bug report, and I guess I'll see what they reply.

**Comment by heennkkee** [comment]
Just updating that this has been solved (by Chrome I suppose). Both version "1" and "1.1" works as intended now.
