### ISSUE TITLE
Tooltip won't display on programatic selection

### ISSUE THREAD

**Issue by tollus** [google/google-visualization-issues#2001]
Hello,

I'm trying to use the `tooltip.trigger = 'selection'` and `setSelection([{row:4,column:null}])`, but the tooltip doesn't show up automatically. Only when you click on another tooltip.

Here's a <a href="http://jsfiddle.net/wt2afgxg/">jsfiddle</a> showing the problem.

Any ideas what I can try?

Thanks!

Reference on stackoverflow: http://stackoverflow.com/questions/30943596/show-tooltip-on-load-with-google-charts

**Comment by grabks** [comment]
Hi,

This is a known bug with focusTarget: 'category'. That particular option uses the mouse position as a signal for how to position the tooltip, and so programmatic selection won't trigger a tooltip to display.

To circumvent this issue, you could use multiple selection on the first load. Here's an example of this, along with a reset that changes the focusTarget back to 'category' at the first opportunity: http://jsfiddle.net/b1kt6mrL/

**Comment by tollus** [comment]
Oh okay. Thanks, that works.
