### ISSUE TITLE
Timeline shows wrong month in graph.

### ISSUE THREAD

**Issue by simkeyur** [google/google-visualization-issues#2003]
Say if I do something like this:
data.addRows([
        ['S01', 'created', new Date(2014, 9, 1), new Date(2014, 9, 30)],
      ]);

timeline chart should show september, instead it shows october. I think it is treating as array.. any quick way to fix this?

**Comment by dlaliberte** [comment]
Keyur,

The numeric index of the first month for JavaScript dates is 0, so 9 does
mean October.  This is true for many programming languages, though everyone
is surprised and confused by it, unfortunately.  See
http://stackoverflow.com/questions/344380/why-is-january-month-0-in-java-calendar

On Tue, Jun 30, 2015 at 5:02 PM, Keyur Patel notifications@github.com
wrote:

> Say if I do something like this:
> data.addRows([
> ['S01', 'created', new Date(2014, 9, 1), new Date(2014, 9, 30)],
> ]);
> 
> timeline chart should show september, instead it shows october. I think it
> is treating as array.. any quick way to fix this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2003.

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2  -
978-394-1058
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA
daniel.laliberte@GMail.com daniel.laliberte@gmail.com 9 Juniper Ridge
Road, Acton MA
