### ISSUE TITLE
Stacked bar doesn't recognize options

### ISSUE THREAD

**Issue by jvanwinden** [google/google-visualization-issues#2005]
When I try to make a stacked bar and use

```
var options = {
    isStacked: 'percent'
}
```

Google charts just renders it as if isStacked were false. Also `isStacked: 'relative'` and `isStacked: 'absolute'` are not recognized by google charts. I am using version 1.0

**Comment by dlaliberte** [comment]
If you are using google.charts.Bar(), that would explain it.

**Comment by jvanwinden** [comment]
I am using `new google.visualization.BarChart()`, so that's not it

**Comment by dlaliberte** [comment]
Ah, I didn't notice that you said you are using version 1.0.  That's the problem since it is not yet available except in version 1.1.

**Comment by jvanwinden** [comment]
This fixed it! Thanks. BTW, do you know where I can see the differences between versions?

**Comment by dlaliberte** [comment]
You can find a brief summary of changes between versions on the Release Notes page: https://google-developers.appspot.com/chart/interactive/docs/release_notes
