### ISSUE TITLE
Line chart: default curveType is not 'null', but 'function'

### ISSUE THREAD

**Issue by yokoto** [google/google-visualization-issues#2008]
I'm using [ankane/chartkick](https://github.com/ankane/chartkick/) in my private project, Ruby 2.2.0 and Rails 4.2.0. This Ruby library can pass options directly to the charting library for [Google Charts](https://developers.google.com/chart/interactive/docs/gallery).  
In the description of the [Configuration Options](https://google-developers.appspot.com/chart/interactive/docs/gallery/linechart#configuration-options), `curveType` option is set to default `'null'` which is straight lines without curve. However, when I use it, it displays a curve line without options. It can be set that default is '`function'`.  
In my code:  

```
<%= line_chart dau_h %>
```

I solve this by adding option `library: {curveType: 'none'}` for now. Please check its default out.

**Comment by grabks** [comment]
The documentation is correct, the default for Google Charts is 'null', as you can see in [this trivial example](http://jsfiddle.net/1bs74vma/) (just uncomment the 'curveType' option to see the difference).

Looking through the (third party) chartkick library, it looks like they set the curveType to 'function' explicitly [right here](https://github.com/ankane/chartkick/blob/master/app/assets/javascripts/chartkick.js#L458).

**Comment by yokoto** [comment]
I see. Thank you for the response and details quickly.
