### ISSUE TITLE
Calendar Charts off by one month

### ISSUE THREAD

**Issue by buytore** [google/google-visualization-issues#2010]
Trying to get Calendar Charts working and all went smooth but the data is off by one month. 

See example on the google charts web-site for Calendar Charts (https://developers.google.com/chart/interactive/docs/gallery/calendar)
Note that the data for the first rows are:
dataTable.addRows([
          [ new Date(2012, 3, 13), 37032 ],
          [ new Date(2012, 3, 14), 38024 ],

However, the example Red Sox chart shows this exact data on April 13 & 14 2012 respectively. I'm experiencing the exact same thing with one chart I've built. My data starts in January 2, 2015 but the information is displayed in February 2, while January shows no data at all. 

I've restructured my Python program to subtract 1 from the month (01 becomes 00) when being passed to the javascript, which corrects the issue and the data displays correctly. Seems to be a bug with the month.

Hope this helps.

**Comment by orwant** [comment]
Confusingly, JavaScript dates use zero-indexing for months, so 0 means January and 3 means April.

**Comment by buytore** [comment]
This was not the case in other Google Charts - I've used the exact same method call in Python to structure date data for other charts like the Bubble Charts and only have to pass in the date - there was no need to modify the date as I had to with the new Material Line Chart.
