### ISSUE TITLE
event handling not working on Table chart

### ISSUE THREAD

**Issue by aloucs** [google/google-visualization-issues#2011]
The following example is extracted from on line documentation. The table is shown, but the event is not working. What is wrong?

  '<head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
google.load('visualization', '1.0', {'packages':['table', 'corechart']});

google.setOnLoadCallback(drawChart);

```
  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart() {

    // Create our data table.
    data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
      ['Mushrooms', 3],
      ['Onions', 1],
      ['Olives', 1],
      ['Zucchini', 1],
      ['Pepperoni', 2]
    ]);

    // Set chart options
    var options = {'title':'How Much Pizza I Ate Last Night',
                   'width':400,
                   'height':300};
```

var cssClassNames = {
    'headerRow': 'italic-darkblue-font large-font bold-font',
    'tableRow': '',
    'oddTableRow': 'beige-background',
    'selectedTableRow': 'orange-background large-font',
    'hoverTableRow': '',
    'headerCell': 'gold-border',
    'tableCell': '',
    'rowNumberCell': 'underline-blue-font'};

  var options = {'showRowNumber': true, 'allowHtml': true, 'cssClassNames': cssClassNames};  
         table = new google.visualization.Table(document.getElementById('table_div'));

google.visualization.events.addListener(table, 'select', tableHandler);       

```
table.draw(data, options); 
  }

 function tableHandler() {
    var selectedItem = table.getSelection()[0];
    var value = data.getValue(selectedItem.row, 0);
         alert('You selected ' + value);
    }
</script>
```

  </head>

<body>

```
<div id="table_div" style="width:400; height:300"></div>
```

</body>

**Comment by grabks** [comment]
Hi, I don't see any "following example." Perhaps you forgot to paste it? It's also unclear which event you're trying to use. [Here is a jsfiddle example of the select event](https://jsfiddle.net/k2mp2j9x/)

**Comment by aloucs** [comment]
Thank you for your reply. Sorry, I pasted the content but it is visible only in edit. 
Anyway, the example was very similar to yours, just a little more complicated by the usage of css part in the table option : table.draw(data, options) where option is the following
var options = {'showRowNumber': true, 'allowHtml': true, 'cssClassNames': cssClassNames}; 

<b>I have found </b> the cause of fail in the following definition of cssClassNames (that I also get from  documetation example at https://developers.google.com/chart/interactive/docs/examples under Customized Table Example). Specifically the BAD clause is  'selectedTableRow': 'orange-background large-font', because it contains the background definition. Deleting this background reference and using only font definition the script works fine. 
If the background color style definition is supposed to be allowed, then it is a BUG, otherwise it should better explained/highlighted. 
Thank you again.   

var cssClassNames = {
    'headerRow': 'italic-darkblue-font large-font bold-font',
    'tableRow': '',
    'oddTableRow': 'beige-background',
    'selectedTableRow': 'orange-background large-font',
    'hoverTableRow': '',
    'headerCell': 'gold-border',
    'tableCell': '',
    'rowNumberCell': 'underline-blue-font'};

  var options = {'showRowNumber': true, 'allowHtml': true, 'cssClassNames': cssClassNames}; 

**_CSS style ***_
  .bold-green-font {
    font-weight: bold;
    color: green;
  }

  .bold-font {
    font-weight: bold;
  }

  .right-text {
    text-align: right;
  }

  .large-font {
    font-size: 15px;
  }

  .italic-darkblue-font {
    font-style: italic;
    color: darkblue;
  }

  .italic-purple-font {
    font-style: italic;
    color: purple;
  }

  .underline-blue-font {
    text-decoration: underline;
    color: blue;
  }

  .gold-border {
    border: 3px solid gold;
  }

  .deeppink-border {
    border: 3px solid deeppink;
  }

  .orange-background {
    background-color: orange;
  }

  .orchid-background {
    background-color: orchid;
  }

  .beige-background {
    background-color: beige;
  }

**Comment by grabks** [comment]
I see the issue here. As it turns out, we only allow one class name per element. However, because of the different ways in which we actually assign the classes for different elements, some wind up working (like headerRow), and some don't (like selectedTableRow).

It's certainly not great, but you could work around this by combining your multiple classes into one.

**Comment by aloucs** [comment]
ok, but using background color only the style is not applied, even if the script crash does not occur.

**Comment by grabks** [comment]
It appears that it's overridden by the existing style. Marking your style as '!important' appears to work. [Here is an example](https://jsfiddle.net/99k9x0e1/).

**Comment by aloucs** [comment]
I see, good. Thank you very much.
