### ISSUE TITLE
Security certificate issues in IE11.

### ISSUE THREAD

**Issue by marcomarsala** [google/google-visualization-issues#2013]
I'm trying to display a graph using Google Charts API:

```
http://chart.apis.google.com/chart?chd=t:2,5,1,2,69,68,30,178,2,63,10,18,6&chl=Vercelli (2)|Torino+(ex+Pinerolo) (5)|Torino (1)|Milano (2)|Mantova (69)|Ivrea (68)|Genova+(ex+Chiavari) (30)|Genova (178)|Cuneo (2)|Brescia (63)|Bergamo (10)|Asti+(ex+Alba) (18)|Asti (6)&cht=p&chds=0,20&chs=400x200
```

This URL is working in all browsers except IE11. IE is complaining about the security certificate emitted for another site.

**Comment by grabks** [comment]
Hi, that URL is no longer supported (because of the certificate issues). Please use chart.googleapis.com instead, as listed on the [documentation page](https://developers.google.com/chart/image/).
