### ISSUE TITLE
Material + bar chart + tooltip.isHtml does not seem to work

### ISSUE THREAD

**Issue by cjblomqvist** [google/google-visualization-issues#2016]
See https://jsfiddle.net/cjblomqvist/uuLnp834/1/ for an example. I need isHtml in order to use ignoreBounds, and apparently it is not working (I've also checked the DOM - it renders SVG and no regular HTML).

Or am I missing something?

**Comment by trevordowdle** [comment]
Running into same problem

**Comment by nbering** [comment]
Possibly related to #1946 and #1953? Smells like unimplemented features in the new charts.

**Comment by grabks** [comment]
Good instincts, @nbering, this is exactly the case.

HTML tooltips are not yet supported in Material charts.

**Comment by grabks** [comment]
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143
