### ISSUE TITLE
Annotating Google Material Bar Charts

### ISSUE THREAD

**Issue by vmvivek208** [google/google-visualization-issues#2037]
Hello everyone,

I was trying to use role annotation in material bar charts, its's not working. Has anyone tried the same?

Thanks in advance,
Vivek Mishra

**Comment by grabks** [comment]
Hi, annotations are not yet implemented in Material charts. We are working on it.

**Comment by vmvivek208** [comment]
Hello,

Thanks for your reply.

Thanks & Regards
Vivek Mishra
Scientist-B
National Informatics Center
Mob no:-+919873205937

**Comment by grabks** [comment]
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Comment by tamtam22** [comment]
Hi, is annotations working on material google charts yet?

**Comment by jonsgreen** [comment]
Any updates?

**Comment by borconi** [comment]
No offence guys but it's 2019 and this still does not work... pretty bad for a company with reputation like Google...

**Comment by isaacrbeam** [comment]
I agree with you @borconi

**Comment by qlerebours** [comment]
It would be very usefull. Any workaround to annotate a material chart ?
