### ISSUE TITLE
gviz/tq from Sheets changed Date object?

### ISSUE THREAD

**Issue by mosa-riel** [google/google-visualization-issues#2042]
In GAS we regularly query sheets with the gviz/tq command. 
![gviztq](https://cloud.githubusercontent.com/assets/9515736/9546502/7b0d297c-4d93-11e5-92eb-f2801b3ef701.png)

But the date object seems to have changed in a Date() function, causing several scripts and webservices to fail right now. 

Is this a bug, or a change that stays?﻿

**Comment by grabks** [comment]
Hi,

This was an intentional change made by docs. This change turned their response into valid JSON, where before it used the date constructor. I'm pretty sure they don't intend to change it back.

**Comment by mosa-riel** [comment]
Actually, are you sure? Because now there is the Date constructor.
I would expect

 "2014-01-01T23:28:56.782Z" 

instead of 

Date(2015,6,15,11,20,15)

But if it is not going to change, then we need to update.
That's what I needed to know.Thank you.

**Comment by alucab** [comment]
+rielzzapps is right.

 This format is ambiguous as there is no consideration for timezones. If a spreadsheet has different timezone settings from the client there is continuous unalignment to be considered everywhere in the code. The old MS Ajax format was at least univoque.

ISO8601 format should be considered and implemented as per all the modern JSON libraries.

It is easily parsable and readable, sortable and totally univoque.
