### ISSUE TITLE
new Date summing 1 month

### ISSUE THREAD

**Issue by ricardobarrospereira** [google/google-visualization-issues#2043]
I am using the charts for some months but I've never realized that, just today I saw it.

The problem is, for example when we use [new Date(2015,01,10),1000] , it shows February, when it was supposed to show January.

Here is a fiddle example: https://jsfiddle.net/ns91ft9v/1/

And even the examples on the chart docs (https://google-developers.appspot.com/chart/interactive/docs/datesandtimes) are summing 1 month.

I couldn't find nowhere else someone reporting this issue, and I've tried on many different browsers.

Am I getting crazy or there is a real issue here?

**Comment by grabks** [comment]
As the first "Important" box says on the [Dates and Times](https://google-developers.appspot.com/chart/interactive/docs/datesandtimes) page that you linked to, "In JavaScript Date objects, months are indexed **starting at zero** and go up through eleven, with **January being month 0** and December being month 11." (emphasis mine)

This is correct behavior, even though it's a little counterintuitive. It's also very well documented on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), which says "month: Integer value representing the month, **beginning with 0 for January** to 11 for December." (emphasis and punctuation added)

**Comment by ricardobarrospereira** [comment]
Yes I saw that later, don't know why I haven't read that box... sorry about that :/

tks
