### ISSUE TITLE
Google bar and guage charts compressed

### ISSUE THREAD

**Issue by SHeffernan** [google/google-visualization-issues#2046]
Hi,

I am publishing a range of google charts on to my web site via a text editor.
I first check the by running the html file directly using Chrome or Firefox, then they are added to my web site via copy and paste in to a rich text editor (blog style, which is part of the web site template).

The line and pie charts added work fine, however the bar, column and gauge charts (all classic versions, not material) compress down to 25px.

When I use Firebug to view the web page, I can see div containing the style which sets the height to 25px immediately below the div for the chart in question and I cannot edit/control those styles. Those lines are NOT written by me.
They are added either by the rich text editor, or by googlecharts.

Any ideas on how to fix this please??
PS: I don't have the time or skill to rebuild the web site template. 

Thanks,
Sean.

Compressed bar chart, but pie is fine:
![compressed bar chart](https://cloud.githubusercontent.com/assets/10904879/9716800/c7fe92c8-55b0-11e5-9fd6-a52dd44040a5.PNG)

Extra style div:
![style divs](https://cloud.githubusercontent.com/assets/10904879/9716731/018e7bf8-55b0-11e5-9287-e21c8f36c940.PNG)

**Comment by dlaliberte** [comment]
Since you didn't show us anything about your options to the charts, we can't tell about that.  But your chart6_div style width and height are missing the 'px', which could explain why your chart sizes are wrong if you haven't specified width and height values otherwise.

**Comment by SHeffernan** [comment]
Awesome!

Thanks Daniel.

That must seem like such a simple fix to you. Those settings worked without the px when I ran the html directly from a text file, but didn’t run when added to the page.

I’m not sure why yet, but I am only new the html, so appreciate your help!

**Comment by dlaliberte** [comment]
Glad to help.
