### ISSUE TITLE
Cannot load 'sankey' package with frozen version 41

### ISSUE THREAD

**Issue by Fenrisvuld** [google/google-visualization-issues#2047]
Hi Guys,

When trying to load the 'sankey' package with `google.charts.load('41', {'packages':['sankey']});`, I get a 404 error from the loader:

![image](https://cloud.githubusercontent.com/assets/2765289/9720227/84b35d10-558c-11e5-9af8-cd8b13710946.png)

Here is a fiddle based on the sankey example: https://jsfiddle.net/0khudjnf/

**Comment by dlaliberte** [comment]
Thanks for your report.  This should be fixed in a day or two.

**Comment by dlaliberte** [comment]
Fixed now.

**Comment by Fenrisvuld** [comment]
Great! Thank you!
