### ISSUE TITLE
Chart Editor layout is broken in frozen version 41

### ISSUE THREAD

**Issue by Fenrisvuld** [google/google-visualization-issues#2049]
Hello,

In frozen version 41, the chart editor layout is broken:
- Tabs are stuck together with no border
- Images are shifted
- The customize panel does not have a scrollbar
- ...

https://jsfiddle.net/xh0y80jz/

![image](https://cloud.githubusercontent.com/assets/2765289/9732103/6b76b154-5621-11e5-9580-b2cf63ecb00f.png)

![image](https://cloud.githubusercontent.com/assets/2765289/9732144/bb6c493a-5621-11e5-8e9e-2478cd8492d5.png)

**Comment by dlaliberte** [comment]
Thanks for your report.  We seem to be missing the charteditor.css file.  Should be fixed in a day or two.

**Comment by dlaliberte** [comment]
Actually, the charteditor.css file is being loaded, but it appears to be the wrong version of that file.  This might be trickier to fix.

**Comment by dlaliberte** [comment]
This should be fixed now.
