### ISSUE TITLE
Issue in displaying Timestamp under tooltip using google.visualization.BubbleChart

### ISSUE THREAD

**Issue by DivyashreeMS** [google/google-visualization-issues#2054]
Hi,

Firstly I would like to say google.visualization.BubbleChart is a good library and  I am working on that  
But I am not getting timestamp on tooltip even though I've provided the timestamp in the data

Please see the code shared in JSFiddle:
http://jsfiddle.net/Divyashree/jtfxj20u/14/

Could anyone help me find out what piece of code I'm missing to get  the timestamp like below screenshot

![image](https://cloud.githubusercontent.com/assets/10521928/9913263/f7520076-5c79-11e5-9384-7a1fe4bea96e.png)

Currently the screen looks below
![image](https://cloud.githubusercontent.com/assets/10521928/9913219/b46e9aee-5c79-11e5-8b0a-5b0dc840065c.png)

Appreciate your help and time in advance

Thanks & Regards
Divya

**Comment by dlaliberte** [comment]
You should use 'datetime' instead of 'date'.  See: http://jsfiddle.net/jtfxj20u/15/
(Also note, in jsfiddle, you should turn off the Fiddle Option to Normalize CSS since it messes with the font sizes.

**Comment by DivyashreeMS** [comment]
Thank you Dlaliberte for the Quick response.
