### ISSUE TITLE
Role:Style in Material bar charts

### ISSUE THREAD

**Issue by neilptel** [google/google-visualization-issues#2080]
For Material bar charts, I need to set different bar colors based on some data. using 'role:style' works for the simple bar charts, but seems its not working when there are multiple bars in same row.

Below is my code, Any ideas if this is at all possible?

var data = new google.visualization.DataTable();
    data.addColumn('string', '');
    data.addColumn('number', '2000');
    data.addColumn('number', '2001');
    data.addColumn({type: 'string', role: 'style'});   //for year 2000 bar
    data.addColumn({type: 'string', role: 'style'});   //for year 2001 bar
    data.addRow(['Orange', 10, 10,'color: #FF8000','color: #FF8000']);
    data.addRow(['Red', 25, 15,'color: #FF0000','color: #FF8000']);
    data.addRow(['Green', 10,20, 'color: black','color: #FF8000']);
    data.addRow(['Blue', 12,10, 'color: #0000FF','color: #FF8000']);
    data.addRow(['Purple', 25,10, 'color: #800080','color: #FF8000']);
    // Create and draw the visualization.
    var chart = new google.visualization.ColumnChart(document.getElementById('chart'));
    chart.draw(data, option);

if you run the code the 1st bar (year 2000) is always blue, I need to set it's color.

Try here: http://jsfiddle.net/nilkanth/cvy1oqLp/1/

**Comment by grabks** [comment]
@onmission role: 'style' applies to the data column to the left of it. Order matters. [Here's a fixed version of your jsfiddle](http://jsfiddle.net/ao5jav8g/).

**Comment by neilptel** [comment]
Thanks!!  Never realized that
