### ISSUE TITLE
Internet Explorer 11: Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by vamshikkalagiri** [google/google-visualization-issues#2084]
When two bar graphs are loaded on the same page in Internet Explorer 11 it is showing Object doesn't support property or method 'contains' error message. 
Screenshot:
![image](https://cloud.githubusercontent.com/assets/11141719/10588190/d424b98c-7672-11e5-9c8a-aa18d278db5e.png)

Any suggested fix to resolve this issue? 
I am using : google.load('visualization', '1.0', { 'callback': drawChart, 'packages': ['bar'] });

**Comment by grabks** [comment]
This is a known issue, and has been fixed in release 43.

However, we have been having issues with actually pushing the release, so it's currently only available via [Frozen Versions](https://developers.google.com/chart/interactive/docs/library_loading_enhancements#frozen-versions).

**Comment by vamshikkalagiri** [comment]
Thanks for your answer. Is there a blog/feed where I could be notified when this gets deployed?

**Comment by grabks** [comment]
We post all updates on the [Google Group for Google Visualization API](https://groups.google.com/forum/#!forum/google-visualization-api). You can find the stickied V43 release post [here](https://groups.google.com/forum/#!topic/google-visualization-api/6Gexd2lr8vU).
