### ISSUE TITLE
Pie chart legend position "labeled" does not work in IE8

### ISSUE THREAD

**Issue by stanggt3** [google/google-visualization-issues#2088]
It did not work on my chart so I dumbed it down to the basic example. Using this standard code does not work in IE8 but works fine in other browsers.  The chart will render fine when you remove the position line.

A red box shows up where the chart should be that says "undefined" is null or not an object

```
  google.setOnLoadCallback(drawChart);
  function drawChart() {

    var data = google.visualization.arrayToDataTable([
      ['Task', 'Hours per Day'],
      ['Work',     11],
      ['Eat',      2],
      ['Commute',  2],
      ['Watch TV', 2],
      ['Sleep',    7]
    ]);

    var options = {
      title: 'My Daily Activities',
      legend: {
        position: 'labeled'
        }
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);
  }
```

**Comment by grabks** [comment]
I just tested your bit of code with an IE8 virtual machine from modern.ie, and everything worked perfectly for me. Here is a screenshot:
![screen shot 2015-10-21 at 2 41 29 pm](https://cloud.githubusercontent.com/assets/11892394/10646698/97732352-7802-11e5-86e3-171e04e1f2ff.png)
