### ISSUE TITLE
Insert an image instead of a string in annotations

### ISSUE THREAD

**Issue by analumonzon** [google/google-visualization-issues#2096]
I would love to be able to display an image instead of a string in the annotation role. Is that possible?
This is a demo from Highcharts:
![image](https://cloud.githubusercontent.com/assets/10563947/10835752/5b0c2df4-7e6b-11e5-9dfc-f9608ebbc7c7.png)

**Comment by nbering** [comment]
You're looking for Overlays. https://developers.google.com/chart/interactive/docs/overlays

I have an example adapted to angular on codepen. http://codepen.io/Balrog30/pen/yNZxKr

**Comment by analumonzon** [comment]
thank you, this looks very good.
