### ISSUE TITLE
Line Chart Adding extra years

### ISSUE THREAD

**Issue by rbugby** [google/google-visualization-issues#2106]
Line chart is adding extra years on x-axis. Using IE 9 on Windows 7 Enterprise. 

![linechartissue](https://cloud.githubusercontent.com/assets/15344460/11145917/b9ab297e-89d7-11e5-8a1e-c1cd8f5b5966.PNG)

[LineChart html.docx](https://github.com/google/google-visualization-issues/files/33934/LineChart.html.docx)

**Comment by dlaliberte** [comment]
You are probably specifying the format to only show the year.  If you also show the month, I bet you'll see Jan and Jul for each year.

**Comment by dlaliberte** [comment]
Actually, looking at your code, it appears your dates are actually just numbers.  In that case, the problem is that your format is showing only the whole numbers.  You would otherwise see, e.g. 2013.5.

**Comment by rbugby** [comment]
X-axis values are numbers not dates. 
Issue seems to arise when column is set to number on x-axis:
    [2013, 1] versus ["2014", 1.9].
If the first value in array is not number (is string) then you lose the trend line and vertical grid lines.
With the first value in array a number, multiple extra years appear. See graphic below.

![linechartissue2](https://cloud.githubusercontent.com/assets/15344460/11148229/71da21e2-89e9-11e5-9038-51b0d506b01b.PNG)

[LineChart html2.docx](https://github.com/google/google-visualization-issues/files/34020/LineChart.html2.docx)

**Comment by dlaliberte** [comment]
You probably should just specify the tick explicitly with this option: 

   hAxis: { ticks: [ 2012, 2013, 2014, 2015 ] }

**Comment by rbugby** [comment]
Explicitly defining ticks make dynamic generation a bit complicated. This issue seems to occur when the x-axis is are Dates as well.
![linechartissue3](https://cloud.githubusercontent.com/assets/15344460/11153775/3c2d9d9c-8a09-11e5-9076-9da9ef6c2994.PNG)
[LineChart html3.docx](https://github.com/google/google-visualization-issues/files/34219/LineChart.html3.docx)

**Comment by rbugby** [comment]
Line Chart Trend lines DO NOT work as stated on https://developers.google.com/chart/interactive/docs/gallery/trendlines. Below are the results for the same data in a Line and Scatter chart. Also  attached below is .docx with html code.

![linechartissue4](https://cloud.githubusercontent.com/assets/15344460/11155128/b06db1bc-8a11-11e5-92f3-25e3399fe0c6.PNG)
[LineChart html4.docx](https://github.com/google/google-visualization-issues/files/34271/LineChart.html4.docx)

**Comment by dlaliberte** [comment]
Here is your example in a jsfiddle: http://jsfiddle.net/dlaliberte/od7yf5z2/  I removed the format option for clarity.

Would you mind saying what you believe is not working regarding the trendlines?    The difference in the horizontal axis is not related to the trendlines, but an unintended side effect of using a Line chart vs Scatter, which you can tell by removing the trendline option.

**Comment by rbugby** [comment]
The additional tick marks between 1 and 2 (1.5), 2 and 3 (2.5), 3 and 4 (3.5). The visualization object is displaying data that was not included in the data set.

**Comment by dlaliberte** [comment]
The axis ticks are guidelines for where the values are, not that the ticks correspond to values.  That's the way charts work most places.    

If you want ticks that correspond exactly to your data values, use the 'ticks' option.  You could specify the gridlines.count option to specify the same number of ticks as the length of your array, but that is not a guarantee that you will get that number, if it doesn't work out for some reason.
