### ISSUE TITLE
BUG: The last day of the relevant month Timeline chat

### ISSUE THREAD

**Issue by kambuki** [google/google-visualization-issues#2118]
When you enter data until November 30, 2015 ~ December 1, 2015
November 31 2015 does not exist is displayed on the Timeline chat.

When the x-axis is displayed in hours.

31 November 2015 I would like to know if this treatment method to suppress one time

**Comment by dlaliberte** [comment]
It is not clear what you are saying or asking.  November 31 does not exist, and is not displayed in charts.  Perhaps you are being tricked by the 0-based months, such that new Date(2015, 10, 30) is actually November 30, and new Date(2015, 11, 31) is actually December 31.

**Comment by kambuki** [comment]
[HtmlPage.txt](https://github.com/google/google-visualization-issues/files/53545/HtmlPage.txt)

When you see the execution results
2015-11-30 09:00:00 - 2015-12-01 09:00:00 resulting data is being queried between
November 30, December 1 and not the data in two days
November 30, November 31 , December 1 samil between data queries like doeneungeot .

**Comment by kambuki** [comment]
When you see the execution results
2015-11-30 09:00:00 - 2015-12-01 09:00:00 resulting data is being queried between
November 30, December 1 and not the data in two days
November 30, November 31 , December 1 samil between data queries like doeneungeot .

**Comment by dlaliberte** [comment]
I see from the code that you posted that you are using your date values like this:  new Date(Number(items[3]), Number(items[4]), Number(items[5]), Number(items[6]), Number(items[7]), Number(items[8])), new Date(Number(items[9]), Number(items[10]), Number(items[11]), Number(items[12]), Number(items[13]), Number(items[14]))  

But the items in your data look like this: 2015,11,30,9,37,29.  So as I said, new Date(2015, 11, 30, ...) is actually December 30, not November 30.  Months start with 0, so 11 is December and 10 is November.  

So change your data or change your code to subtract one from your month numbers and it should work better.
