### ISSUE TITLE
Geo map shows incorrect data for india (Jammu & Kashmir Missing and wrongly plotted the graph)

### ISSUE THREAD

**Issue by jawahit** [google/google-visualization-issues#2157]
![india_head_missing](https://cloud.githubusercontent.com/assets/6762744/12646161/6a2748fc-c5f4-11e5-9a84-cd9f9efbc01f.png)

please find the code below for more details:

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

```
   <div id="geochart-colors" style="width: 700px; height: 433px;"></div>
  google.charts.load('current', {'packages':['geochart']});
  google.charts.setOnLoadCallback(drawRegionsMap);

  function drawRegionsMap() {
    var data = google.visualization.arrayToDataTable([
      ['Country'],
      ['India']
    ]);

    var options = {
      region: '034', // Africa
      colorAxis: {colors: ['#00853f', 'black', '#e31b23']},
      backgroundColor: '#81d4fa',
      datalessRegionColor: '#f8bbd0',
      defaultColor: '#f5f5f5',
    };

    var chart = new google.visualization.GeoChart(document.getElementById('geochart-colors'));
    chart.draw(data, options);
  };
```

**Comment by grabks** [comment]
Hi, it sounds like you want to use the `domain: 'IN'` option, which makes Jammu and Kashmir a part of India. If this isn't the problem you're experiencing, you'll have to give us more details about exactly how they're plotted incorrectly.

**Comment by jawahit** [comment]
Thanks for point to take it from you . we have given domain and we can able to plot india correctly.
