### ISSUE TITLE
Multiple Domains is not supported in Geo Map

### ISSUE THREAD

**Issue by jawahit** [google/google-visualization-issues#2163]
We are trying to Plot Geo chart with multiple domains like IN,PK,CN (India,Pakistan,China) which is neighborhood countries but disputed territories are plotted incorrectly.India Jammu & Kashmir shows part of Pakistan.

In Domain data type is String so not able to plot multiple countries for domainId
![indiachina](https://cloud.githubusercontent.com/assets/6762744/12718743/9712a9f4-c916-11e5-942c-52e0a20d262c.png)

Please find the attached image.

**Comment by grabks** [comment]
@jawahit The only domains that the GeoChart supports are `"IN"` (for India) and `"COM"` (for the rest of the world), and only one can be used at a time, so I'm not entirely sure what you mean by "multiple domains". It looks like you're just plotting those three countries, so I think you have a different definition for "domain" than we do.

Jammu and Kashmir will show as a part for India for `domain: "IN"`, but as disputed territories for `"COM"`.

[Here's an interactive jsfiddle that switches between the two options.](http://jsfiddle.net/hyhp67sb/)
