### ISSUE TITLE
Broken Quick Start

### ISSUE THREAD

**Issue by resolutedreamer** [google/google-visualization-issues#2168]
I'm copy and pasting the code from this quick start and it's not working.
https://developers.google.com/chart/interactive/docs/quick_start

Please help!

**Comment by grabks** [comment]
@resolutedreamer Sorry about that! It appears that the example wasn't quite correct. The error is that instead of `google.setOnLoadCallback(drawChart);`, it should be `google.charts.setOnLoadCallback(drawChart);`.

[Here is a working jsfiddle of the example](https://jsfiddle.net/3dk84ofw/)

**Comment by resolutedreamer** [comment]
Thanks it works!
