### ISSUE TITLE
Google Visualization Org Chart Setbacks in financial applications

### ISSUE THREAD

**Issue by MARKUSER** [google/google-visualization-issues#2169]
I am new to Google OrgCharts, please kindly suggest on below points...

I did one small application for myself using Google Visualization API (Org Chart). I like it and now i feel this API help me to address one of the business use case. Please suggest me on following questions. 1. Is it advisable to have these Google Visualization API in financial applications. 2. Google Visualization API need any licensing for commercial usage purpose. 3. Since it is not an open source framework, i am unable to track or assume how Google Visualization API is using my application data to render the chart.

 a) Will it store the data that is being passed from my site?
 b) How secure my data if i pass key values to org charts to prepare and render the chart on my website page.
I sincerely request you to provide your valuable suggestions.

Sample Example (not actual code):

<script src="http://www.google.com/jsapi" type="text/javascript"></script>

function drawChart(dataValues) {
            data = new google.visualization.DataTable();
            chart = new google.visualization.OrgChart(document.getElementById('chart_div'));
            data.addColumn('string', 'PlanName');
            data.addColumn('string', 'PaymentAmount');
            data.addColumn('string', 'ValidationId');
            data.addColumn('string', 'AccountName');

```
        for (var i = 0; i < dataValues.length; i++) {
            data.addRow([{ v: dataValues[i].PlanName, f: dataValues[i].Name }, dataValues[i].AccountName]);



            }




        // Draw the chart, setting the allowHtml option to true for the tooltips.
        chart.draw(data, {
            allowHtml: true, allowCollapse: true, size: 'medium', explorer: {
                maxZoomOut: 100,
                keepInBounds: true
            }
        });
        google.visualization.events.addListener(chart, 'select', selectHandler);


    }
```

Source: developers.google.com/chart/interactive/faq
Is Google logging all my chart data?
The chart data included in the HTTP request is saved in temporary logs for no longer than two weeks for internal testing and debugging purposes. Of course you should understand that if your chart appears in an image tag on a public webpage, it could be crawled.

 2) i am thinking *_jsapi *_file has some mechanism to send the data to google and prepare the chart and give it back to DOM (it is just a guess).

**Comment by MARKUSER** [comment]
Can any one please help me providing your valuable comments

**Comment by nbering** [comment]
@MARKUSER I can't speak for the google team, but I don't see any HTTP requests being made in association with chart draws, just requests to get the resources during the loading phase. If you have security audits that require something more than that, I would suggest you defer the question to a legal or  IT Security specialist who is familiar with your requirements.

**Comment by grabks** [comment]
@MARKUSER Sorry about the delay. I'll attempt to answer your all questions.

1) Google Charts may be used for any purpose as long as you do not break our [Terms of Service](https://developers.google.com/chart/terms)

2) [Yes, Google Charts may be used for commercial purposes.](https://developers.google.com/chart/interactive/faq#commercialuse)

3) Google Charts does not send your data to Google, unless you are using [our deprecated Image Charts](https://developers.google.com/chart/image/) or the [ImageChart wrapper](https://developers.google.com/chart/interactive/docs/gallery/genericimagechart), which work by sending your data to the server and returning a rendered image, or if you are using the [GeoChart](https://developers.google.com/chart/interactive/docs/gallery/geochart) or [the deprecated Geomap](https://developers.google.com/chart/interactive/docs/gallery/geomap), which may send your data to Google for geocoding (though this behavior can be avoided).

a) The OrgChart will not send data to Google under any circumstances.

b) The OrgChart is rendered on the client-side (in JavaScript). No data is sent to Google from the OrgChart. Your data is as secure as the rest of your website.

**Google is not logging any of your data** unless you're using one of the charts I mentioned above.
2) `jsapi` is just a loading mechanism. It is for sending JavaScript code to your browser. Like any other HTTP server, we may log the requests made to it (i.e. the user requested /jsapi), but we do not send your data to any server, except in the cases outlined above.

**Comment by MARKUSER** [comment]
Thanks grabks. Your responses are very clear. One last question, if i want to deploy Google OrgChart solution in production environment, my company should pay for it ? or still we can use it for free ?... I didn't understand much from Terms and Services link.
Is there any option to make JSAPI file offline... may be not now in near feature.

**Comment by grabks** [comment]
No payment is currently required for the use of Google Charts, either for commercial purposes or not.

I hesitated to mention this in my initial response, since it wasn't as relevant, but we no longer recommend using `/jsapi` to load Google Charts. Please refer to [our documentation](https://developers.google.com/chart/interactive/docs/basic_load_libs) for the recommended way of loading Google Charts.

We currently do not have any way of using Google Charts offline, and downloading the source code is actually against our Terms of Service (aside from being dangerous due to possible security issues). We do intend to eventually provide downloadable versions of Google Charts, but I have no information for when/how/if this will actually happen.

**Comment by MARKUSER** [comment]
Excellent... Appreciated your quick answers to my questions.
