### ISSUE TITLE
Add link to google chart title

### ISSUE THREAD

**Issue by prabhathAmila** [google/google-visualization-issues#2170]
how can i add link to google chart title [view source link]
![eb2ls](https://cloud.githubusercontent.com/assets/15810276/12969301/93f98130-d0a4-11e5-957b-dc17c42c2738.png)

**Comment by grabks** [comment]
Hi, this is not currently possible to do within the constraints of Google Charts. We do intend (at some distant point in the future) to make this possible, but the timeline is both very unclear and very far off.

Your best bet to accomplish this is to not show the title as part of the chart, but add a div above your chart that shows the title and the link. This will also give you more flexibility, allowing you to bold/underline/change the font for parts of the title.

**Comment by kishan3** [comment]
Hey, Guys is this possible in 2019?

**Comment by ChaoTingChen** [comment]
Hey, Guys is this possible in 2020?
