### ISSUE TITLE
material design

### ISSUE THREAD

**Issue by supun19** [google/google-visualization-issues#2176]
cant Stacked

**Comment by supun19** [comment]
thnk

**Comment by grabks** [comment]
@supun19 You are probably forgetting to use google.charts.Bar.convertOptions.

[Here is an example of a stacked Material Bar Chart](http://jsfiddle.net/wa9054xo/).

**Comment by supun19** [comment]
thank you

**Comment by supun19** [comment]
but how to give different color to stack

**Comment by grabks** [comment]
You can customize the colors of the series via the [series.<index>.color option](http://jsfiddle.net/1epnr67k/1/).

**Comment by supun19** [comment]
thank you very mach bro (Y)
