### ISSUE TITLE
Uncaught TypeError: fH.pc is not a function - VM54:635 

### ISSUE THREAD

**Issue by ovntatar** [google/google-visualization-issues#2182]
Since today "Fri Feb 26 09:33:36 UTC 2016" my simple html code doesn't work:

```
<html>
   <head>
      <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
      <script type="text/javascript">
         google.charts.load('current', {packages: ['corechart', 'line']});
         google.charts.setOnLoadCallback(drawBasic);

         function drawBasic() {

         var data = new google.visualization.DataTable();
         data.addColumn('number', 'X');
         data.addColumn('number', 'Urls');

         data.addRows([
         [0, 0],   [1, 10],  [2, 23],  [3, 17],  [4, 18],  [5, 9],
         [6, 11],  [7, 27],  [8, 33],  [9, 40],  [10, 32], [11, 35],
         [12, 30], [13, 40], [14, 42], [15, 47], [16, 44], [17, 48],
         [18, 52], [19, 54], [20, 42], [21, 55], [22, 56], [23, 57],
         [24, 60], [25, 50], [26, 52], [27, 51], [28, 49], [29, 53],
         [30, 55], [31, 60], [32, 61], [33, 59], [34, 62], [35, 65],
         [36, 62], [37, 58], [38, 55], [39, 61], [40, 64], [41, 65],
         [42, 63], [43, 66], [44, 67], [45, 69], [46, 69], [47, 70],
         [48, 72], [49, 68], [50, 66], [51, 65], [52, 67], [53, 70],
         [54, 71], [55, 72], [56, 73], [57, 75], [58, 70], [59, 68],
         [60, 64], [61, 60], [62, 65], [63, 67], [64, 68], [65, 69],
         [66, 70], [67, 72], [68, 75], [69, 80]
         ]);

         var options = {
         hAxis: {
          title: 'Time- Days'
         },

         };

         var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

         chart.draw(data, options);
         }
      </script>
   </head>
   <body>
      <div id="chart_div"></div>
      <br />
   </body>
</html>`
```

may some changes affected  https://www.gstatic.com/charts/loader.js

thanks

**Comment by agladysh** [comment]
Workaround: freeze API version to 43.

http://stackoverflow.com/questions/35648530/google-visualization-charts-api-examples-are-broken-how-to-fix-them

**Comment by ovntatar** [comment]
yep - It's working with the Workaround
from: google.charts.load('current', {packages: ['corechart', 'line']});
to: google.charts.load('43', {'packages':['corechart', 'line']});

thanks

**Comment by cmirnow** [comment]
thank you, workaround is works.

**Comment by grabks** [comment]
Hello everyone,

These issues were due to propagation delays/caching issues with us pushing out a new a version of Google Charts. **I strongly recommend against using the workaround suggested in this thread**. Using the workaround will mean that you will not get any bugfixes or new features. While this might be the right thing to do for some users, we expect that it's not the right thing for the majority. The issues you're experiencing should no longer be occurring, so it should be safe to switch back to `'current'` or `'upcoming'`.

**Comment by konkers** [comment]
I am still seeing these issues with current.

**Comment by agladysh** [comment]
The workaround is just that, a workaround. I assume that the users are smart enough to disable it when the issue would be resolved ;-)

**Comment by arikagit** [comment]
Still seeing this issue on current here.

**Comment by austinwang** [comment]
also still seeing the issue on current.

**Comment by dlaliberte** [comment]
We have isolated to problem, and it is caching related.  We will be able to
avoid this problem in the future, and for now, you can work around the
problem by changing 'current' to '43' or '44', or you can force your
browser to flush the cache or ignore the cache.

The browser caches should expire by this friday as well and I just made a
change that might help reset the caches within an hour.

On Tue, Mar 1, 2016 at 3:10 PM, Austin Wang notifications@github.com
wrote:

> also still seeing the issue on current.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2182#issuecomment-190882155
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA
