### ISSUE TITLE
ReferenceError: TB is not defined

### ISSUE THREAD

**Issue by Daniel-Marcelo** [google/google-visualization-issues#2183]
Hi,

My chart has been 100% operational for the past month but is giving me major issues today. There is an error "ReferenceError: TB is not defined" pointing to https://www.gstatic.com/charts/loader.js line 133. Would greatly appreciate help. Find it very strange that it has been working for the past month and only now begins to trouble me. It is worth noting I attempted to run in js fiddle a google chart example taken directly from the website. When reviewing the console the same error appeared. Could this possibly be an issue on your end? Thanks.

**Comment by dlaliberte** [comment]
Sounds like this was another instance of the caching/propagation error due to pushing out a new release.  We will try to avoid this problem in future releases.
