### ISSUE TITLE
Annotation Chart stopped working (EB is not defined)

### ISSUE THREAD

**Issue by tsankuanglee** [google/google-visualization-issues#2189]
The chart doesn't show up. Loading the demo page
https://google-developers.appspot.com/chart/interactive/docs/gallery/annotationchart
caused an error error in the console that says: "Uncaught ReferenceError: EB is not defined".

Tested on Chromium/Firefox latest version.

**Comment by lipis** [comment]
:+1: 

https://google-developers.appspot.com/chart/interactive/docs/gallery/linechart

```
Uncaught ReferenceError: Hh is not defined
```

**Comment by dlaliberte** [comment]
Change 'current' to '44' and it should work.

On Mon, Feb 29, 2016 at 5:48 AM, Lipis notifications@github.com wrote:

> [image: :+1:]
> 
> https://google-developers.appspot.com/chart/interactive/docs/gallery/linechart
> 
> Uncaught ReferenceError: Hh is not defined
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2189#issuecomment-190151267
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by lipis** [comment]
fixed..
