### ISSUE TITLE
Google Annotation chart throws Uncaught TypeError cannot read property 'prototype' of null

### ISSUE THREAD

**Issue by blgn4** [google/google-visualization-issues#2200]
Its not working even on the example code at this  [link](https://developers.google.com/chart/interactive/docs/gallery/annotationchart)  nor on the code it yourself JSFiddle page.

**Comment by dlaliberte** [comment]
It should work better now.  I updated the loader to redirect directly to the correct version, which avoids the whole problem with redirect caching in the browser not being updated.

**Comment by blgn4** [comment]
I am still facing the same issue even on the google annotation chart example page. I have also cleared the browser cache and checked it.

**Comment by dlaliberte** [comment]
Try again.  The problem has been redirects that were stored in each user's browser cache that we could not update.  Now we are avoiding those redirects.
