### ISSUE TITLE
Timelines Graph: Month Showing incorrectly (adding extra one month by default)

### ISSUE THREAD

**Issue by Gopi7a** [google/google-visualization-issues#2202]
Go to Timelines chart:
https://developers.google.com/chart/interactive/docs/gallery/timeline

Now check the examples: "A Simple Examples"
There its given the name and date like this 
[ 'Washington', new Date(1789, 3, 30), new Date(1797, 2, 4) ]

It means 1789 March,30 to 1797 Feb, 4

But in chart showing April 1789 to March 1797

How could extra one month is added in chart? Same issues I got in my project also.
Could you please guide me to resolve this month issues.

Thanks in advance :)

**Comment by d4mation** [comment]
[In a JavaScript `Date` Object, Months are 0-indexed and years and days are not.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

Threw me off as well when I was setting up a Gantt Chart. If you're pulling the Date from somewhere else you'll just want to subtract one from your Month as you're making the `Date` Object.

**Comment by grabks** [comment]
@d4mation- is correct. Closing.
