### ISSUE TITLE
I want use google chart in chinese,

### ISSUE THREAD

**Issue by YealZoy** [google/google-visualization-issues#2203]
I want use google chart in chinese,everybody,who knows the answer?

**Comment by nbering** [comment]
I don't know about Chinese specifically, but to change the language you can add something like this to your project, replacing `'en'` with whatever your language code is. This will set some of the defaults, like date formatting, to something that makes sense in your language, provided the language is supported. I couldn't find a list of supported languages.

```JavaScript
angular.module('myApp')
  .value('googleChartApiConfig', {
    version: '1',
    optionalSettings: {
      packages: ['corechart'],
      language: 'en'
    }
  });
```

**Comment by nbering** [comment]
See [loading with locales](https://developers.google.com/chart/interactive/docs/basic_load_libs#loadwithlocale) in the documentation. I couldn't find a list of supported language codes, though.

**Comment by grabks** [comment]
@YealZoy You can load Google Charts with the Chinese locale by specifying a language code in the `'language'` parameter to the `'google.charts.load'` call, as in the documentation @nbering pointed to. [Here is an example of a Line Chart loaded in with the Chinese locale](http://jsfiddle.net/aqtz3dv9/).
