### ISSUE TITLE
Emphasis Role on Line Chart: Set Line Style

### ISSUE THREAD

**Issue by ccrvincent** [google/google-visualization-issues#2204]
It would be nice to be able to set the emphasis style for the line charts.

For example:

```
  data.addColumn('number', 'X');
  data.addColumn('number', 'Dogs');
  data.addColumn({type: 'number', role: 'emphasis'});

  var Options = {
    series: {
      0: {
        lineDashStyle: [10, 2],
        lineWidth: 2
      },
      1: {
        lineWidth: 4,
        color: 'red'
      }
    }
  }
```

Would result in a table looking more like this:

![dashedoverlay](https://cloud.githubusercontent.com/assets/12836291/13542838/4e99c404-e22b-11e5-9cf0-7f24c44fd69d.PNG)

As of now, you have to replicate the first column, use nulls where you do not want emphasis, set interpolateNulls and visibleInLegend to false.

**Comment by dlaliberte** [comment]
Check out the column roles feature: https://developers.google.com/chart/interactive/docs/roles

**Comment by ccrvincent** [comment]
I am talking about Roles.  There is either no way to define the style
changes used for an emphasis role, or it is undocumented.

**Comment by grabks** [comment]
@ccrvincent You are correct that it is currently not possible to customize the style of the emphasis role. If that is a requirement, please look into using the more flexible `style` role.

**Comment by ccrvincent** [comment]
I was looking at Style (though not until after I made my initial post), but styling Emphasis would be far cleaner as my data is already boolean.

Hence the feature request.

**Comment by nbering** [comment]
@ccrvincent You could probably get the functionality you're looking for by combining the styles role with a calculated column in DataView. Have the calculated column look at the emphasis boolean value you already have and output the style you want. [See SetColumns on DataView](https://developers.google.com/chart/interactive/docs/reference#DataView_setColumns)

**Comment by ccrvincent** [comment]
Good catch, that would be the easiest way with the current functionality.  Thanks!
