### ISSUE TITLE
LineChart new Date(2016, 2, 29), new Date(2016, 3, 1) leads to new group at 31.03.16

### ISSUE THREAD

**Issue by yuristru** [google/google-visualization-issues#2205]
Using some dates in a LineChart leads to unexpected grouping of dates:
`data.addRows([         
              [new Date(2016, 2, 27), 2],
              [new Date(2016, 2, 28), 26],
              [new Date(2016, 2, 29), 46],
              [new Date(2016, 3, 1), 57],
              [new Date(2016, 3, 2), 63],
              [new Date(2016, 3, 3), 73],
              [new Date(2016, 3, 4), 39],     
              [new Date(2016, 3, 5), 24],          
            ]);`

Grouped Dates:
27/3/16 - 29/3/16 - 31/3/16 - 2/4/16 - 4/4/16

Maybe its about the current leap year?

Full Code:
`var data = new google.visualization.DataTable();
            data.addColumn('date', 'Date');
            data.addColumn('number', 'Count');

```
        data.addRows([

          [new Date(2016, 2, 27), 2],

          [new Date(2016, 2, 28), 26],

          [new Date(2016, 2, 29), 46],

          [new Date(2016, 3, 1), 57],

          [new Date(2016, 3, 2), 63],

          [new Date(2016, 3, 3), 73],

          [new Date(2016, 3, 4), 39],

          [new Date(2016, 3, 5), 24],

        ]);


        var options = {
          width: '100%',
          height: '450',
          legend: 'none',
          hAxis: {
            format: 'd/M/yy',
            gridlines: {count: 7},
            slantedText:true,
            slantedTextAngle:90
          },
          vAxis: {
            gridlines: {color: 'none'},
                minValue: 0

              },
              chartArea: {
                top: 55,
                width: '90%',
                height: '70%' 
              }
            };

            var chart = new google.visualization.LineChart(document.getElementById('chart_div2'));
        chart.draw(data, options);`
```

**Comment by nbering** [comment]
First, I think your real issue might be related to the common confusion about JavaScript's zero-indexed months. Much like the first element of an array, the first month is 0, so the dates you've entered are actually March and April, not February and March. This strange behaviour confuses people a lot.

Second, your description of "grouping" is pretty vague. If fixing the months as I've described above does not help, I think a more detailed description of the unexpected behaviour would be helpful to the Google Visualization team. A screenshot would help, but [jsFiddles](jsfiddle.net) are even better.

**Comment by yuristru** [comment]
Hallo Nicholas,

thanks for your hint! It was the date problem and everythings works fine now.
Never read about that somewhere ... maybe Google can give a hint in the documents where the date fields are discribed.

Kind regards Yuri

**Comment by nbering** [comment]
@YuriStruszczynski Pretty sure they do somewhere, but not in every example. It's not actually specific to the charts, it's part of the JavaScript specification.
