### ISSUE TITLE
Timeline chart 

### ISSUE THREAD

**Issue by TechBCS** [google/google-visualization-issues#2219]
Is it possible to use start time and duration in minutes or seconds rather than start time and end time?

**Comment by grabks** [comment]
No, this is not possible. I have a hard time imagining how a Timeline would handle these kinds of ambiguities (i.e. how would it know where to start a bar). Perhaps what you're looking for is a [Gantt Chart](https://developers.google.com/chart/interactive/docs/gallery/ganttchart#a-simple-example)?
