### ISSUE TITLE
Unable to override interval colors when using style column

### ISSUE THREAD

**Issue by ianlewis** [google/google-visualization-issues#2229]
When using intervals with a column with role: style, the style overrides the color specified for the interval. Because of that, the interval cannot be seen properly when used with bar or column graphs.

https://jsfiddle.net/hy7221g1/

**Comment by dlaliberte** [comment]
Instead of just specifying the color in the style, which specifies the color for all features of the data value, you can qualify it to only change the bar color like this:  'bar {color: green}'.  Then your interval color option will be used.
