### ISSUE TITLE
Add support for duration data type

### ISSUE THREAD

**Issue by mfulton26** [google/google-visualization-issues#2231]
I want to be able to sum time durations (e.g. "1:05:45", "5:40:13", "1:56:21" sum to "8:42:19") in Google Sheets but I get an error:

> **Error**
> Unable to parse query string for Function QUERY parameter 2: AVG_SUM_ONLY_NUMERIC

I see that currently "supported data types are `string`, `number`, `boolean`, `date`, `datetime` and `timeofday`" ([Query Language Reference (Version 0.7)  |  Charts  |  Google Developers](https://developers.google.com/chart/interactive/docs/querylanguage)). Will `duration` be added?

Thank you.

**Comment by dlaliberte** [comment]
That error message actually comes from Google Sheets, though it may be that the Google Charts query is requesting an operation that fails on the Google Sheets side.  Could I ask you to ask in the Google Sheets API forum to find out what their QUERY function supports?  https://groups.google.com/forum/#!forum/google-spreadsheets-api  It appears they don't support this SUM operation on non-numeric values, though they could.

**Comment by mfulton26** [comment]
Ah yes, that makes sense. I have created a new topic there: [Support for duration data types in QUERY function](https://groups.google.com/forum/#!topic/google-spreadsheets-api/P0nEhMSW4Zs). Thank you.
