### ISSUE TITLE
Wrong value for small percentage in google charts

### ISSUE THREAD

**Issue by katia-ua** [google/google-visualization-issues#2233]
Hi there! You have a small bug with google charts for now. If percent is very small - there is wrong name for it. Here is the example of function:

```
function drawChart() 
    {
        var data = new google.visualization.DataTable();
                data.addColumn('string', 'Topping');
                data.addColumn('number', 'Slices');
                data.addRows([['Successful', 1234], ['Failed', 1]]);
                var options = {'title':'Summary automatic tests', 'width':600,'height':400};
                var chart = new google.visualization.PieChart(document.getElementById('chart_div1'));
                chart.draw(data, options);
         }
```

Instead of 'Failed' I get 'Other' although if I change value into 2 - I will get 'Failed'.

**Comment by grabks** [comment]
@katia-ua This is not a bug. This behavior is by design and can be controlled via the `sliceVisibilityThreshold` option. You can disable the behavior entirely by setting the value of that option to `0`, like in [this jsfiddle](http://jsfiddle.net/kkqx1m9s/).
