### ISSUE TITLE
Documentation, just small error in "How to print pngs" section

### ISSUE THREAD

**Issue by hpiso** [google/google-visualization-issues#2236]
https://developers.google.com/chart/interactive/docs/printing#overview

var my_div = document.getElementById('my_div');
var my_chart = new google.visualization.ChartType(**chart_div**);

should be :

var my_div = document.getElementById('my_div');
var my_chart = new google.visualization.ChartType(**my_div**);

**Comment by orwant** [comment]
Fixed -- thanks for pointing this out!
