### ISSUE TITLE
Comment wrong in multiple chart example

### ISSUE THREAD

**Issue by thebagmaster** [google/google-visualization-issues#2245]
https://developers.google.com/chart/interactive/docs/basic_multiple_charts#draw-multiple-charts-on-one-page

Anthony's Pizza Data is not commented correctly; also the instantiation comment.
Copy and paste strikes again.

Love You Google
Keep up the good work

**Comment by dlaliberte** [comment]
Thanks for noticing :)

**Comment by orwant** [comment]
Fixed.
