### ISSUE TITLE
Timeline Chart Dates are off by one month

### ISSUE THREAD

**Issue by alanjuden** [google/google-visualization-issues#2248]
I just noticed that my timeline charts are all off by one month and verified in the samples on this page: https://developers.google.com/chart/interactive/docs/gallery/timeline#overview

If you specify this date: new Date(1789, 3, 30) - it displays as April 1789. All dates are showing one month later than it should be.

**Comment by dlaliberte** [comment]
Hi Alan,

Month index numbers in JavaScript and most other programming languages
start at 0.  See
https://developers.google.com/chart/interactive/docs/datesandtimes

On Mon, Apr 18, 2016 at 10:22 AM, alanjuden notifications@github.com
wrote:

> I just noticed that my timeline charts are all off by one month and
> verified in the samples on this page:
> https://developers.google.com/chart/interactive/docs/gallery/timeline#overview
> 
> If you specify this date: new Date(1789, 3, 30) - it displays as April
> 1789. All dates are showing one month later than it should be.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2248

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA
