### ISSUE TITLE
Stacked charts with logarithmic axis are wrong

### ISSUE THREAD

**Issue by cptbalu87** [google/google-visualization-issues#2262]
example: data=[['Testdata1', 10, 10], ['Testdata2', 10, 10]]
Using column/area charts with `vAxis: {logScale: true}` and `isStacked: true` options shall result two columns/one area with points on each other, first level at 10, second somewhere between 10 and 100. Instead of this, I can see first level at 10, second at 100
The reason seems to be that stacked values are calculated for log individually, then added up linearly, this should be changed by first calculating stacked values, then finally calculate logs of these results (if log scale is in use), evading the effect of rule

> log(a)+log(b)=log(a*b)

**Comment by dlaliberte** [comment]
You are quite right that this is done wrong.  Thanks for the clear example.  Stacking with logscale was only accidentally partially supported initially, and remains buggy, though we should be able to straighten this out.

**Comment by dlaliberte** [comment]
This is actually fixed by a recent change, now available in v45.  I was worried that my change caused the breakage, rather than fixed it.

**Comment by rfcohen** [comment]
I have a similar problem in that I have a bar chart with multiple series and the y-axis is logarithmic.  However it's all messed up.  I'm using the 'current' version.  I did try '45' with no change.  I'm not sure what you need to help debug this.
![brokenloggraph](https://cloud.githubusercontent.com/assets/1448319/18728354/e11337e2-801a-11e6-814e-d1fd9d8fae27.png)
The column for which the tool tip is presented is correct, but the scale on the left is all cattywampus.
