### ISSUE TITLE
Feature request: Animated transition for Donut.

### ISSUE THREAD

**Issue by kradalby** [google/google-visualization-issues#2265]
Hi

I am currently using the donut chart as a "speedometer" for a dashboard app for LANparties.

As far as I understand from this list: https://developers.google.com/chart/interactive/docs/animation#supported-modifications

The donut chart does not allow animations, which makes our app very jumpy when the speed changes.

The feature I seek is basically that between two states, it will gradually change from old to new.

A screenshot of the application ![nettbrett](https://camo.githubusercontent.com/0782d1f260edd61af928bb7cb988b1a40d36ef15/68747470733a2f2f6b726164616c62792e6e6f2f73732f32303136303430333231353331322e706e67)

If this is the wrong place to post this, I am really sorry!

**Comment by dlaliberte** [comment]
The PieChart (and Donut variation) doesn't support animation, but you could do your own animation with a timer.  Just interpolate between the two values and draw the chart again each step.  This is essentially what the internal animation does.

**Comment by kradalby** [comment]
Thank you for the tips, it worked quite well.
