### ISSUE TITLE
ComboChart incorrect X-Axis scale with 1 data point.

### ISSUE THREAD

**Issue by mhaley-miovision** [google/google-visualization-issues#2272]
The combo chart creates an incorrect X-Axis when given only a single data point.  This can be seen int he following example: https://jsfiddle.net/eL8m5Lo7/1/.

The first chart shown has a single data point and it's x-axis stretches for decades, whereas the second chart shows the correct x-axis with a proper scale.  The only difference between the two charts is how many datapoints are given to each.

**Comment by dlaliberte** [comment]
Hi Mark,

With only a single data point, there is no way for the chart to know what
the appropriate scale is.  You might be charting data that covers decades,
or days, but it can't know that with only a single data point, so you have
to specify the range.  You can use hAxis minValue and maxValue for this
purpose.

On Tue, May 24, 2016 at 3:46 PM, Mark Haley notifications@github.com
wrote:

> The combo chart creates an incorrect X-Axis when given only a single data
> point. This can be seen int he following example:
> https://jsfiddle.net/eL8m5Lo7/1/.
> 
> The first chart shown has a single data point and it's x-axis stretches
> for decades, whereas the second chart shows the correct x-axis with a
> proper scale. The only difference between the two charts is how many
> datapoints are given to each.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2272

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by dlaliberte** [comment]
Admittedly, a single very wide bar doesn't make much sense, however.  But we should probably try to make the bar width be something that fits between whatever gridlines have been set up.
