### ISSUE TITLE
Chart data series shows up mis-aligned for all February data

### ISSUE THREAD

**Issue by guangster** [google/google-visualization-issues#2275]
I have some time-series data that is sorted by date, and plotted to charts with date as the x-axis, the x-axis option is as follows
`hAxis: {
            title: 'Monday of the Week',
            format:'MM/dd/yy'
        }`

Recently I started to notice all the February data-points are aligned to march series labels, and there are no data-points ( that are visible by hovering over the mouse ) aligned to February.

This seems to happen retrospectively for all February data points (2014,2015,2016), but I don't remember seeing them like this before

The data passed looks like it's in order, which is consistent with tracing the plot lines continuously, but it seems on rendering the data gets mis-aligned. 

Following are three screenshots of the seemingly misaligned February data as I trace them.

![image](https://cloud.githubusercontent.com/assets/6445459/15654855/88ed2848-2665-11e6-8e92-b227bc22b2b3.png)

![image](https://cloud.githubusercontent.com/assets/6445459/15654754/e526a586-2664-11e6-8320-e1dc3362db83.png)

![image](https://cloud.githubusercontent.com/assets/6445459/15654863/9aeac10e-2665-11e6-80c0-95d038bbfaec.png)

**Comment by etennapel** [comment]
This was also reported:
http://stackoverflow.com/questions/37528321/goole-visualization-daterangefilter-data-issue-data-conflict-between-feb-and-ma

**Comment by guangster** [comment]
thanks!

I managed to fix by replacing my old import from
`<script type="text/javascript" src="https://www.google.com/jsapi"></script>`
to
`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>`

and init as

```
    google.charts.load('current', {
        'packages': ['corechart', 'controls','table']
    });

    google.charts.setOnLoadCallback(main);
```

**Comment by dlaliberte** [comment]
I'd still like to understand what is happening here.  I have yet to see the problem myself so I have a chance of debugging it.  

If you are loading with https://www.gstatic.com/charts/loader.js, if you could please try the 'upcoming' version and post again if it does not work.

The issue in the jsfiddle linked by @etennapel appears to be quite different, since it involves a DateRangeFilter.  It might be related, but that seems doubtful.

**Comment by etennapel** [comment]
Hi,
Since this morning it appears that also the month of April is missing in my google charts. I am also using the "old" way of loading the library. I still have to try loading the new library to see if it solves my problem.

**Comment by hkmaly** [comment]
In my case, not only April disappeared, but but the last few days of March were rendered in May, producing line from end of the graph back to the beginning. Oh, wait, that's likely just special case of what  guangster reported.
Apparently, I'm using code even older than the old version mentioned, so I'll need to look how to upgrade from

```
var graph_data = new google.visualization.DataTable(#{data.dump});
var graph_view = new google.visualization.#{type}(document.getElementById('#{id}'));
graph_view.draw(graph_data, #{view.to_json});
```

... oh, right, of course. It only needs to add two lines:

```
google.charts.setOnLoadCallback(function() {
var graph_data = new google.visualization.DataTable(#{data.dump});
var graph_view = new google.visualization.#{type}(document.getElementById('#{id}'));
graph_view.draw(graph_data, #{view.to_json});
});
```

**Comment by etennapel** [comment]
In my case the root cause has something to do with (json / javascript)  Date() handling in combination with google datatable. (still using the "old" library loading)

```
        var dt = new google.visualization.DataTable({
    cols: [
           {id:'Tijd' ,label:'Tijd',type:'datetime'}],
    rows: [{c:[{v: 'Date(2016,0,21,00,00,00,0)'}]},
           {c:[{v: 'Date(2016,0,31,00,00,00,0)'}]},
           {c:[{v: 'Date(2016,1,01,00,00,00,0)'}]},
           {c:[{v: 'Date(2016,1,14,00,00,00,0)'}]},
           {c:[ {v: 'Date(2016,1,18,00,00,00,0)'}]}]
    }, 0.6);
```

Returns (Amsterdam time):

```
Thu Jan 21 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
Sun Jan 31 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
Tue Mar 01 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
Mon Mar 14 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
```

So.... I think I will have to check the stuff in [https://developers.google.com/chart/interactive/docs/datesandtimes#dates-and-times-using-the-date-string-representation](url) . It states: 

> Warning: Again, the string representation may be parsed differently by different browsers/versions. Notably, when dealing with time and timezones, there are differences in whether the datetime is returned with a UTC (GMT) timezone, or is offset and returned in local time. This is another reason why the use of datetime strings is not recommended.

So, I think I will have to make my json ==> Date-handling more robust against this.

**Comment by dlaliberte** [comment]
When you specify a date or datetime value with the date-string notation like you are doing, e.g. 'Date(2016,0,21)' then you are avoiding the problem of browser specific date parsing issues.  The part of the documentation that you quoted is talking about specifying dates like this:  new Date('Thu Jan 21 2016 00:00:00 GMT+0100') which required parsing of that string.

**Comment by etennapel** [comment]
Ok thanks, I mixed up on the quote.

However, why do I see the difference here then w.r.t string-represented Date()?

```
           {c:[ {v: 'Date(2016,1,18,00,00,00,0)'}]},
           {c:[ {v: new Date(2016,1,19,00,00,00,0)}]}

```

```
Fri Mar 18 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
Fri Feb 19 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
```

I think this is the problem I have. Am I misunderstanding something?

And... what has changed over the last few days.....?

**Comment by dlaliberte** [comment]
'Date(2016,1,18,00,00,00,0)' will be parsed to the same date as new
Date(2016,1,18,00,00,00,0).  Note the day is 18, not 19.  Days of the month
start with 1.  Every other value starts with 0, but the month index is
surprising.

What changed in the last couple days is the end of the month.  The problem
was that the date-strings are being parsed in a new way that is safer but,
it turns out, incorrect, and it only shows up when the current day is at
the end of a month.  My fault. Sorry.

On Tue, May 31, 2016 at 4:20 PM, etennapel notifications@github.com wrote:

> Ok thanks, I mixed up on the quote.
> 
> However, why do I see the difference here then w.r.t string-represented
> Date()?
> 
> ```
>        {c:[ {v: 'Date(2016,1,18,00,00,00,0)'}]},
>        {c:[ {v: new Date(2016,1,19,00,00,00,0)}]}
> ```
> 
> Fri Mar 18 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
> Fri Feb 19 2016 00:00:00 GMT+0100 (West-Europa (standaardtijd))
> 
> I think this is the problem I have. Am I misunderstanding something?
> 
> And... what has changed over the last few days.....?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2275#issuecomment-222807726,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAizDer8nOznaLv6wQ9-xB1WP9Z64N-7ks5qHJfwgaJpZM4Ip7oF
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by etennapel** [comment]
My charts are showing the correct dates again! Thanks for the quick fix.

[Maybe you could add some unit-tests to prevent this happening again ;-) ]

**Comment by dlaliberte** [comment]
The "fix" was only that the current date changed from the end of a month to
the beginning of the next month.  We will have to get the correct fix in
place before the end of this month.

On Wed, Jun 1, 2016 at 2:04 AM, etennapel notifications@github.com wrote:

> My charts are showing the correct dates again! Thanks for the quick fix.
> 
> [Maybe you could add some unit-tests to prevent this happening again ;-) ]
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2275#issuecomment-222900987,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAizDZu5ApRpvhtP1ZW_eJt0LjgPEpDlks5qHSDhgaJpZM4Ip7oF
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA
