### ISSUE TITLE
Line, Scatter, and Candlestick Charts are showed JAN-01 by default if we have single data value

### ISSUE THREAD

**Issue by vimalavinisha** [google/google-visualization-issues#2281]
Hi,
        I have checked Line, Scatter, and Candlestick  charts with below inputs. Here am using x axis as datetime datatype. y axis is number.

The issue is, If we have more than two inputs in the addRows column, it will draw perfect graph.
but have single input, it will draw graph with Jan-01 as default x-value. But my actual single date values is Apr-2016.

Here is  the link: 
https://jsfiddle.net/trj7m05y/13/

Here is the code:

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

 <div id="vis_div" style="width: 600px; height: 400px;"></div>

google.charts.load('current',{'packages':['corechart']});
 google.charts.setOnLoadCallback(drawVisualization);
function drawVisualization() {
       var data = new google.visualization.DataTable();
  data.addColumn('datetime', 'Date');
  data.addColumn('number', 'measurement');
  data.addRows([
                 [new Date(2016, 3, 22,10,10,10), 130 ]
                // [new Date(2016, 3, 21,15,10,20), 170],
                // [new Date(2016, 3, 20), 142],
                // [new Date(2016, 3, 19,8,34,7), 127],
                // [new Date(2016, 3, 18,15,34,7),158],
               //  [new Date(2016, 3, 16), 171]
         ]);
  var options = {
        width: 350,
        height: 300,
        legend : {
          position:'top',
          alignment:'end'
        },
        hAxis: {
        format: 'MMM-dd',
        gridlines: {color: 'none',count: 7},
        //gridlines: {count: 15}
        title:'Date',
        titleTextStyle:{
        // fontWeight:'bold',
          fontSize:16
        }
        },
        vAxis: {
          viewWindow:{
          gridlines: {color: 'none'},
          minValue: 200,
          maxValue:100,
          },
          title: 'Height (CM)',
          titleTextStyle:{
          // fontWeight:'bold',
            fontSize:16
          }
        },
        series: {
          1: {curveType: 'function'},
          0: {
          pointShape: 'circle',
          pointSize: 8,
          color:'#604DC0'
          }
        }
  };
  var chart = new google.visualization.LineChart(document.getElementById('vis_div'));
  chart.draw(data, options);
      }

 Please give solution for this.

Thanks,
Vimala.A

**Comment by dlaliberte** [comment]
The problem is that with only a single date value, there is no way for the chart to know what scale to assume, so it must guess.  You can help it, though, by adding a minValue or maxValue, or viewWindow min or max.

**Comment by dlaliberte** [comment]
Oh, also, you have a format that doesn't show the year, but if you change that to show the year, you would see it is different for each tick.

**Comment by vimalavinisha** [comment]
Hi ,
  Thanks for the quick response. 
             I have changed date format from 'MMM-dd' to 'MMM d, y'. Now it will show x axis as 
Jan 1, 2000 Jan 1, 2010  Jan 1, 2020  Jan 1, 2030...  

you can check it here
https://jsfiddle.net/trj7m05y/14/

Thanks

**Comment by dlaliberte** [comment]
Your hAxis min and max values need to be dates.  Like this:
https://jsfiddle.net/trj7m05y/16/

On Fri, Jun 3, 2016 at 2:33 AM, vimalavinisha notifications@github.com
wrote:

> Hi ,
> Thanks for the quick response.
> I have changed date format from 'MMM-dd' to 'MMM d, y'. Now it will show x
> axis as
> Jan 1, 2000 Jan 1, 2010 Jan 1, 2020 Jan 1, 2030...
> 
> you can check it here
> https://jsfiddle.net/trj7m05y/14/
> 
> Thanks
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2281#issuecomment-223501836,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAizDaXOy9e03ijYyZDBPirZ0j2aUTsYks5qH8rNgaJpZM4IsiXk
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA
