### ISSUE TITLE
wordtree docs out of date

### ISSUE THREAD

**Issue by valtron** [google/google-visualization-issues#2283]
The [wordtree](https://google-developers.appspot.com/chart/interactive/docs/gallery/wordtree) docs mention `sentenceRegex`/`wordRegex` but it looks like these have been renamed to `sentenceSeparator`/`wordSeparator`.

**Comment by hu4869** [comment]
Yes, and thanks for saving the day

**Comment by orwant** [comment]
Docs fixed. Thanks for pointing this out!
