### ISSUE TITLE
Timeline chart - Month not reflecting properly on graph

### ISSUE THREAD

**Issue by tejashree2012** [google/google-visualization-issues#2284]
I am using Timeline chart. Month is not displayed properly on timeline chart.
In code, I entered start date for chart as (2016,03,25,11,30,0) i.e. 25th **March**
However in timeline graph it is displaying 25th **April**

Please find snapshot of code and timeline:

![code snapshot](https://cloud.githubusercontent.com/assets/19752492/15801749/672f1170-2abc-11e6-8842-5b4ba475184b.png)
![graph snapshot](https://cloud.githubusercontent.com/assets/19752492/15801750/672f363c-2abc-11e6-9f67-d584aa87e14b.png)

**Comment by nbering** [comment]
Javascript months are zero-indexed. Same as #2248
