### ISSUE TITLE
Documentation with a 404 error

### ISSUE THREAD

**Issue by gregorydillon** [google/google-visualization-issues#2291]
The "Magic Tables" example on this [documentation page](https://developers.google.com/chart/interactive/docs/more_charts)  comes up with a 404 error.

**Comment by gregorydillon** [comment]
![screenshot 2016-06-10 at 16 55 00](https://cloud.githubusercontent.com/assets/5195087/15981616/955ea6a4-2f2c-11e6-88cf-d3a2e2d6c42c.png)

**Comment by orwant** [comment]
I scrubbed the obsolete charts. Thanks for pointing this out!
