### ISSUE TITLE
Chart Interval Styling

### ISSUE THREAD

**Issue by pargamanik** [google/google-visualization-issues#2297]
Individual interval styling no longer works.  In past releases the interval could be a different color than other series and other intervals (for example, try to put a blue bar interval on top of a green column in a column chart).  But now the interval inherits the color of another series/interval.  I'll use the Box Plot example posted on the website https://developers.google.com/chart/interactive/docs/gallery/intervals#combining-interval-styles. When I change the firstQuartile and thirdQuartile colors to be green and red, respectively, in the options, both intervals are rendered green.  Here is the code to replicate the issue:  

google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawBoxPlot);
function drawBoxPlot() {

```
    var array = [
      ['a', 100, 90, 110, 85, 96, 104, 120],
      ['b', 120, 95, 130, 90, 113, 124, 140],
      ['c', 130, 105, 140, 100, 117, 133, 139],
      ['d', 90, 85, 95, 85, 88, 92, 95],
      ['e', 70, 74, 63, 67, 69, 70, 72],
      ['f', 30, 39, 22, 21, 28, 34, 40],
      ['g', 80, 77, 83, 70, 77, 85, 90],
      ['h', 100, 90, 110, 85, 95, 102, 110]
    ];

    var data = new google.visualization.DataTable();
    data.addColumn('string', 'x');
    data.addColumn('number', 'series0');
    data.addColumn('number', 'series1');
    data.addColumn('number', 'series2');
    data.addColumn('number', 'series3');
    data.addColumn('number', 'series4');
    data.addColumn('number', 'series5');
    data.addColumn('number', 'series6');

    data.addColumn({ id: 'max', type: 'number', role: 'interval' });
    data.addColumn({ id: 'min', type: 'number', role: 'interval' });
    data.addColumn({ id: 'firstQuartile', type: 'number', role: 'interval' });
    data.addColumn({ id: 'median', type: 'number', role: 'interval' });
    data.addColumn({ id: 'thirdQuartile', type: 'number', role: 'interval' });

    data.addRows(getBoxPlotValues(array));

    /**
     * Takes an array of input data and returns an
     * array of the input data with the box plot
     * interval data appended to each row.
     */
    function getBoxPlotValues(array) {

        for (var i = 0; i < array.length; i++) {

            var arr = array[i].slice(1).sort(function (a, b) {
                return a - b;
            });

            var max = arr[arr.length - 1];
            var min = arr[0];
            var median = getMedian(arr);

            // First Quartile is the median from lowest to overall median.
            var firstQuartile = getMedian(arr.slice(0, 4));

            // Third Quartile is the median from the overall median to the highest.
            var thirdQuartile = getMedian(arr.slice(3));

            array[i][8] = max;
            array[i][9] = min
            array[i][10] = firstQuartile;
            array[i][11] = median;
            array[i][12] = thirdQuartile;
        }
        return array;
    }

    /*
     * Takes an array and returns
     * the median value.
     */
    function getMedian(array) {
        var length = array.length;

        /* If the array is an even length the
         * median is the average of the two
         * middle-most values. Otherwise the
         * median is the middle-most value.
         */
        if (length % 2 === 0) {
            var midUpper = length / 2;
            var midLower = midUpper - 1;

            return (array[midUpper] + array[midLower]) / 2;
        } else {
            return array[Math.floor(length / 2)];
        }
    }

//series: [{ 'color': '#D3362D' }],
    var options = {
        title: 'Box Plot',
        height: 500,
        legend: { position: 'none' },
        hAxis: {
            gridlines: { color: '#fff' }
        },
        lineWidth: 0,
        intervals: {
            barWidth: 1,
            boxWidth: 1,
            lineWidth: 2,
            style: 'boxes'
        },
        interval: {
            max: {
                style: 'bars',
                fillOpacity: 1,
                color: 'blue'
            },
            min: {
                style: 'bars',
                fillOpacity: 1,
                color: 'blue'
            },
            firstQuartile: {
                style: 'boxes',
                fillOpacity: 0.7,
                color: 'green'
            },
            thirdQuartile: {
                style: 'boxes',
                fillOpacity: 0.7,
                color: 'red'
            }
        }
    };

    var chart = new google.visualization.LineChart(document.getElementById('box_plot'));

    chart.draw(data, options);
}
```

**Comment by dlaliberte** [comment]
I don't know that interval coloring ever worked the way you believe it did.  And you might be misinterpreting the way it works now.

Box intervals always come in pairs, so only one color applies to a pair of box interval values.  They are not relative to the data value that they are associated with, but absolute values.   Both box interval values might be above or below the data value, so the data value is then not between the ends of the box.  

Bar intervals are separate, however, so they can have different colors, although the stem between the bars is colored by the first bar interval color, I believe.

It might be useful to have a type of interval that behaves more like a bar chart, in which each interval value would be relative to a base value which in this case would be the associated data value.  Then each such interval could have its own color.  Maybe this is what you thought the 'box' interval does.

**Comment by pargamanik** [comment]
Thank you for your quick reply.
I've provided another example on jsfiddle here: https://jsfiddle.net/83artm2g/1/
I was expecting the intervals to be blue, but they are the same color as the corresponding columns.  Is there a way to make the interval blue now?  This worked several months ago.

**Comment by dlaliberte** [comment]
Apparently v42 works as you would expect for your example, so you could change 'current' to '42' to get that behavior.

This happens because the explicit style role for the series overrides the color for the interval, although that is arguably incorrect since the interval can have a color which might be considered as more specific, and thus override the default. It is a bit ambiguous, however, and we actually do have a way to specify it either way.  If you wrap your style for the bar with "bar { ... }" then the bar style will be specific to the bar and not apply to everything about the series including the intervals.  Like so:  https://jsfiddle.net/dlaliberte/83artm2g/2/

This is an incompatible break from the past, but yours is the first report of a problem that I am aware of.

**Comment by pargamanik** [comment]
Thanks again for getting back to me so quickly.  That makes sense and fixed my issue.

**Comment by dlaliberte** [comment]
It's still not clear whether this should be considered a bug because it seems that the interval style specified in options should override the series style specified in data.   We think of things in the data as more specific, but there are ambiguous cases at best.
