### ISSUE TITLE
Link broken in the FAQ page

### ISSUE THREAD

**Issue by iamyorchdev** [google/google-visualization-issues#2304]
The **Visualization API Python sample page** link is broken

![image](https://cloud.githubusercontent.com/assets/1671260/16501525/62d23004-3ecf-11e6-8e2e-446a16c08df2.png)

**Comment by orwant** [comment]
Thanks for pointing this out! I removed the entry.

**Comment by iamyorchdev** [comment]
Awesome! :+1:
