### ISSUE TITLE
Need to change or eliminate line at X axis 

### ISSUE THREAD

**Issue by mpemburn** [google/google-visualization-issues#2311]
Hi,

I'm generating several line charts on a page, and on some, there is a horizontal line below the chart lines and above the X axis values (in this case, years).   I've included two examples below.  I've been unable to identify which option is responsible for this line.  It needs to be either gone, or to appear consistently on all charts.  Can you help me figure this out?

Thanks!

Mark Pemburn
ColorJar, LLC

![image](https://cloud.githubusercontent.com/assets/461989/16772603/e0852644-4822-11e6-895c-d1572db81a19.png)

![image](https://cloud.githubusercontent.com/assets/461989/16772697/3dcdc20c-4823-11e6-8b5a-00d88c2a17c0.png)

**Comment by dlaliberte** [comment]
Sounds like the line is at the baseline value that is shown if it is close
enough to your data.   You can change the baseline color to 'none'.

On Tue, Jul 12, 2016 at 11:25 AM, Mark Pemburn notifications@github.com
wrote:

> Hi,
> 
> I'm generating several line charts on a page, and on some, there is a
> horizontal line below the chart lines and above the Y axis values (in this
> case, years). I've included two examples below. I've been unable to
> identify which option is responsible for this line. It needs to be either
> gone, or to appear consistently on all charts. Can you help me figure this
> out?
> 
> Thanks!
> 
> Mark Pemburn
> ColorJar, LLC
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/461989/16772603/e0852644-4822-11e6-895c-d1572db81a19.png
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/461989/16772697/3dcdc20c-4823-11e6-8b5a-00d88c2a17c0.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2311, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAizDZJDUgpzxAOS5kywjkP_DemDFtTDks5qU7HUgaJpZM4JKhDQ
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by mpemburn** [comment]
Thanks!  This would be hAxis.baselineColor, if I read right.  It seems that this option is only applicable to the major axis, and only if that axis is of the "continuous" and not the "discrete" type.  Next, to figure out how to make my axes continuous, because they are evidently not.

**Comment by dlaliberte** [comment]
Actually, the horizontal gridline is associated with the vertical axis, since it is positioned at the baseline value for your series values, not the domain values.  So you should change the vAxis.baselineColor.
