### ISSUE TITLE
 google.visualization Charts showing blank page

### ISSUE THREAD

**Issue by denkyira5544** [google/google-visualization-issues#2337]
I am using JSON with google charts to draw pie chart. I can step through my code and see the data but when the page loads it loads empty chart, only shows the data-option titles without the pie chart. I am getting error "Not Array" on this " var data = google.visualization.arrayToDataTable(jsonArray);"
 Below is my code. Can some one help me find out what I am missing?
@{

 ViewBag.Title = "Metrics Page";
}

<div class="row">
<div class="col-md-12">
    <div class="chart"
         data-url="/Metrics/ApprovedCDRLS"
         data-chart-type="Pie"
         data-options='{ "title": "Approved CDRLS", "is3D" : "true" }'>
    </div>
</div>

```
<div class="col-md-6">
    <div class="chart"
         data-url="/Metrics/AverageNumResubmissions"
         data-chart-type="Pie"
         data-options='{ "title": "Average Resubmissions", "is3D": "true" }'>
    </div>
</div>
```

</div>

 <script type="text/javascript"
        src="https://www.google.com/jsapi?autoload={
        'modules':[{
          'name':'visualization',
          'version':'1',
          'packages':['corechart']
        }]
      }"></script>

<script type="text/javascript">
    $().ready(function () {
        google.setOnLoadCallback(drawCharts);
    });

```
function drawCharts() {
    var chart = $('div.chart');
    $.each(chart, drawChart);
}

function drawChart() {
    var $this = $(this);
    var url = $this.data('url');
    var chartType = $this.data('chart-type');
    var options = $this.data('options');
    var chartArea = $this[0];

    $.get(url)
     .done(function (jsonArray) {
         var chart;
         var data = google.visualization.arrayToDataTable(jsonArray);
         var defaultOptions = {
             title: 'Chart',
             chartArea: { left: '100' },
             height: '400'
         };
```

**Comment by nbering** [comment]
arrayToDataTable expects a 2-dimensional array - an array of arrays - with the inner arrays being the "rows" of the DataTable (each row consisting of one cell for each column/series. I don't see anything in the code you've provided to confirm that the data is indeed in that format. Are you using some sort of wrapper library? It may or may not be a downstream issue if the wrapper library is attempting to explicitly convert a dataset that doesn't need conversion.

**Comment by denkyira5544** [comment]
Hi Nick
Thanks a lot for responding to my post.
I am converting the List to a datatable and below is my code.
``
private static List<object> GetData(string command)
        {

```
        var connStr = ConfigurationManager.ConnectionStrings["ReportsConnection"].ConnectionString;
        var ds = new DataSet();

        using (var conn = new AdomdConnection(connStr))
        {

            conn.Open();
            using (var cmd = new AdomdCommand(command, conn))
            {
                var adapter = new AdomdDataAdapter(cmd);
                adapter.Fill(ds);
            }
            conn.Close();
        }

        return ConvertDataTable(ds.Tables[0]);
    }

    private static List<object> ConvertDataTable(DataTable dt)
    {
        var data = new List<object>();
        var columnCount = dt.Columns.Count;

        var columnObject = new string[columnCount];
        for (var i = 0; i < columnCount; i++)
        {
            var name = dt.Columns[i].ColumnName.Replace(".[MEMBER_CAPTION]", "");
            var nameParts = name.Split(new[] { '.' });

            columnObject[i] = nameParts[nameParts.Count() - 1].Replace("[", "").Replace("]", "");
        }
        data.Add(columnObject);

        foreach (DataRow row in dt.Rows)
        {
            data.Add(row.ItemArray);
        }

        return data;
    }
```

**Comment by denkyira5544** [comment]
Hi Nick
My issue is  fixed. The code is correct. It was not showing because of plotting the wrong graphs. Thanks for your response anyway
