### ISSUE TITLE
Vertical Axis not responding to "options"

### ISSUE THREAD

**Issue by perryjgorelik** [google/google-visualization-issues#2340]
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

   <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Age', 'Place1', 'Place2', 'Place3', 'Place4'],
          ['18-21 Years', 6.8, 22.5, 15.2, 26.1],
          ['22-25 Years', 19.6, 9.9, 22.5, 8.7],
          ['26-30 Years', 20.7, 15.9, 15.6, 17.4],
          ['31-35 Years', 15.6, 11.8, 11.1, 13.0],
          ['36-40 Years', 12.1, 11.4, 9.7, 6.5],
          ['41+ Years', 25.1, 28.5, 24.2, 28.3],
          ['Missing', 0.1, 0.0, 1.7, 0.0]
        ]);

```
    var options = {
      chart: {
        title: 'Demographics',
      },
      height: 500,
      colors: ['#004F9B', '#BD233A', '#EAC506', '#01573E'],
```

vAxis: {format: 'percent', title: 'Percent'} //THIS LINE WON'T WORK

```
    };

    var formatter = new google.visualization.NumberFormat({
          fractionDigits: 1,
          suffix: '%'
        });
    formatter.format(data, 1);
    formatter.format(data, 2);
    formatter.format(data, 3);
    formatter.format(data, 4);

    var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

    chart.draw(data, options);
  }
</script>
```

**Comment by dlaliberte** [comment]
Perhaps you are using a chart editor in a spreadsheet, or in AppsScript?

**Comment by perryjgorelik** [comment]
Thank you for your response. I'm not sure I understand what you're referring to. I am writing the code in Dreamweaver. I may have discovered the problem in the last line, however: 
var chart = new google.**charts**.Bar(document.getElementById('columnchart_material'));

I changed it to **visualization** when I made other changes, and that may have fixed the issue.

**Comment by nbering** [comment]
@perryjgorelik Material chart axis options have changed from the classic bar chart. That's probably the issue.
