### ISSUE TITLE
setAction "Object doesn't support" on timeline

### ISSUE THREAD

**Issue by Scheevel** [google/google-visualization-issues#2349]
screenshot debugging this issue.  
The "chart" object is instantiated  "setAction" is not available on the object
![image](https://cloud.githubusercontent.com/assets/178806/18139487/5b73f148-6f77-11e6-9079-d42cdc961348.png)

**Comment by dlaliberte** [comment]
Can you provide enough context to reproduce this?  Or can you point us at your web page?

**Comment by Scheevel** [comment]
Code file below is displayed in Content Editor Webpart on an .aspx page in SharePoint (intranet, so I don't have any way of providing access).
Everything else about timeline works perfectly, including custom-html-tooltips.
The "chart" functions are wrapped in an object to avoid the global name space.
Thanks!
Full code below.

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

```
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">

google.charts.load('current', {'packages':['timeline']});

jsoChart = {
    oCtx:null,
    oList:null,
    oItems:null,
    listTitle:'ImmaCalendar',
    oCalendarItems:[],

    DrawChart: function() {
        var container = document.getElementById('timeline');
        var chart = new google.visualization.Timeline( container );
        var dataTable = new google.visualization.DataTable();

        dataTable.addColumn({ type: 'string', id: 'Room' });
        dataTable.addColumn({ type: 'string', id: 'Name' });
        dataTable.addColumn({ type: 'string', role: 'tooltip' , 'p': {'html': true} });
        dataTable.addColumn({ type: 'date', id: 'Start' });
        dataTable.addColumn({ type: 'date', id: 'End' });
        dataTable.addRows( jsoChart.oCalendarItems );
/*
        dataTable.addRows([
          [ 'Tax', 'Deadline', new Date(2016,8,21,0),  new Date(2016,8,21,12) ],
          [ 'Tax', 'Outing', new Date(2016,8,22,8),  new Date(2016,8,22,14) ],
          [ 'Tax', 'Event',  new Date(2016,8,23,17),  new Date(2016,8,23,19) ],
          [ 'Audit', 'Due Date', new Date(2016,8,22,0),  new Date(2016,8,22,24) ],
          [ 'Audit', 'Team Meeting', new Date(2016,8,24,0),  new Date(2016,8,24,24) ],
          [ 'Audit', 'Something Else', new Date(2016,8,26,0),  new Date(2016,8,26,24) ],
          [ 'Training', 'Training', new Date(2016,8,21,0),  new Date(2016,8,21,24) ],
          [ 'Training', 'Teaching', new Date(2016,8,23,0),  new Date(2016,8,23,24) ],
          [ 'Training', 'Learning', new Date(2016,8,25,0),  new Date(2016,8,25,24) ],
          ]);
*/
        var options = {
          timeline: { colorByRowLabel: true },
          tooltip: { isHtml: true },
          tooltip: { trigger: 'selection' },
        };


        chart.setAction({
            id:'sample',
            text:'whatever',
            action: function() {
                alert('test');
            }
        });

        chart.draw( dataTable, options );
    },

    GetCalendarItems: function() {
        this.oCtx = new SP.ClientContext(); 
        this.oList = this.oCtx.get_web().get_lists().getByTitle( this.listTitle );
        var camlQuery = new SP.CamlQuery();
        camlQuery.set_viewXml(
            '<View><Query></Query></View>'
        );
        this.oItems = this.oList.getItems( camlQuery );
        this.oCtx.load( this.oItems );
        this.oCtx.executeQueryAsync(Function.createDelegate( this, this.OnGetSuccess ), Function.createDelegate( this, this.OnFail ));   
    },

    OnGetSuccess: function() {
        //alert('Request succeeded. \n\nRetrieved Item is: ' + this.oItem.get_item('Title'));

        var itemEnumerator = this.oItems.getEnumerator();

        while ( itemEnumerator.moveNext() ){
            var oItem = itemEnumerator.get_current();
            //console.log( oItem.get_id() + ":" + oItem.get_item( 'TestDate' ) );
            jsoChart.oCalendarItems.push( [ oItem.get_item( 'Location' )
                , oItem.get_item( 'Title' )
                , '<a href="http://google.com" >test</a>'
                , oItem.get_item( 'EventDate' )
                , oItem.get_item( 'EndDate' ) ] );          
        }

        google.charts.setOnLoadCallback( jsoChart.DrawChart );

    },  
    OnFail: function( sender, args ) {
        SP.UI.Notify.addNotification( 'Request failed. \nError: ' + args.get_message() + '\nStackTrace: ' + args.get_stackTrace(), true );
    },
}

// Make sure that sp.js & SP.ClientContext are available
SP.SOD.executeFunc( 'sp.js', 'SP.ClientContext', function() {
        jsoChart.GetCalendarItems();
    } 
);

</script>
</head>
<body>
<div id="timeline" style="height: 180px;"></div>
</body>
</html>

```

**Comment by dlaliberte** [comment]
The Timeline chart is not documented to support setAction.  Would be a nice feature to add.

**Comment by Scheevel** [comment]
Ugh.  It's implicit according: https://developers.google.com/chart/interactive/docs/customizing_tooltip_content#supported-charts

![image](https://cloud.githubusercontent.com/assets/178806/18144371/eb189902-6f8b-11e6-8b6b-f2daa8f8bbfb.png)
![image](https://cloud.githubusercontent.com/assets/178806/18144391/0f21448e-6f8c-11e6-87f6-33f8b6b53142.png)

**Comment by dlaliberte** [comment]
Well, the html tooltips are supported on those chart types, but the setActions method doesn't apply to Timeline, unfortunately.   On the reference page, it says this more specifically: 

setAction()

This is optionally exposed by visualizations that have tooltips and allow tooltip actions. It works only for core charts (bar, column, line, area, scatter, combo, bubble, pie, donut, candlestick, histogram, stepped area).

**Comment by Scheevel** [comment]
Thank you so much for looking into this for me.  I appreciate your responsiveness.

**Comment by sohamray1990** [comment]
@Scheevel Hi, For someone, who needs to provide some actionable items in timeline chart tooltip, what ways can he achieve that?

**Comment by Scheevel** [comment]
Hi @sohamray1990, I don't recall how much capability is in the "HTML Tool Tips." I assume you could use HTML <button> or <a> elements in the TT's markup.  I don't recall how long the TT persists after hover or if the TT can retain focus, you may need to add some code to alter the TT's behavior

**Comment by thornomad** [comment]
I also came here because I couldn't figure out why `setAction` on my Timeline was not working!  Perhaps the documentation could be updated -- I certainly was expecting it to work like the other charts (and it would be great if it could).
