### ISSUE TITLE
[CRITICAL] DataTable crashing Chrome (CPU >50%, unlimited steady climbing RAM)

### ISSUE THREAD

**Issue by JamesCullum** [google/google-visualization-issues#2361]
Demonstration: http://stackoverflow.com/questions/39572694/browser-crashes-for-specific-data-in-google-chart
Tested in Chrome 52

Expected effect: Clicking on "year" will show the data for the year. The console debugging shows the correct data.

What happens: UI blocks, CPU jumps to 50+% and the RAM climbs quickly (around 2k/s) until the computer crashes or the tab is force-closed.

**Comment by JamesCullum** [comment]
Found the issue: If the label (f) is a number, it will crash the browser.

**Comment by dlaliberte** [comment]
Thanks for figuring it out and reporting.  We'll try to fix this asap.

**Comment by jplarrea** [comment]
same problem, change the label (f) from number to string.

**Comment by JamesCullum** [comment]
It should be a number, but should use parseInt before.

**Comment by JamesCullum** [comment]
> Thanks for your followup. The problem is an infinite loop when a number is provided instead of a string. This problem will be avoided in the next release
- SE, dlaliberte
