### ISSUE TITLE
Request to support "https://www.googleapis.com/auth/spreadsheets" as an authorized scope for "/gviz/tq"

### ISSUE THREAD

**Issue by Spencer-Easton** [google/google-visualization-issues#2365]
Google Apps Script adds the scope of "https://www.googleapis.com/auth/spreadsheets" to access spreadsheets in drive.  There is no simple way to add "https://spreadsheets.google.com/feeds" to the Apps Script project.

**Comment by dlaliberte** [comment]
You should probably post to an Apps Script forum.  See https://developers.google.com/apps-script/support
