### ISSUE TITLE
Height attribute required

### ISSUE THREAD

**Issue by 1Jesper1** [google/google-visualization-issues#2370]
Now I have to define the "height" attribute in the options for a chart. Otherwise I get the error messages:
"jsapi_compiled_ui_module.js:82 Error: <rect> attribute y: Expected length, "NaN".
"jsapi_compiled_ui_module.js:82 Error: <rect> attribute height: Expected length, "NaN".

Is it required now? I thought a default value was provided when the height attribute is not set.

**Comment by dlaliberte** [comment]
The height attribute on the container element should not be required, and we have many examples of charts working as expected without a height attribute.  Could you give us more details about the problem you are seeing?  Best would be to point to an example.
