### ISSUE TITLE
Unexpected end tag warning on MS Edge + Win10

### ISSUE THREAD

**Issue by vmakovsky** [google/google-visualization-issues#2400]
In MS Edge browser (+Win 10) when loading google chart apis:

```
<html>
<head>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1.0', {'packages':['corechart']});
  </script>
</head>
<body></body>
</html>
```

a warning occurs 'Unexpected end tag'. This seems that google library
doesn't enclose some html tag(s) properly when manipulating with DOM.
According to some users on stackoverflow this happens on IE11  too.

**Comment by dlaliberte** [comment]
Thanks for your report.   Since we are no longer (unless necessary) updating the version of Google Charts that you load with jsapi, I am curious what happens if you use the new loader:

```
<html>
<head>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
  </script>
</head>
<body></body>
</html>
```

**Comment by vmakovsky** [comment]
This version works without warnings. Thanks.

**Comment by dlaliberte** [comment]
Good to know. Thanks.
