### ISSUE TITLE
typo found

### ISSUE THREAD

**Issue by adrien-vieilleribiere** [google/google-visualization-issues#2402]
in https://developers.google.com/chart/interactive/docs/gallery/piechart#configuration-options
for the Name pieResidueSliceColor
Defualt: '#ccc'
should be
Default: '#ccc'
![typo_googlepiecharts](https://cloud.githubusercontent.com/assets/18309999/20524090/e0b8afec-b0b8-11e6-9f51-cdb7b0026b87.JPG)

**Comment by orwant** [comment]
Fixed; thanks!
