### ISSUE TITLE
Google Bar Chart Error- new google.charts.Bar() is not a Constructor in Dual X Chart

### ISSUE THREAD

**Issue by vkvikrant001** [google/google-visualization-issues#2409]

**Comment by dlaliberte** [comment]
Although I can't see your code here now (did you delete it), it is working fine for me in this example: https://jsfiddle.net/dlaliberte/0yf08o7f/

**Comment by THEMBOCHARLES** [comment]
I am also getting TypeError: google.charts.Bar is not a constructor from the Code bellow. How Do I resolve it.

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

 <div id="btn-group">
      <button class="button button-blue" id="none">No Format</button>
      <button class="button button-blue" id="scientific">Scientific Notation</button>
      <button class="button button-blue" id="decimal">Decimal</button>
      <script type="text/javascript">
        google.charts.load('current', {'packages':['bar']});
        google.charts.setOnLoadCallback(drawChart);
          function drawChart() {
            var data = google.visualization.arrayToDataTable([
              ['Year', 'Sales', 'Expenses', 'Profit'],
              ['2014', 1000, 400, 200],
              ['2015', 1170, 460, 250],
              ['2016', 660, 1120, 300],
              ['2017', 1030, 540, 350]
            ]);

            var options = {
              chart: {
                title: 'Company Performance',
                subtitle: 'Sales, Expenses, and Profit: 2014-2017',
              },
              bars: 'horizontal', // Required for Material Bar Charts.
              hAxis: {format: 'decimal'},
              height: 400,
              colors: ['#1b9e77', '#d95f02', '#7570b3']
            };

            var chart = new google.charts.Bar(document.getElementById('barchart_material'));

            chart.draw(data, google.charts.Bar.convertOptions(options));

            var btns = document.getElementById('btn-group');

            btns.onclick = function (e) {

              if (e.target.tagName === 'BUTTON') {
                options.hAxis.format = e.target.id === 'none' ? '' : e.target.id;
                chart.draw(data, google.charts.Bar.convertOptions(options));
              }
            }
          }
     </script>


<div id="barchart_material" style="width: 900px; height: 500px;"></div>

**Comment by dlaliberte** [comment]
Thembocharles, your code seems to work fine, with the addition of a container element:  https://jsfiddle.net/dlaliberte/d9t4934b/

**Comment by danmv** [comment]
I keep getting the same error as @THEMBOCHARLES. Did you figure out how to solve the issue? 

I do have multiple charts in my page that are non-material charts.

**Comment by dlaliberte** [comment]
@danmv, Did you see my jsfiddles?  

If you have multiple charts in the same page, you may have some problems depending on how you load and run the Google Charts code.  It would help to see your code.   Or you may find enough hints here: https://developers.google.com/chart/interactive/docs/basic_multiple_charts
