### ISSUE TITLE
Google Visualization DateTiem auto add 1 month

### ISSUE THREAD

**Issue by phoanghuong86** [google/google-visualization-issues#2414]
Link reference from Google https://developers.google.com/chart/interactive/docs/datesandtimes
and sample demo https://jsfiddle.net/b2yuoh0n/ , we can see that the format Date(2000, 8, 5) will be parsed to 5.Sep.2000 (add 1 month)
At this time, my report have to sub one month and waiting fixing from Google
Thank a lot
Huong

**Comment by dlaliberte** [comment]
The month index is 0-based.  This is a frequent confusion/misunderstanding, which started many years ago.  http://stackoverflow.com/questions/1507619/javascript-date-utc-function-is-off-by-a-month

**Comment by phoanghuong86** [comment]
Thank a lot @dlaliberte , my reports were worked well and last week they got index 0-based so I think many guys have same issue with new update.
Thank again,
Huong
