### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by phe-sto** [google/google-visualization-issues#2441]
Hi,

As you can see in the capture above the date sent is data.addRows([[new Date(2016, 09, 15), 14976789]]);
when the date on the chart indicate Oct as October when 09 is September.

![image](https://cloud.githubusercontent.com/assets/22092963/22099280/01a6e24c-de2b-11e6-9f37-969c601e97e1.png)

Regards

**Comment by dlaliberte** [comment]
When you use the Date constructor with numbers, the months start at 0.  http://stackoverflow.com/questions/2552483/why-does-the-month-argument-range-from-0-to-11-in-javascripts-date-constructor
