### ISSUE TITLE
 Problem with an empty column in query (not a bug but a feature? ☺)

### ISSUE THREAD

**Issue by olyakolya** [google/google-visualization-issues#2485]
I try to use next query in a spreadsheet: **"QUERY("ABC";"SELECT  '' , Col1, Col2 etc")**
It allows me to insert an empty column in output. It worked yesterday, but now there is an error.
Were there any changes that could affect this?
http://prntscr.com/exsf34 - example

**Comment by olyakolya** [comment]
the problem appeared again

**Comment by dlaliberte** [comment]
This is a forum for posting issues about Google Charts.  We can't help here with spreadsheet query issues (except maybe when requests are made via Google Charts).  I would suggest going to Google Docs help forums: https://productforums.google.com/forum/#!forum/docs

**Comment by olyakolya** [comment]
Thank You! Sorry
