### ISSUE TITLE
Bars aren't drawn correctly - Column Chart

### ISSUE THREAD

**Issue by coyarzun2013** [google/google-visualization-issues#2499]
i´m using column charts with 2 bars to compare percentajes (like "Dual-Y charts"), but in some cases, the bar with minor value is higer than the bar with mayor value.
in fact, on the example "Dual-Y charts" from the oficial page https://developers.google.com/chart/interactive/docs/gallery/columnchart

the fourth comparission bars get the problem, blue bar has a value of 3000 and red 14, but red bar is higer than blue, why?.

i´gave u a example image with annotations with column values.

PD: Sorry mi bad english :(
![2017-05-24_163036](https://cloud.githubusercontent.com/assets/4574326/26424229/7bb4faf8-409e-11e7-9aeb-4dd8aa3f492e.jpg)

**Comment by dlaliberte** [comment]
Your chart is using dual-Y axes, and each axis uses its own scale.  Your blue values correspond to the left axis and the red values correspond to the right axis.  

If you want them to use the same scale, then you probably should just have them use the same axis.  If not, I am not sure what you are asking for.

**Comment by coyarzun2013** [comment]
@dlaliberte thanks for the fast reply...
the question now is, how can i use the same scale for left and right axis?

here´s my code
`google.charts.load('current', {'packages':['corechart', 'bar']});
      google.charts.setOnLoadCallback(drawStuff);

      function drawStuff() {

        var button = document.getElementById('change-chart');
        var chartDiv = document.getElementById('chart_div');
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'AsigCurso');
        data.addColumn('number', 'Aprobados');
        data.addColumn({type: 'number', role: 'annotation'});
        data.addColumn('number', 'Reprobados');
        data.addColumn({type: 'number', role: 'annotation'});
        data.addRows(<?php echo json_encode($chartData); ?>);

        var classicOptions = {
          width: 1000,
          series: {
            0: {targetAxisIndex: 0},
            1: {targetAxisIndex: 1}
          },
          title: '<?php echo $row_cs_listado['nombre']; ?>',
          annotations: {
            alwaysOutside: true
          },
          hAxis : { 
		      textStyle : {
		          fontSize: 9 // or the number you want
		      }

		  }
        };
        function drawClassicChart() {
          var classicChart = new google.visualization.ColumnChart(chartDiv);
          classicChart.draw(data, classicOptions);
        }

        drawClassicChart();
    };`

**Comment by coyarzun2013** [comment]
@dlaliberte Forgot it

i change ...
`series: {
        0: {targetAxisIndex: 0},
        1: {targetAxisIndex: 1}
      },`
by 
`series: {
        0: {targetAxisIndex: 0},
        1: {targetAxisIndex: 0}
      },`
And now works perfect, thanks a lot.
