### ISSUE TITLE
Bracket missing in Diff charts example

### ISSUE THREAD

**Issue by thevarunfactor** [google/google-visualization-issues#2518]
In this URL: https://developers.google.com/chart/interactive/docs/gallery/diffchart, in the options examples, one of the brackets is missing.
Example:
var options = { diff: innerCircle: { radiusFactor: 0.3 } } };

SHOULD ACTUALLY BE:

var options = { diff: { innerCircle: { radiusFactor: 0.3 } } };

**Comment by orwant** [comment]
Fixed. Thanks for pointing this out!
