### ISSUE TITLE
jsapi_compiled_ui_module.js of version 45.2 is loading very slow (taking 15 sec - 20 sec for loading)

### ISSUE THREAD

**Issue by vganjare** [google/google-visualization-issues#2520]
Hi Team,

We are using google chart in our dashboard. Following code is used to load the google charts:
`google.charts.load('current', { 'packages': ['corechart', 'charteditor'] });`

loader.js is loading version 45.2 instead of 45. Also, in loader.js, we can see that 
{current:"45.2",upcoming:"45.2"}

Because of this, jsapi_compiled_ui_module.js was loaded from https://www.gstatic.com/charts/45.2/js/jsapi_compiled_ui_module.js, and was taking more than 15sec to load.

Can you please confirm if this is expected? 

Thanks,
Vishal

**Comment by dlaliberte** [comment]
Why do you say 'current' is supposed to be loading '45'?  Whatever is 'current' will change over time, as new releases are pushed out.  It just so happens that I pushed out '45.2' last week, so this is the correct version to be loading.  All the files loaded in a single document should be from the same version, however.

**Comment by vganjare** [comment]
Yes. Current version will change over time as new releases are pushed out. Since last one week, we have observed that the google charts were loading very slow. This was happening because of https://www.gstatic.com/charts/45.2/js/jsapi_compiled_ui_module.js file, and this file used to take 15sec - 20sec to load. We observed this slow loading specifically between 9AM IST - 1:30PM IST (on 11th July 2017).
This was the actual reason for raising this issue.

Currently, jsapi_compiled_ui_module.js (version 45.2) file is getting loaded under 500ms and we are not observing any delay in google charts loading time.

Thanks,
Vishal

**Comment by dlaliberte** [comment]
OK thanks.  I don't know why that one file would load so slowly.  If it was the first time that file was loaded for you, it might have been a temporary network problem.  The files are cachable, but only for a short time initially, and later I lengthen the cache lifetime.

**Comment by omguddu100** [comment]
Getting same Error when loading 2nd time ....this implemented in single page application ...
first time working good..... but 2nd try to load  getting this type of error....

![capturet](https://user-images.githubusercontent.com/16487240/48756293-96a2e780-ecbe-11e8-9cbb-458b2ce30fb4.PNG)

**Comment by dlaliberte** [comment]
@omguddu100, can you try the 'upcoming' release?  In any event, can you post enough to reproduce the problem you are seeing?  Best would be to create a jsfiddle so we can see it.
