### ISSUE TITLE
Table pagination on Firefox bug

### ISSUE THREAD

**Issue by unmaskz** [google/google-visualization-issues#2521]
There seems to be a possible bug on Firefox involving table pagination. I have set up a test fiddle to check.

[https://jsfiddle.net/zof8y6rt/8/](https://jsfiddle.net/zof8y6rt/8/)

If you have a table and enable pagination on it then the pages won't work on firefox and is ignored. This will then show every row instead of only X per page. Chrome and IE are fine so this seems to only be on Firefox.

**Comment by dlaliberte** [comment]
Thanks for your report.  It appears your dashboard-table style is modifying the style of the Table chart rendering in a way that is browser dependent, and interferes with assumptions made by the Table chart.  Removing the ".dashboard-table div" selector, in particular, seems to be enough to make it work again.

**Comment by unmaskz** [comment]
Thanks @dlaliberte you were correct that fixed the issue. Much appreciated!
