### ISSUE TITLE
support for static sizeAxis values in bubble charts instead of dynamic sizing

### ISSUE THREAD

**Issue by mpascualBluecore** [google/google-visualization-issues#2529]
When creating bubble charts, the size of the bubbles are dynamically set so that the radius of a bubble is relative to the other data points. So in one chart, a data point might have a size value of 100 and that maps to a bubble with a radius of 100px, and there might be another data point with a size value of 1 which is 1/100 the size of the bigger bubble.

The problem happens when you want to compare bubbles from different charts. If there's a second chart that has data points with size values 200 and 2, the 200 size bubble will be drawn the same size as the 100 value bubble in the other chart.

Would it be possible to support static sizing as an option, where the size value of the data point is the actual pixel size that you want drawn?

This same problem was encountered by an Excel user here: https://peltiertech.com/Excel/Charts/ControlBubbleSizes.html

The work-around described for Excel is to add a dummy point for the sole purpose of adjusting the scaling of the bubble sizes, and then deleting that dummy point from the chart. If there was a way to create a hidden dummy data point in the Google chart, that would also be a reasonable work-around here.

**Comment by dlaliberte** [comment]
The best way to do what you want currently is to use the point size styling that is available with a ScatterChart.  See the example in this documentation: https://developers.google.com/chart/interactive/docs/points#customizing-individual-points

You would basically be reimplementing a specialized Bubble chart.

**Comment by mpascualBluecore** [comment]
@dlaliberte , thank you very much. Using the ScatterChart with different point sizes worked.
