### ISSUE TITLE
Is there any customization option for "No data" label on pie chart

### ISSUE THREAD

**Issue by nealshan** [google/google-visualization-issues#2533]
Hi Guys,  
Is there any customization option for "No data" label on pie chart, I need to replace it with Germany translation.

![pie chart](https://user-images.githubusercontent.com/9512651/28952347-6fcd7ffc-7885-11e7-93ac-0c5917395725.png)

**Comment by emreonder** [comment]
Hi, i have same issue and i solved it by replaced chart div  with another div. Maybe its temporary solution but work fine

**Comment by nealshan** [comment]
@emreonder thanks, For now, we just hide it when no data. We will try your solution if customer doesn't like that.
