### ISSUE TITLE
Need typescript definition file.

### ISSUE THREAD

**Issue by rubinchyk** [google/google-visualization-issues#2534]
Trying to search Google Chart typescript definition file, but no one sources like TypeSearch etc. not consist any file about this library...

**Comment by rubinchyk** [comment]
I think it's happened, because I searched 'Google charts' but in this case right name - 'Google visualization'   [Google visualization typescript definition](https://www.npmjs.com/package/@types/google.visualization)

**Comment by nbering** [comment]
https://www.npmjs.com/package/@types/google.visualization
