### ISSUE TITLE
Documentation: Wrong reference to configuration option

### ISSUE THREAD

**Issue by TryingToImprove** [google/google-visualization-issues#2538]
As you can see on the image, the pie chart is referencing a prop called `pieSliceTextSlice` but should reference `pieSliceTextStyle`

https://developers.google.com/chart/interactive/docs/gallery/piechart#configuration-options
 
![image](https://user-images.githubusercontent.com/1690457/29613147-f1823d9c-8804-11e7-8abe-f619c35fb7ef.png)

**Comment by orwant** [comment]
Fixed. Thanks for reporting!

Jon
