### ISSUE TITLE
hAxis gridlines option ignored / too many vertical gridlines

### ISSUE THREAD

**Issue by nick2a** [google/google-visualization-issues#2555]
I noticed a change yesterday where many more hAxis gridlines (vertical lines) on my line graphs are being drawn. The result is a messy uneven look. The number of gridlines is way above what I see documented as the default of 5

I then set the gridlines.count option to these graphs but only in 1 case did this have a limited effect. 

I am attaching a file showing 3 line charts being created. They have similar datasets (all dates and numbers, of different amounts). Without the gridlines option they all have more than the default number of gridlines

When setting gridlines.count on the options (shared by all 3 charts) only the 1st chart seems to respond, and even then only when a gridline count of 4 or lower is set. From 5 upwards it returns to messy looking innacurate number of gridlines.

[chart.html.zip](https://github.com/google/google-visualization-issues/files/1317309/chart.html.zip)

Also hosted here:

https://tweets.nickab.uk/chart.html  - ( no gridlines option set )
https://tweets.nickab.uk/chart2.html - ( hAxis.gridlines.count set to 1)
https://tweets.nickab.uk/chart3.html - ( hAxis.gridlines.count set to 5)

**Comment by nick2a** [comment]
Note these gridlines have now returned to normal after what I assume was the rollback.

**Comment by dlaliberte** [comment]
Thanks for your report.  

The gridlines.count is gradually being deprecated.  Usually the count is the least useful way of specifying gridlines, and it often conflicts with finding good tick values.    But as special cases, a count of 0 or 1 will compute gridlines normally and then throw them away until 0 or 1 remain, with the exception of the baseline value.

**Comment by nick2a** [comment]
No problem, that makes a lot of sense thanks
Thank you also for your work and everyone else involved on this, I have loved using this api
