### ISSUE TITLE
hAxis/vAxis.textPosition = 'none' stopped working

### ISSUE THREAD

**Issue by sevalad** [google/google-visualization-issues#2556]
axis **textPosition** option with **'none'** value stopped working. It causes the next problem:
setting chartArea bottom leads to an error **Can not read property 'x' of null**. because it is not enough space for the vAxis text to be displayed correctly. Setting textPosition option to 'in' fixes the problem, but will need to change axis text color to 'transparent' to hide it.
Everything worked fine before 09.20.17
![image](https://user-images.githubusercontent.com/2684834/30651467-75385826-9e2e-11e7-9036-607a6914cf53.png)

**Comment by dlaliberte** [comment]
Thanks for your report.  I'll probably be rolling back to the prior version to let me fix several problems that have been exposed.

Could you point us at a webpage showing the problem you are seeing, especially the chartArea.bottom issue?  Or give enough details to reproduce this, say in a jsfiddle?

**Comment by sevalad** [comment]
@dlaliberte thanks for the quick reply. Took some time to reproduce it best. I guess the main start point is that the chart has to be **google.visualization.DataTable()** if it will be **arrayDataTable** it will work fine.
You can check it [here](https://jsfiddle.net/p2L9mn12/2/).  I found some more cases to reproduce the ticket. Also added some comments so you could play with behavior.
Hope it helped.

**Comment by dlaliberte** [comment]
Thanks for your example reproducing the problem.   It does seem that a bottom area that is too small exposes a problem in rendering that area.

I don't know why constructing the DataTable with arrayToDataTable would help, but perhaps there is a different conversion of your string dates.  You should generally not use strings for dates because of the differences in different browsers.

**Comment by sevalad** [comment]
The main problem is that the textPosition set to 'none' doesn't remove the axis text(just ignores). If it would have worked as expected there would be no issue. It worked fine for more than 1.5 a year for me, and today morning I faced an error

**Comment by sevalad** [comment]
Checked now, everything works fine like before
