### ISSUE TITLE
API functionality to Add Google Chart to Google Spreadsheet

### ISSUE THREAD

**Issue by vatsalvora** [google/google-visualization-issues#2562]
Is there a way to programmatically embed the chart created by the Google Chart API into a Google Spreadsheet? I know the Google Spreadsheet API provides some functionality, but is it possible to use the Google Chart API with the Google Spreadsheet API?

**Comment by nbering** [comment]
@vatsalvora I'm pretty sure the charts in Google Spreadsheets are the same javascript code as what you get when you pull the API into your project. Maybe you're looking for [Apps Script](https://developers.google.com/apps-script/)? It's an API to use JavaScript to embed some custom code into Google Docs.

**Comment by nbering** [comment]
Specifically, here's something for embedding a chart.

https://developers.google.com/apps-script/reference/spreadsheet/embedded-chart

**Comment by vatsalvora** [comment]
Hi, 

I looked into that also:
```javascript
function newChart() {
 var ss = SpreadsheetApp.getActiveSpreadsheet();
 var sheet = ss.getSheets()[0];
 

 // This creates a simple bar chart from the first three rows
 // of the first two columns of the spreadsheet
 var chart = sheet.newChart()
     .setChartType(Charts.ChartType.BAR)
     .addRange(sheet.getRange("A1:B4"))
     .setPosition(25, 5, 0, 0)
     .setOption("title", "Dynamic Chart")
     .build();
  
 var data = Charts.newDataTable()
       .addColumn(Charts.ColumnType.STRING, "Month")
       .addColumn(Charts.ColumnType.NUMBER, "In Store")
       .addColumn(Charts.ColumnType.NUMBER, "Online")
       .addRow(["January", 10, 1])
       .addRow(["February", 12, 1])
       .addRow(["March", 20, 2])
       .addRow(["April", 25, 3])
       .addRow(["May", 30, 4])
       .build();

   var drawChart = Charts.newPieChart()
       .setTitle('Sales Per Region')
       .setDimensions(600, 500)
       .set3D()
       .setDataTable(data)
       .build();
  
  Logger.log("Other Chart: "+ drawChart.getType());
  Logger.log("Chart: "+ chart.getType());
 sheet.insertChart(drawChart);

 }
```
^ in the above code, when I create a chart from the chart service and try to add it to my spreadsheet it does not work. It only works when I create a chart through the sheets API. 


The functionality I was looking for in the Spreadsheets API was for changing line colors, point size, and point shape. 

I could not find that functionality through these links:
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#BasicChartSpec
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#BasicChartSeries

This same functionality is available through the Charts API.

**Comment by nbering** [comment]
With a quick look, I don't see the specific options you are looking for either, perhaps you could create an apps script and call it through the rest API?

https://developers.google.com/apps-script/guides/rest/api

Beyond that suggestion... I suspect your issue is not with the Google Visualization API. Perhaps you can try some of the options for [Sheets API Support](https://developers.google.com/sheets/api/support)?

**Comment by vatsalvora** [comment]
Thank you for your time!

**Comment by MSMBilal** [comment]
![Uploading image.jpg…]()

**Comment by MSMBilal** [comment]
![Uploading image.jpg…]()
![Uploading image.jpg…]()
