### ISSUE TITLE
Add tooltip to Timeline Chart via Google Spreadsheet

### ISSUE THREAD

**Issue by mccrodp** [google/google-visualization-issues#2576]
### Steps to Reproduce
See code (https://github.com/mccrodp/availability-forecast):

````js
<script type="text/javascript">
      google.charts.load('current', {'packages':['timeline']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var query = new google.visualization.Query(URL);
        query.send(handleQueryResponse);
      }

      function handleQueryResponse(response) {
        var dataTable = response.getDataTable();
        var container = document.getElementById('timeline');
        var chart = new google.visualization.Timeline(container);
        chart.draw(dataTable, null);
      }
````

When I use a spreadsheet of 4 columns it works, but if I add a 5th column similar to described in https://developers.google.com/chart/interactive/docs/customizing_tooltip_content it gives the below error: `Invalid data table format: must have 3 or 4 columns`.

<img width="362" alt="screen shot 2017-11-07 at 15 44 32" src="https://user-images.githubusercontent.com/559938/32480549-b176b52a-c3d2-11e7-94a5-cc1ceaf9ca7e.png">

I imagine this is because it is not adding the `role` attribute properly when just adding to the spreadsheet. How do you replicate the below in the spreadsheet or code when importing from Google sheets?

````js
// A column for custom tooltip content
dataTable.addColumn({type: 'string', role: 'tooltip'});
````

Thanks!

**Comment by nbering** [comment]
You're probably right about it not having the `tooltip` role set for your extra column. You should be able to modify the role on an existing column like this:
```
dataTable.setColumnProperty(4, {role: "tooltip"});
```
Documention for this method available here:
https://developers.google.com/chart/interactive/docs/reference#DataTable_setColumnProperty

You haven't provided a complete working sample, so I haven't tested this. Give it a try.

**Comment by mccrodp** [comment]
Thank you very much @nbering, I was able to add a final column "Tooltip" to the spreadsheet and get rid of the error using the docs you linked, either with `setColumnProperties()` or `setColumnProperty()`, but it does not set the tooltip itself, it remains as the auto generated one. Getting closer though 😄 

This time the example is included, any ideas? Cheers!

**Demo:** https://mccrodp.github.io/availability-forecast/
**Code:** https://github.com/mccrodp/availability-forecast
**GSheet:** https://docs.google.com/spreadsheets/d/1MRcVKE3Nb-WU6RecYrTgQjMg4OX1JdaDtfk0HwDYktQ/edit#gid=0

**Comment by nbering** [comment]
I just noticed the [official example](https://developers.google.com/chart/interactive/docs/gallery/timeline#customizing-tooltips) has the tooltip data in the third column (index 2). Column ordering often matters in Google Charts, so try moving the "Tooltip" column next to the "Name" column, and adjust the javascript accordingly. That might help.

**Comment by dlaliberte** [comment]
You could use a DataView to specify a different column order, if there is a problem with changing the order of the DataTable columns.

**Comment by mccrodp** [comment]
@nbering, you were completely spot on, it was all about the ordering. I had to order as Index 2, thanks for that and @dlaliberte for the mention of DataView, didn't know it existed.

I'm going to close this issue, as solved, but before I do, any idea why Timeline doesn't support persisting of Tooltips. I got HTML tooltip working, but even a plain example does not support `trigger: 'selection'` or `both` option. See: https://jsfiddle.net/rmpodfze/ (If you remove the trigger entry from options, it will show as default, but not persist)

**Comment by dlaliberte** [comment]
The lack of persistent tooltips could well be a bug.  We only recently fixed selections to return relevant data.

**Comment by mccrodp** [comment]
Thank you @dlaliberte, I've opened https://github.com/google/google-visualization-issues/issues/2578 instead for that issue. Thanks again to you both.

**Comment by TomiBone** [comment]
Hi guys, I'm working with multiple charts. After joining them, only the last one renders with html tooltip. All the previous charts render with the default tooltip, not the html. How could I set all the tooltips to render with the preset html value?
