### ISSUE TITLE
defs

### ISSUE THREAD

**Issue by safetyhorse** [google/google-visualization-issues#2607]
https://developers.google.com/chart/interactive/docs/basic_multiple_charts

When using multiple charts on a page, each defs tag gets an id of "defs". Multiple elements in the same page with the same id is making my accessibility checker unhappy. Any resolution to this validation issue in sight?

**Comment by dlaliberte** [comment]
Thanks for your report.  This bug has existed for several years, and is simple to fix, and the fix will show up in the next release (which I am actually very close to pushing out).

**Comment by safetyhorse** [comment]
Excellent! Thanks for taking care of this.

**Comment by nagyt234** [comment]
The problem still exists, even on [Google's page](https://developers.google.com/chart)

**Comment by dlaliberte** [comment]
@nagy7234, I'm not seeing any problem with duplicate ids on the page you linked to, or the gallery page, or any chart pages that I can find.  Can you be more specific about the page, which tester you are using.  Can you link to your own page with multiple charts and duplicate ids?
