### ISSUE TITLE
Typo in Query Language Documentation

### ISSUE THREAD

**Issue by rachel-1** [google/google-visualization-issues#2664]
There are two typos at [https://developers.google.com/chart/interactive/docs/querylanguage#scalar_functions](https://developers.google.com/chart/interactive/docs/querylanguage#scalar_functions
)

For both the minute and second descriptions, the example given uses the "hour" function. 
```
Returns the minute value from a datetime or timeofday value. For example: hour(timeofday "12:03:17") returns 3
Returns the second value from a datetime or timeofday value. For example: hour(timeofday "12:03:17") returns 17
```
On a side note, it would be great if duration were eventually added as a numeric class. It took quite some time to figure out how to solve my issue of summing durations via query in Google sheets (for those who end up in the same boat, it was [this 2014 forum post](https://productforums.google.com/forum/#!topic/docs/srRCH4AYehM;context-place=topicsearchin/docs/category$3A(spreadsheets)$20duration$20in$20query) and the to_pure_number function that finally did the trick). For what it's worth, the situation absolutely required the use of query, so being able to operate on the duration directly (instead of relying on to_pure_number ignoring text data) would have been fantastic.

**Comment by orwant** [comment]
Typos fixed. Thanks for the report!
