### ISSUE TITLE
Sankey charts stopped rendering?

### ISSUE THREAD

**Issue by svdarren** [google/google-visualization-issues#2675]
Yesterday I was experimenting with Sankey charts, which were working fine.  Today Sankey charts are not rendering, including the samples embedded in the Google Visualization guides.  The charts aren't even rendering in the developers.google.com page or in the JSFiddle example links.  Other chart types are rendering correctly.

**Comment by dlaliberte** [comment]
Working again.  Sorry for the interruption.
