### ISSUE TITLE
v46 extremely bad draw performance with "string" values and textPosition "none"

### ISSUE THREAD

**Issue by longzheng** [google/google-visualization-issues#2679]
We use Google Charts' line chart to draw a chart with a horizontal axis of string values (rather than a number or date as it is more common).

We observed that in the latest version 46.1 (also affects 46) that the chart rendering performance in the `.draw()` call is over 50x slower. We're seeing it jump from 100ms to over 5000ms.

I've created a demo test case here https://jsfiddle.net/jkfwc85y/ by generating 1000 random data points. The extra data points exacerbates the problem to be more noticeable.

![untitled](https://user-images.githubusercontent.com/484912/47414886-d6f56f80-d7bd-11e8-8c22-27e8f4e6d4ae.png)

As you can see, the bug only occurs with a combination of two things: `string` data type on the and `textPosition: 'none'` are set on the horizontal axis. Changing either will render at acceptable speeds.

I have not tested whether a similar issue exists for the vAxis.

Funnily enough in our use implementation I've overriden the `chartArea` to be large enough so the hAxis is never rendered anyway so the `textPosition: 'none'` didn't actually have any effect. My workaround is to simply remove `textPosition`, however I believe this is still a pretty significant performance bug that will affect other users.

**Comment by longzheng** [comment]
I believe this bug was introduced with the latest set of v46 changes as documented in https://groups.google.com/forum/?hl=en#!topic/google-visualization-api/SaQnVkXTUO8 as it specifically mentions

>Fix textPosition == 'none', to generate gridlines with no ticks.

**Comment by dlaliberte** [comment]
Thanks for posting about this.  Definitely looks like a bug, though I am not sure it was due to the lastest v46 update (to 46.1) because that change made the textPosition == 'none' work with numbers and dates, which was failing in v46.  But regardless, there is more work to do for string data.  

By the way, if you try to load '46' now, it automatically redirects to '46.1'.

**Comment by longzheng** [comment]
> By the way, if you try to load '46' now, it automatically redirects to '46.1'.

Yeah I wasn't able to confirm if it was introduced in 46.1 since I couldn't find a way to test v46 specifically.

**Comment by dlaliberte** [comment]
This should be fixed in the latest updated v46 release, 46.2, also known as 'current' at this time.
