### ISSUE TITLE
Google Charts for Dart Lang

### ISSUE THREAD

**Issue by supermuka** [google/google-visualization-issues#2683]
[Dart lang](https://www.dartlang.org) it´s a great and nice language from Google.

For Charts, actually we have [Chartjs](https://pub.dartlang.org/packages/chartjs) ported to Dart.

Are there plans to port Google Charts to Web Dart?

**Comment by dlaliberte** [comment]
No plans to "port" to Dart, though there is a wrapper API you can use: 
https://pub.dartlang.org/packages/google_charts
https://pub.dartlang.org/documentation/google_charts/latest/google.charts/google.charts-library.html

**Comment by supermuka** [comment]
I'm a little sad to know there are no plans for Dart. It would be an incredible contribution to Web developers who love Dart.

The "google_charts" package is currently out of date with version Dart 2.

**Comment by supermuka** [comment]
Answered.
