### ISSUE TITLE
Line chart not displaying one row data with datetime column.

### ISSUE THREAD

**Issue by preechaim** [google/google-visualization-issues#2689]
Hi
I found a problem on the Line chart.
When it has only one data row with a 'datetime' type column as axis, the chart is blank.
More than one data row, it works fine.
It also was working fine before, I just found it recently.
See: https://jsfiddle.net/n5vjeo76/6/

**Comment by dlaliberte** [comment]
Definitely a bug, in that it doesn't show any hAxis at all.  You can work around it, however, by adding a viewWindow option.  See https://jsfiddle.net/dlaliberte/w3y507az/

**Comment by preechaim** [comment]
Hi dlaliberte,
With your work around, the hAxis is appeared, but it is still not showing a data point.

Edit:
Sorry, it is working. I didn't see the dots.
Thank you

**Comment by dlaliberte** [comment]
It is showing point at the top and bottom of the vAxis.  Adjust the viewWindow to move the min to the left, so the points will end up in the middle.
