### ISSUE TITLE
Google map visualisation not working for named locations

### ISSUE THREAD

**Issue by jeffdbelcher** [google/google-visualization-issues#2698]
This issue can be seen on Google's own gallery:

https://developers.google.com/chart/interactive/docs/gallery/map

"No data points to show on map" is being displayed for map visualisations using named locations rather than lat/long.

**Comment by nbering** [comment]
Console errors on the docs page indicate that it's an API key issue for the geocoding service.

**Comment by dlaliberte** [comment]
Duplicate of #2699
