### ISSUE TITLE
Google geo charts displayMode - markers for city/region not working.

### ISSUE THREAD

**Issue by VigneshD96** [google/google-visualization-issues#2699]
![mapsmarkers](https://user-images.githubusercontent.com/45787251/49793396-1fabbc80-fd5b-11e8-95ce-43ebc13d8a48.png)
Google Geo Maps, displaymode markers not working.

**Comment by dlaliberte** [comment]
Should be fixed now. We had a mis-configuration of how we use the geocoding service.

**Comment by dlaliberte** [comment]
In case it is not clear, you have to get your own mapsApiKey.  It will no longer work to just copy the one that you find in the documentation pages.
