### ISSUE TITLE
Changes in Google Object cause issues further down.

### ISSUE THREAD

**Issue by Frederic-P** [google/google-visualization-issues#2702]
Hi,

In spite of all the customization options present in google charts we apply another customization layer on top. For this we have the following code that merges the thousands of results - this is normal code supported by the Google Chart api.
`    
var newData = google.visualization.data.group(data_object, [{
      column: 0,
      type: 'para'
    }], [{
      column: 1,
      label: 'ratio',
      aggregation: google.visualization.data.sum,
      type: 'number'
    }]);`

then later in the code I modify a part of the newData variable depending on user interaction; this code starts with:
`    var editable_dataset = newData["wg"]; //use this for data manipulation
`

Yesterday for the second time since I joined the project the key for newData changed without notice. The first time it changed was 3/10/2018. Until then we used:
`    var editable_dataset = newData["og"]; //use this for data manipulation
`
for reasons  I still can't understand the "og" key was changed to "xg"; so the code was updated to:
`    var editable_dataset = newData["xg"]; //use this for data manipulation
`
Then yesterday we noticed that the overlay wasn't working properly again. By changing the key from "xg" to the current
`    var editable_dataset = newData["wg"]; //use this for data manipulation
`
I got the extra overlay working again. So I have two questions:

1) Is there a stable version of the google charts api where this change isn't made?
2) If not, is there a way to automatically detect the name of the key should it change again? I thought to use the index. However if the name of a key can change, than what's to assure me that it's position is not going to change either?

**Comment by dlaliberte** [comment]
It is highly recommended that you do not depend on internal property names generated by the compiler.  These will change every time google charts is updated.  Furthermore, modifying the internals of the data structures is also asking for trouble.    You should always go through the methods and options of the public API.  Feel free to modify the options and data that you provide as input; hopefully, we have written the code such that no ill effects will result if you do that.

If you have need of some capability that is apparently not provided by the public API, please ask, and maybe some alternatives can be suggested, or if there is a strong enough need, a change can be made to the API.

There are 'frozen' versions of google charts, as documented on the [release notes](https://developers.google.com/chart/interactive/docs/release_notes#official-releases).   But even these versions could be changed, if necessary, although it is unlikely.

**Comment by Frederic-P** [comment]
So there are two factors that limit our projects when just using the public API. Our data is historical data of events, annotations, dates of birth/death, etc... not all of this can be dated exactly which is why we give a score to each year in that range. That score is (1/range). So if a text is written somewhere between 33AD and 37AD then the score for that text, for each year is 0.2. (33ad=0.2; 34ad=0.2;35ad=0.2;36ad=02;37ad=0.2).

In rare events, text are dated more precise than that. When visualizing this, this produces outliers (in fact the outliers are the precise measurements); often leading to misinterpretations etc... What we did then was to make a 'smoother'; the thing is that we need the graph to be created first (hence why we adres the non-public api of google charts). Firstly we need the method
`var newData = google.visualization.data.group(data_object, [{ column: 0, type: 'para' }], [{ column: 1, label: 'ratio', aggregation: google.visualization.data.sum, type: 'number' }]);`

This helps us to group all the values for each year together (a graph can for instance show every text written in a certain language; for often used languages, this often covers tens of thousands of texts with multiple datapoints. Keeping track of them in the PHP makes the scripts too slow/or consumes too much memory.

With the var newData the graph is created the graph is visually changed to include a slider, this slider addresses a value (`var n`); that we'll call the smoothrange. When smoothing the data the custom JS iterates over every year and takes the values before that and after that. So if we have n=5 we slice a part of the data, ending up with 11 values. Then these values are averaged and used only for that year:small example (haven't tested it)
```
var example_data={
100:5.4,
101:5.6,
102:5.5,  
103:8.1,
104:2.3,
105:4.8,
106:5.2,
107:5.8,
108:5.9,
109:6.0,
110:6.1
...//more data
}
var n = 2 //this would comes from the slider with an event.
var y = 104;  //this is normally part of an iteration.
var slice = [];
var tot= 0;
var start = y-n //take the current year and substract the range
var end = y+n//take the current year and add to the range
/*we have checks in place so that we don't end up with indexes that are <0 or >Object.keys(example_data)
*/
for( var x = start; x < end; x++ ){
    var value_of_given_year = example_data[x];
    slice.push(value_of_given_year );
}
//the slice array should contain: 5.5, 8.1, 2.3, 4.8, 5.2 //
//that is ==>                               y-n         y           y+n

for (var i=0; i < slice.length;i++{
    tot = tot+slice[i];
}
var avg = tot/slice.length;   // this is now the value used for the year in var y. and should be 5.18
```
We do this for every key in example_data and end up with a derived variable. Let's call that `derived_data`. This `derived_data `object has the same keys that were present in `example_data`; however the values for `derived_data` are the smoothed results. 
This is now used to make the graph. 

The second issue we have with the public properties is the 0 in the graph. When working with time-series that have negative values (i.e. BC) then it shows a 0 in the graph. This is also something we'd like to address as there's no such thing as the year 0: https://en.wikipedia.org/wiki/Year_zero 

I haven't found in the public API any indication that we can tell Google Graphs that it's dealing with timeseries data that spans a range from 300BC to 800AD. Since our data is always historical data we don't have a value for the year zero. Leading to a dip for that inexistant year in the graph. We've created a hackish workaround in the php where it echoes a value for zero that is the average of the value for 1BC and 1AD. The dip is gone, but now it's giving the impression that something happend in a year that didn't exist and shouldn't be on the graph in the first place. We don't have a JS-based fixed for this in place (yet)

**Comment by dlaliberte** [comment]
The result of calling google.visualization.data.group is itself a DataTable, so you should be able to get all the values from that newData object using the DataTable methods.  In particular, newData.getValue(rIndex, cIndex) will get you the value at each row and column.  So I am not seeing any need to look in the properties of newData directly.

You might also be interested in creating a DataView from your newData, in which you can specify a calculated column (with your own custom function) which computes the average of some number of previously existing values.

Regarding the 0 date value, I wasn't aware that 0AD is the same as 1BC.  Interesting.  But that means all the dates are effectively AD, so you would have to take a positive BC value (say 1BC) and convert it into a negative AD value and add 1 year (so 1BC => (-1 + 1)AD == 0AD). That way, there is no inconsistency in the values, except there is effectively no way to display values differently for AD and BC.  You could specify the formatted representation of every date, either adding 'AD' or 'BC', and doing the appropriate calculation to convert negative AD values into positive BC values.  But there is no way to similarly compute the formatting of axis tick labels.  Worse yet, JavaScript dates don't let you specify dates before the year 100, at least not easily, and perhaps not before 1970 even.  See https://stackoverflow.com/questions/29968116/javascript-date-01-01-0001

So you really need to represent your dates entirely yourself, probably using just plain numbers, and also specify how to format every value.  Again, you can specify the exact string you want to represent each value (using the {v: value, f: formattedValue} notation), but for tick values, you would at best have to specify the exact tick values you want displayed, and for each one, how it should be formatted.  See the 'ticks' option for that.

**Comment by Frederic-P** [comment]
The getValue indeed fixed the issue; thanks I've missed that one. 

For the customizable dates I'll go with an extra column; probably a display_date-column and an order_column. The dipslay_date can be determined by using the order_column and I can consider 0 as 1AD; 1 as 2AD etc... without having gaps in the line. Thanks for the input!

**Comment by dlaliberte** [comment]
Glad you found a solution.
