### ISSUE TITLE
502 Error for charts.googleapis.com

### ISSUE THREAD

**Issue by barrett316** [google/google-visualization-issues#2721]
Our filemaker server calls on a QR code from "https://chart.googleapis.com/chart?cht=qr&chs=150x150&chl=" 

It is reporting back with a 502 error. It has been working fine for months, and there were no network changes or code changes in filemaker. 

It seems almost like it's down on the Google server side.

**Comment by orwant** [comment]
It is down and will be until 3pm ET today. This is a planned outage in anticipation of the service being turned off for good on March 14.

Google Image Charts (not Google Charts!) was announced as deprecated in 2012. Information is on the support forum: https://groups.google.com/forum/#!topic/google-chart-api/rZtHTyYgyXI.

**Comment by tggeth** [comment]
Hello, we have the same issue with the error 502. Any update?

**Comment by barrett316** [comment]
I recommend goqr.me for QR codes. Apparently Google turned off this service for good.

**Comment by orwant** [comment]
Correct: the service has been turned off for good. If you decide to use another service for QR codes, make sure it's a trustworthy source.

**Comment by tggeth** [comment]
Any suggestion?

**Comment by tggeth** [comment]
Thanks now i have seen your suggestion.
