### ISSUE TITLE
HTTP Status 502 by loading chart

### ISSUE THREAD

**Issue by BisnodeCH** [google/google-visualization-issues#2725]
Hi,
Since today we have a 502 error by calling "http://chart.apis.google.com/chart?cht=bhs"
Thank you in advance and BR
Luca

**Comment by orwant** [comment]
Any use of "chart.apis.google.com" or "chart.googleapis.com" was using Google Image Charts, which was deprecated 7 years ago and finally turned off yesterday. See https://groups.google.com/forum/#!topic/google-chart-api/rZtHTyYgyXI for the public announcement of the turndown.

I recommend upgrading to Google Charts or using one of the alternatives mentioned in that thread.

**Comment by BisnodeCH** [comment]
Hi Jon,
Thanks for your feedback – we’ll upgrade to Google Charts if we can.
Have a nice day.
BR from Switzerland
Luca

Luca Comparato
Developer
Bisnode D&B Schweiz AG
Direct: +41 44 735 63 89
Fax: +41 44 735 61 61
luca.comparato@bisnode.com<mailto:luca.comparato@bisnode.com>
Grossmattstrasse 9, CH-8902 Urdorf
www.bisnode.ch<http://www.bisnode.ch>

Folgen Sie Bisnode D&B auf Social Media:
LinkedIn<https://www.linkedin.com/company/233636> -  XING<https://www.xing.com/company/bisnode> -  Twitter<www.twitter.com/bisnode_ch> -  Facebook<https://www.facebook.com/bisnode.ch> -  Google+<https://plus.google.com/+BisnodeDBSchweizAGUrdorf/posts> -  Youtube<https://www.youtube.com/channel/UC2aQdi8Mk_cy04YNsFTgjxw>

[http://www.dnbschweiz.ch/logos/Hoovers_freetrial.jpg]<https://bisno.de/1oG>

Unsere Datenschutzgrundsätze finde Sie unter: https://www.bisnode.ch/datenschutz/
