### ISSUE TITLE
Drawing Timeline and Line charts on same page causes exception: Uncaught (in promise) Error: Container is not defined

### ISSUE THREAD

**Issue by caspianb** [google/google-visualization-issues#2733]
Trying to load the attached page will show the error (only the Timeline will load; the line chart will not due to an uncaught error).

Commenting out the load callback for either chart will allow the other one will load successfully - this shows the issue only occurs when both charts are (attempted to be) displayed simultaneously.

[chart_error.zip](https://github.com/google/google-visualization-issues/files/3073661/chart_error.zip)

**Comment by dlaliberte** [comment]
The problem is that you are calling google.charts.load() twice and also calling google.charts.setOnLoadCallback() twice, and neither callback knows which load you are waiting for, so they both will run after the first load finishes.

You can fix this various ways.  The cleanest, if you want to keep the load calls separate, is to add a callback parameter for each load call, like this:

```
google.charts.load('current', {
  packages: ['timeline'], callback: drawTimeline
});
google.charts.load('current', {
  packages: ['corechart'], callback: drawLineChart
});

```

Here is a [jsfiddle of the working code](https://jsfiddle.net/dlaliberte/L7de2y08/8/).

**Comment by caspianb** [comment]
@dlaliberte - I do not believe you fully tested your suggestions as they still fail when loaded directly by Chrome (as well as Firefox and Edge -- also it is worth noting that the original file I attached *works* when loaded into jsfiddle as well).

I made the above changes and it still fails in Chrome for the exact same reason. I also tried variations of what you described above (prior to creating this issue) already with no success.

**Comment by dlaliberte** [comment]
My jsfiddle is working fine for me in Chrome while your original code did not work for me in jsfiddle until I fixed the problem as I suggested.  At best, if your works, you were lucky that both load calls were finished before the corresponding setOnLoadCallback calls were started.  

I doubt jsfiddle has anything to do with making my suggestion work, but if you have a website that shows a failure doing it how I suggest but without using jsfiddle, please post a link to that.  Thanks.

**Comment by caspianb** [comment]
@dlaliberte 
The files are not on the web, but I have generated three other test cases (all of which I actually did try 
 prior to logging this issue - including one with your suggested changes). However, they all fail in Chrome, Firefox, and Edge.

[chart_errors.zip](https://github.com/google/google-visualization-issues/files/3073987/chart_errors.zip)

**Comment by dlaliberte** [comment]
You'll have to prove it.  I expect there is something different about how you are composing your web page when not using jsfiddle.  At least put the same code up in a jsfiddle (or similar) so we can see the code.

**Comment by caspianb** [comment]
I provided three new test cases that should prove the issue in the above zip file (including one with your suggested changes).

Here is a link with your suggested changes that fails: https://jsfiddle.net/dp9eu350/

EDIT:
Comparing your fiddle to mine, I noticed some very weird quirks (only in JSFiddle).
If I define my chart divs self closing tags then I get the error. If I define the divs using explicit close tags then I don't get the error in JSFiddle. Very strange.

HOWEVER, I get the error with either approach to defining the div blocks in Chrome. I would suggest avoiding JSFiddle and opening the files I provided directly into a browser to diagnose this issue.

**Comment by dlaliberte** [comment]
I see the same problem you describe that involves how you defined your divs.  That is the source of the missing containers, independent of the separate problem with how you called the setOnLoadCallback multiple times.  Also your use of height: 100% will hide your second chart even if you get two to display. 

So it appears that jsfiddle fixes your otherwise unclosed divs.  [Self-closing divs are not supported in browsers](https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5).

**Comment by caspianb** [comment]
I repeat: "HOWEVER, I get the error with either approach to defining the div blocks in Chrome. I would suggest avoiding JSFiddle and opening the files I provided directly into a browser to diagnose this issue."

I have provided a new zip with my three updated test cases showing the error still occurs WITHOUT self-closing tags. You will note that, even with explicit close tags the error still occurs.

[chart_errors.zip](https://github.com/google/google-visualization-issues/files/3074095/chart_errors.zip)

**Comment by dlaliberte** [comment]
I see no error when I open chart_error1.html in your latest.  You are still including the height: 100% in your styles, so your first chart takes up the whole page, and hides your second chart.

**Comment by caspianb** [comment]
Ah, I have it. The self closing tags were the cause of the local issue as well. Sorry - and thanks!

**Comment by dlaliberte** [comment]
You're welcome.  Fixing 3 problems at once is challenging when you don't know what's going wrong.  Trying to fix only 1 or 2 problems, it still looks broken, so it looks like the fix was not working.
