### ISSUE TITLE
vAxis title not always rendered

### ISSUE THREAD

**Issue by terje-rosenlund** [google/google-visualization-issues#2779]
Scatter chart with one data serie where the vertical title and horisontal grid-text is rendered in case 1 but not in case 2:

case 1: Timerange 1 hour, 459 points, y-min-max: 0.027-6.895
case 2: Timerange 25 minutes, 221 points, y-min-max: 0.027-0.142 (within range in case 1)

Min/max values for x- and y-axis are different in case 1 and case 2 but the available space for vertical title is the same (fixed height (400))

It seems that text for horisontal grid-lines is skipped if all values on horizontal grid is < 1 and that the vertical title is also skipped if so

![alt text](http://terje-rosenlund.no/google/bugs/images/vAxis.png "Missing title on vAxis")

**Comment by terje-rosenlund** [comment]
Not the first time and shurly not the last - my bad again

I was setting options.vAxis.format = "0" so chart.draw(dataTable, options) did what it was asked to do

**Comment by dlaliberte** [comment]
I was going to suggest that.  However, it should at least show the rounded tick values, 0s or 1s in your case, rather than fail to show anything.   It currently gives up after trying every alternative rather than keep the "best" of the alternatives that fails.
