### ISSUE TITLE
When formatting a 2019 date value greater than 29 december 2019, it will show year 2020

### ISSUE THREAD

**Issue by raul-handpoint** [google/google-visualization-issues#2783]
When formatting date values of a DataTable using a DateFormat object, if the date is 29 or 30 december 2019, it will display 2020 as year.

This issue will probably also happen with 31 december 2019 datetimes, but I haven't test it.

`
let datetimeFormatter = new google.visualization.DateFormat("YYYY-MM-dd HH:mm:ss");
datetimeFormatter.format(dataTable, getColumnIndex(dataTable, TIMESTAMP_COLUMN));
`

**Comment by dlaliberte** [comment]
I'm not seeing this.  Are you sure you have your dates specified correctly?  Month numbers in the Date constructor, or the string notation (e.g. "Date(2019, 11, 29)" ) start with 0, so 11 is December.

**Comment by raul-handpoint** [comment]
@dlaliberte Thanks for answering!

The DataTable column is filled with Date object values and I have verified by debugging on Chrome that the dates are correct.

![Captura de pantalla 2019-12-30 a las 16 58 35](https://user-images.githubusercontent.com/33625384/71589572-a6c60100-2b25-11ea-958b-4cfbdb964a57.png)

However, when such dates are formatted through the DateFormat object to be displayed on screen, the resulting strings are incorrect for dates equal or greater than 29 december 2019.

![Captura de pantalla 2019-12-30 a las 17 00 42](https://user-images.githubusercontent.com/33625384/71589664-f1477d80-2b25-11ea-8399-f2ac5ccbe6cc.png)

**Comment by dlaliberte** [comment]
It may depend on which chart you are drawing.  Also, I'm assuming you are using the 'current' version via the gstatic loader.

**Comment by dlaliberte** [comment]
I see the problem now in formatting of tick values for corecharts.  Weird, especially that such a problem not has been reported previously for other dates.  Not sure I will have time to fix it before it is too late for the current date, but it will remain relevant going forward.

**Comment by raul-handpoint** [comment]
@dlaliberte Thanks a lot for your help! I appreciate your concern. Let me know if I can help you. Happy new year!

**Comment by raul-handpoint** [comment]
@dlaliberte Hi, good morning! Do you casually have any news regarding this issue? Thanks.

**Comment by pzygielo** [comment]
@raul-handpoint - 

1. https://developers.google.com/chart/interactive/docs/reference#dateformatter:

> The recommended pattern standards are the ICU DecimalFormat and [SimpleDateFormat](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/SimpleDateFormat.html)

2. https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/SimpleDateFormat.html
>  Y: Year (in "Week of Year" based calendars). Normally the length specifies the padding,          but for two letters it also specifies the maximum length. **This year designation is used in ISO year-week calendar as defined by ISO 8601**, but can be used in non-Gregorian based calendar systems          where week date processing is desired. May not always be the same value as calendar year.

3. [Why 2020 Started On December 30th by Tom Scott](https://www.youtube.com/watch?v=D3jxx8Yyw1c)

So I guess the issue lies in using pattern letter `Y` and expecting behaviour of `y`.

**Comment by dlaliberte** [comment]
> So I guess the issue lies in using pattern letter `Y` and expecting behaviour of `y`.

Wow!  This is news to me. Thanks very much for posting, pzygielo.

**Comment by raul-handpoint** [comment]
The solution worked for me. It's quite weird but anyway... Thanks a lot for the help!!
