### ISSUE TITLE
Zoom buttons on annotation chart

### ISSUE THREAD

**Issue by nav1n** [google/google-visualization-issues#2794]
I suspect there is a bug with zoom buttons on annotation charts as in current/47 they no longer work. Can confirm they still work in 46.
Example here:
https://developers.google.com/chart/interactive/docs/gallery/annotationchart

**Comment by dlaliberte** [comment]
You are correct.  I haven't checked yet, but I'll bet this involves the html sanitizing that we are doing now more aggressively, and apparently, sometimes incorrectly.

**Comment by ScriptedFluff** [comment]
Is there a timeline or estimate for this case to be picked up?

**Comment by dlaliberte** [comment]
I believe that has been fixed in the 'current' release, which is '48'.  Yes, it works on the documentation page.
