### ISSUE TITLE
Redirection of https://www.google.com/jsapi stopped support for visualization version ~1.1

### ISSUE THREAD

**Issue by KaptenJon** [google/google-visualization-issues#2832]
I have been using version 1.1 using endpoint https://www.google.com/jsapi but now it redirects to the new loader https://www.gstatic.com/charts/loader.js and it does not support versions prior to 41. 
I rendering using QT4 and cannot use newer version unfortunately. Could you add support for version 1.1 in the new loader?

**Comment by dlaliberte** [comment]
Version 1.1 from the old server is closest to version '45.2', since that is the last version I could update on the old server.  I hope that version works for you.

See the [release notes](https://developers.google.com/chart/interactive/docs/release_notes) for a summary of changes for all releases.

**Comment by KaptenJon** [comment]
The problem was not the package but rather the loader.  By using som hack during javasript loading I could successfully use google chart. (found in another github answer)

`		function init() {
			google.charts.load('current', { 'packages': ['corechart'] });
			var interval = setInterval(function () {
				if (
					google.visualization !== undefined
						&& google.visualization.DataTable !== undefined
						&& google.visualization.LineChart !== undefined
				) {
					clearInterval(interval);
					drawLineChart();
					window.status = 'ready';
				}
			}, 100);
		}
	</script>
</head>
<body onload="init()">`

**Comment by dlaliberte** [comment]
Instead of all that setInterval code, you should be able to just change your google.charts.load call to:

`google.charts.load('current', { 'packages': ['corechart'], 'callback': drawLineChart  });
`

**Comment by KaptenJon** [comment]
For sure in a normal case. But not with my old renderer.

**Comment by dlaliberte** [comment]
I'm curious why this would be the case.  Makes me wonder what is in your drawLineChart function, and what else is happening on the page.  

If you want to avoid more surprises, you may want to change 'current' to '48', which is the current release at this time, but it will be changing when we push out a new release.

**Comment by KaptenJon** [comment]
Might be an Idea with 48! 
DrawlineChart is using google charts no fancy stuff there. I only changed from 
google.charts.load('current', { 'packages': ['corechart'], 'callback': drawLineChart });
to the init loader hack in my previous comment.

**Comment by tecssil** [comment]
Any thoughts on this? I have the same problem, I'm redering charts into a PDF, but the loader is not able to "load" anymore. I was using the old jsapi and google.load, I made the changes as google stayed in the release and I got no charts on the PDF, it will render on web though. I tried the workaround mentioned here and no luck yet

**Comment by KaptenJon** [comment]
Did you run the init function. I use Wkhtml and start init by `<body onload="init()">`

**Comment by fdoyen** [comment]
> Did you run the init function. I use Wkhtml and start init by `<body onload="init()">`

For me, it didnt works. I will try in few hours to stream the PDF in a webpage to activate console log and check if there is anny errors and try to debug it... But I'm facing the same problem here :

I was using the 1.1 version, worked well, and begin of June 2020, nothing works anymore. Using wkhtmltopdf 0.12.4 (upgraded to 0.12.5 to see if it could change anything : didnt works)

**Comment by KaptenJon** [comment]
I run on 0.12.5 with current chart version work great now. I guess you also use the jsdelay option on wkhtml.

**Comment by dlaliberte** [comment]
By the way, version "1.1" loaded via the jsapi server now maps to the 'upcoming' version, which at this time is the same as 'current' but as each new release is pushed out, it is the next version made available for beta testing purposes until 'current' is switched to that same new release.  

You may want to switch to "1.0" which is the 'current' version.  Or you may want to switch to '45.2', which was closest to the version last available via the jsapi loader.

**Comment by fdoyen** [comment]
As I wrote here -> https://stackoverflow.com/a/62501534/3536432

I solved my problem with 2 steps :

installing libssl because wkhtmltopdf wants this lib to work with HTTPS URLs and adding a setinterval while loading the lib. You can see the full code answer on my stackoverflow answer. (well inspired by KaptenJon answer)

Good luck guys.

**Comment by ulrichenslin** [comment]
Using '--window-status ready' combined with the following JS solved the loading issue.  The problem is a timing issue, which is solved by the JS function:

```
function loadGoogleGraph(graphCallback) {
        var interval = setInterval(function() {
            console.log('not-ready-yet');
            if (
                google.visualization !== undefined
                && google.visualization.DataTable !== undefined
                && google.visualization.PieChart !== undefined
            ){
                clearInterval(interval);
                console.log('ready');
                window.status = 'ready';
                graphCallback()
              }
        }, 100);
    }


    loadGoogleGraph(<YOUR FUNCTION>)

```

instead of

```
google.charts.setOnLoadCallback(<YOUR FUNCTION>);
```

Above is an adaptation from Abisco: https://github.com/barryvdh/laravel-snappy/issues/255#issuecomment-628815194
