### ISSUE TITLE
GeoChart no longer included in corechart

### ISSUE THREAD

**Issue by ankane** [google/google-visualization-issues#2845]
Hi, it looks like the GeoChart is no longer included in `corechart` and instead a separate `geochart` package with the release of version 49. Can this be added to the release notes? https://developers.google.com/chart/interactive/docs/release_notes#current:-july-2020

**Comment by dlaliberte** [comment]
The geochart has always been [documented as requiring the 'geochart' package](https://developers.google.com/chart/interactive/docs/gallery/geochart#loading), but at some point, we accidentally started including the geochart code along with the 'corechart' package.   We finally found the cause of that and fixed it, so it works as documented again.  Sorry for the confusion.  I'll add a note to the release notes about the bug fix.

**Comment by ankane** [comment]
Thanks for clarifying and the quick response!
