### ISSUE TITLE
response.isError is true because "Request timed out"

### ISSUE THREAD

**Issue by gx-kazuya-okamoto** [google/google-visualization-issues#2846]
Until the other day, the following programs were running.
I have not modified the program.
But now when I start it I get the error.
The error[response.getMessage()] is "Request timed out".
Is the specification changed due to the processing of the callback on the Google API side?
Please tell me how to deal with it.

```
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<Script Language="JavaScript">
<!--

const wSpreadSheet = "https://docs.google.com/spreadsheets/d/1H0QH-onJ1vPUwesyfuHYwo3I7wgbs4L__RsRPzkBNaE/edit#gid=0";

var data;
google.load('visualization', '1');

function init(){
readSS();
}

function readSS() {
var query = new google.visualization.Query(wSpreadSheet);
query.setQuery("select A");
query.send(handleQueryResponse);
}

google.setOnLoadCallback(init);

function handleQueryResponse(response) {
if (response.isError()) {
alert('Error in query: ' + response.getMessage() + ' - ' + response.getDetailedMessage());
return;
}
data = response.getDataTable();
}

//-->
</script>
```

**Comment by gx-kazuya-okamoto** [comment]
The cause is known.
The version does not currently work.
It worked on version 48.

before
<pre>
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
google.load('visualization', '1.0');
</pre>

after
<pre>
<script src="https://www.gstatic.com/charts/loader.js"></script>
google.charts.load('48', {packages: ['corechart']});
</pre>

**Comment by XTJX21X** [comment]
#@`
Duplicate of #`
