### ISSUE TITLE
Timeline overlaps items for Aug-31 and Sep-01

### ISSUE THREAD

**Issue by prcdutra** [google/google-visualization-issues#2872]
When creating a timeline for items that cross Aug-31 and Sep-01, the items are overlapped.

**Problematic example:**

      google.charts.load('current', {'packages':['timeline']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
		  var options = {}

          var container202008 = document.getElementById("timeline202008");
          var chart202008 = new google.visualization.Timeline(container202008);

      var dataTable202008 = google.visualization.arrayToDataTable([
        ['Group', 'Activity', 'Start Time', 'End Time'],
		['G1','Job1', 
		new Date(2014, 08, 31, 17, 30), 
		new Date(2014, 08, 31, 20, 39)],

		['G1','Job2', 
		new Date(2014, 09, 01, 06, 20), 
		new Date(2014, 09, 01, 07, 14)],

		['G1','Job1', 
		new Date(2014, 09, 01, 17, 30), 
		new Date(2014, 09, 01, 19, 41)]
		]);

            chart202008.draw(dataTable202008, options);

   }
![image](https://user-images.githubusercontent.com/75105719/100406650-22397680-3045-11eb-9e15-1fa4ae3511af.png)

Job1 is executed every day at the same time, so it would be expected that the timeline do not grouped them.

**Working Example: Dates were substitutes by 31-JUL and 01-AUG. No changes on times.**

      google.charts.load('current', {'packages':['timeline']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
		  var options = {}

          var container202008 = document.getElementById("timeline202008");
          var chart202008 = new google.visualization.Timeline(container202008);

      var dataTable202008 = google.visualization.arrayToDataTable([
        ['Group', 'Activity', 'Start Time', 'End Time'],
		['G1','Job1', 
		new Date(2014, 07, 31, 17, 30), 
		new Date(2014, 07, 31, 20, 39)],

		['G1','Job2', 
		new Date(2014, 08, 01, 06, 20), 
		new Date(2014, 08, 01, 07, 14)],

		['G1','Job1', 
		new Date(2014, 08, 01, 17, 30), 
		new Date(2014, 08, 01, 19, 41)]
		]);

            chart202008.draw(dataTable202008, options);

   }

Results for Jul/Aug are as expected.
![image](https://user-images.githubusercontent.com/75105719/100406729-64fb4e80-3045-11eb-9009-c071254b52e0.png)

**Comment by dlaliberte** [comment]
The [month number for JavaScript Date constructor starts at 0](https://stackoverflow.com/questions/1507619/javascript-date-utc-function-is-off-by-a-month), so 8 is actually September, and September 31 is really October 1.
