### ISSUE TITLE
Anchor Link misspelled in developers.google.com/chart/interactive/docs/basic_load_libs

### ISSUE THREAD

**Issue by renika** [google/google-visualization-issues#2885]
inside HTML H3 TAG WITH ATTRIBUTE ID "load-settings"

anchor link to href Locales is misspelled 

`<a href="#Locales>">Locales</a>`

It should be:
`<a href="#Locales">Locales</a>`

**Comment by dlaliberte** [comment]
Those two "Locales" look identical.  What are we missing?

**Comment by orwant** [comment]
There's an extra > symbol in the first. Dan, I sent you the fix.

**Comment by dlaliberte** [comment]
Oh, of course.  Thanks Jon!
