### ISSUE TITLE
Timeline Chart Bug?

### ISSUE THREAD

**Issue by Kengkardy** [google/google-visualization-issues#2897]
https://developers-dot-devsite-v2-prod.appspot.com/chart/interactive/docs/gallery/timeline

For the first example of your page

        dataTable.addRows([
          [ 'Washington', new Date(1789, 3, 30), new Date(1797, 2, 4) ],

As you see Year, month and day for Start is 1789, 3, 30  and end date is 1797, 2 ,4
so the month of start date is march and month of end date is february
but the timeline chart displays a wrong month 

it is showing "April" on the start date and "Mar" on the end date 

Please Fix this and thank you.

**Comment by dlaliberte** [comment]
Month indexes in JavaScript, Java, and most languages, start with 0, so this is working as intended.    https://stackoverflow.com/questions/2552483/why-does-the-month-argument-range-from-0-to-11-in-javascripts-date-constructor
