### ISSUE TITLE
ChartWrapper wrong year

### ISSUE THREAD

**Issue by HyouSei** [google/google-visualization-issues#2907]
when i draw a Dashboard with timeline and DateRangeFilter ChartWrapper by using data like this:
dataTable.addRows([
		        ["A",  "TESTA"  , new Date(2020, 10, 1), new Date(2020, 10, 28)],
		        ["B",  "TESTB"  , new Date(2020, 11, 1), new Date(2020, 11, 28)],
		    ]);
the date on the right side of filter became "2021/12/28", it supposed to be "2020/12/28".

![20210512152900](https://user-images.githubusercontent.com/71740455/117928646-cdf62a80-b336-11eb-92b5-4540a3387e56.png)

![20210512152527](https://user-images.githubusercontent.com/71740455/117928299-52947900-b336-11eb-88dc-b0c05c834db5.jpg)

the year on filter is right when the date is 2020/12/26 or 2019/12/27. when date is 2020/12/27~2020/12/31, year became 2021.

**Comment by dlaliberte** [comment]
This would appear to be a problem not with the ChartWrapper or even the ControlWrapper but the DateRangeFilter which is showing the date range it gets from column 3 of the data.   Thanks for your report, and for the detail about what dates it fails on.  Not sure when we can get around to fixing this, however.

**Comment by pzygielo** [comment]
Per http://userguide.icu-project.org/formatparse/datetime - `y` is year, while `Y` is _year of "Week of Year"_ (check https://www.youtube.com/watch?v=D3jxx8Yyw1c). However https://developers.google.com/chart/interactive/docs/reference?hl=en#dateformatter:
> but the following patterns are not yet supported: A e D F g Y u w W

@HyouSei - could you check with pattern updated to use `yyyy` instead?

**Comment by dlaliberte** [comment]
Thanks @pzygielo .  I was wondering about exactly this scenario, since it has come up before.   So this "year of Week of Year" thing is very surprising.  Not sure if we should remove the (accidental?) support for YYYY, or make it somehow more obvious what is going on.

**Comment by HyouSei** [comment]
@pzygielo Thanks very much!
