### ISSUE TITLE
Google chart api ip list

### ISSUE THREAD

**Issue by ghost** [google/google-visualization-issues#2908]
Hi google support team,

I am using google chart api in an ERP software, our server for security purposes does not resolve any dns so I was wondering if you can give me a complete list or a range of ip addresses to set in our server for resolving char api url.

This is an example of the complete url I am using in my program, it automatically changes in order the clien provide the data.
https://chart.apis.google.com/chart?chs=60x60&cht=qr&chld=|1&chl=7861152809971/chart.png

Greetings.

Hola, equipo de asistencia de Google:

Estoy usando google chart api en un software ERP, nuestro servidor por motivos de seguridad no cuenta con servicio de dns así que no puede resolver ninguna dirección, así que me preguntaba si puede darme una lista completa o un rango de direcciones IP para configurar en nuestro servidor para resolver la url de google chart api: .

Este es un ejemplo de la dirección completa que uso en mi programa, obviamente cambia dinámicamente de acuerdo a los parámetros que envía el usuario.
https://chart.apis.google.com/chart?chs=60x60&cht=qr&chld=|1&chl=7861152809971/chart.png
Saludos.

**Comment by orwant** [comment]
We can't give you a complete list of IP addresses; they change.

**Comment by orwant** [comment]
Also, you're using a deprecated service that can be turned off at any time. You should generate your QR codes some other way.

**Comment by ghost** [comment]
Has google any other api in order to generate qr code? Or is this the only way to do it?

**Comment by orwant** [comment]
Nope. There are other free services available online.
