### ISSUE TITLE
https://developers.google.com/chart failing to load resources and connectivity problems

### ISSUE THREAD

**Issue by EdoWasTaken** [google/google-visualization-issues#2978]
The website is failing to load some resources in the page https://developers.google.com/chart: 

- chart_linea.png:1          Failed to load resource: the server responded with a status of 404 ()
- chart_crostata.png:1          Failed to load resource: the server responded with a status of 404 ()
- chart_colonna.png:1          Failed to load resource: the server responded with a status of 404 ()
- chart_albero.png:1          Failed to load resource: the server responded with a status of 404 ()

When it doesn't fail to load the resource it just show an error related to the request sent to get the images:

- chart_linea.png:1          GET https://developers-dot-devsite-v2-prod.appspot.com/chart/interactive/images/chart_linea.png 404
- chart_colonna.png:1          GET https://developers-dot-devsite-v2-prod.appspot.com/chart/interactive/images/chart_colonna.png 404
- chart_albero.png:1          GET https://developers-dot-devsite-v2-prod.appspot.com/chart/interactive/images/chart_albero.png 404
-chart_crostata.png:1          GET https://developers-dot-devsite-v2-prod.appspot.com/chart/interactive/images/chart_crostata.png 404

Also, when you browse across the site, if the language is different from english, all the example charts and the charts images in general are not being shown. I get this error in the italian version and in all the other languages version (all translated in the one selected): 

>**Cannot find the IP address of the %20l10n-placeholder3%3D server.**

**Comment by dlaliberte** [comment]
Everything seems to be working, so maybe just try again now.  There might have been some changes on the developers.google.com site such that your cached copy of pages no longer work.

**Comment by dlaliberte** [comment]
Ah, now I understand what was happening.  This was yet another manifestation of the translation bug(s), which in this case corrupted chart-related image URLs.  Changing the language to other than English was required.  I failed to read your message carefully.
