### ISSUE TITLE
Problems with Google chart version 52

### ISSUE THREAD

**Issue by moroale93** [google/google-visualization-issues#2986]
[This bundle](https://www.gstatic.com/charts/52/js/jsapi_compiled_default_module.js) (on version 52) instantiates a variable named `google` on the window scope that overrides the one created by the loader.
<img width="239" alt="image" src="https://user-images.githubusercontent.com/9401948/220588606-bb6c7cad-332c-4213-a814-01fd84a3e3c5.png">

Doing so the loader module will not be able to find the `google.charts.load` function because it got overridden. 
This will display the error `No loader available`. Please update the codebase before making it the current version on March 2023.

<img width="141" alt="image" src="https://user-images.githubusercontent.com/9401948/220587990-c439f450-0414-4b41-9f23-55dd3f221e9e.png">

**Comment by darren-doherty** [comment]
➕ 1

**Comment by TaniaPrln** [comment]
➕ 1

**Comment by dlaliberte** [comment]
Thanks for the report.  Yes, I found the same just yesterday, and I am tracking down where it comes from.

**Comment by renanwilliam** [comment]
+1

**Comment by Riesling11** [comment]
Hi, I get this problem with the new release: `Uncaught TypeError: google.charts.setOnLoadCallback is not a function`. I guess it's related to the described problem here then.

**Comment by dlaliberte** [comment]
> Hi, I get this problem with the new release: `Uncaught TypeError: google.charts.setOnLoadCallback is not a function`. I guess it's related to the described problem here then.

Probably not related.  For setOnLoadCallback to not be a function, it would first have to find whatever it is on google.charts, but if google.charts is undefined, it should complain about that.  So you may have a different problem, and I am curious to learn how you got it.  You can add more details here.

**Comment by Riesling11** [comment]
> Probably not related. For setOnLoadCallback to not be a function, it would first have to find whatever it is on google.charts, but if google.charts is undefined, it should complain about that. So you may have a different problem, and I am curious to learn how you got it. You can add more details here.

Thanks, It turned out to be a race condition on my end. I am not sure if the new version maybe takes a bit longer to load, but I guess this bug was there all along in my code – it just didn't come into play so far.

**Comment by dlaliberte** [comment]
The problem with the "var google={}" has been fixed with an update to the 'upcoming' v52 release.
