### ISSUE TITLE
Bug: "Requested map does not exist" for a "world" map - Geochart

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#856]
```
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.
1. when opening a "world" map. Even for the example in your website:
2. Example: http://code.google.com/apis/chart/interactive/docs/gallery/geochart.html#Example


What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)?
Geochart

Are you using the test environment (version 1.1)?
(If you are not sure, answer NO)
NO

What operating system and browser are you using?
2Windows, tested on Chrome and Firefox, with the same results


*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************

```

Original issue reported on code.google.com by `rodrigoacunaagost` on 2012-03-20 10:40:23

<hr>
- _Attachment: [example error.JPG](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-856/comment-0/example error.JPG)_

**Comment by orwant** [comment]
```
In Analytics I've lost the map in the last few days and see this message instead.
```

Original issue reported on code.google.com by `djklint26` on 2012-07-06 21:38:35

**Comment by orwant** [comment]
```
I have the same exact issue.
```

Original issue reported on code.google.com by `sergio.felix` on 2012-11-08 05:54:55

**Comment by orwant** [comment]
```
I can still the same issue (see below url)... Don't we have a solution yet?

https://code.google.com/apis/ajax/playground/?type=visualization#geo_chart


```

Original issue reported on code.google.com by `kesavanv` on 2013-01-07 20:13:25

**Comment by orwant** [comment]
```
Same issue with XHTML 5
```

Original issue reported on code.google.com by `industral` on 2013-03-28 12:54:32

**Comment by orwant** [comment]
```
Hello, the original issue is from a year ago, so I don't think that kesavanv and industral
are having the same issue as the one originally outlined. I wasn't able to replicate
this issue, so if anyone is still experiencing it, please comment with your OS and
browser, as well as a link to a page where the chart doesn't work for you, on this
bug, and I will investigate. Thank you for your patience.
```

Original issue reported on code.google.com by `grabks@google.com` on 2013-03-28 13:40:04

**Comment by orwant** [comment]
```
I experience this issue using the Tor Browser Bundle on Ubuntu 12.10 .  The link given
by kesavanv demonstrates it well.  https://code.google.com/apis/ajax/playground/?type=visualization#geo_chart
```

Original issue reported on code.google.com by `bittlebeetle` on 2013-04-01 21:47:10

**Comment by orwant** [comment]
```
I tested your link in using the Tor Browser Bundle on Ubuntu 12.04, but didn't see any
issues. The maps are stored statically, and it sounds like this issue is cause by it
not being able to load the file. Perhaps the map request is timing out? Can you consistently
reproduce this issue? Does it happen with other browsers? Could you post more detail
from the developer tools (such as the status code of the response)? I'd really like
to help, but I can't seem to reproduce the issue.
```

Original issue reported on code.google.com by `grabks@google.com` on 2013-04-02 14:23:47

**Comment by orwant** [comment]
```
I have not seen the issue in a very long time.  What I remember about it was that I
had been logged into the account for possibly a couple of weeks and after experiencing
the problem it was corrected when I logged out and back in.  Just a guess but maybe
session information was corrupted when I logged into another gmail account in the same
browser?  
```

Original issue reported on code.google.com by `djklint26` on 2013-04-02 14:37:25

**Comment by orwant** [comment]
```
So I was able to replicate this issue with the Tor Browser Bundle exactly once. My current
running theory is that these issues are related to network issues. I suspect that because
Tor slows down your network so much, the maps just time out sometimes. If anyone has
this issue occurring consistently, please ping this thread. If not, I'm inclined to
blame this on connectivity issues and close this bug.
```

Original issue reported on code.google.com by `grabks@google.com` on 2013-04-02 15:12:52

**Comment by orwant** [comment]
```
I had this issue consistently in analytics until today.  My network is indeed flaky,
and I am usually using Tor, although generally google handles it well.

Unfortunately the map started working for me as soon as I started using the network
tab in firebug or developer tools.
```

Original issue reported on code.google.com by `bittlebeetle` on 2013-04-02 16:49:36

**Comment by orwant** [comment]
```
It is happening when some firewall or some network is blocked (e.x sonicwall, antivirus)...


-Sadiq
```

Original issue reported on code.google.com by `sadiq.s@mobinett.com` on 2013-08-16 12:04:05

**Comment by orwant** [comment]
```
Having the exact same issue; have low and erratic network bandwidth and low availability.
I can reproduce the behaviour bittlebe...@gmail.com (http://code.google.com/u/106877764643473796183/)
mentioned in comment #10 (http://code.google.com/p/google-visualization-api-issues/issues/detail?id=856#c10).
For now I am using the activated net tab of firebug as a workaround.
```

Original issue reported on code.google.com by `goetz.freytag` on 2014-02-05 08:56:30

**Comment by orwant** [comment]
```
Yep no map on chrome
```

Original issue reported on code.google.com by `aoleynik@3dfs.com` on 2014-03-12 23:17:03

**Comment by orwant** [comment]
```
I have this issue now on my account.
```

Original issue reported on code.google.com by `kik3rboy` on 2014-05-01 20:53:58

**Comment by orwant** [comment]
```
I have this issue also on Google Analytics - Browser is Google Chrome Version 35.0.1916.114
. In analytics, the error appears in Audience - Geo - Location
```

Original issue reported on code.google.com by `linda@splasch.cx` on 2014-06-09 04:41:02

**Comment by orwant** [comment]
```
I am new to Analytics and this error popped up when I was trying to view Language/Location
https://www.google.com/analytics/web/?hl=en#report/visitors-geo(There was another set
of numbers after this, don't know if it was important/leaking identifying information
but I can add it if requested/necessary).

Linux Mint 16
FireFox 30.0


I refreshed the page and then the map showed up.Just a normal F5, not a force refresh
of all files.
```

Original issue reported on code.google.com by `webmaster@londoncapital.biz` on 2014-06-25 04:51:33

**Comment by orwant** [comment]
```
As mentioned earlier in this bug, this is likely due to a slow internet connection or
a flaky network. It is also possible that the firewall software that you or your company
are using is either making the network slower or blocking certain content. It would
be useful if you could reproduce this with the Network tab open in the Developer Tools
window and let us know if there are any errors or timeouts. A screenshot would be nice
as well.

However, it is highly likely that this issue has more to do with your network than
with anything that we could affect.
```

Original issue reported on code.google.com by `grabks@google.com` on 2014-06-25 14:10:41

**Comment by orwant** [comment]
```
I ran into this also when looking at UA-35972239-1.

1. Was looking at real-time data.  (Not sure if that's a factor.)
2. Went to look at Geo locations.  World map came up fine.
3. Clicked on USA in list and got the little red notification that the map doesn't
exist.
4. Went back and forth a few times and switched timeframe to force a refresh.  Same
result.

That's all I know.
```

Original issue reported on code.google.com by `wsimr.mcc@wsimarketreach.com` on 2014-12-30 16:13:45

**Comment by orwant** [comment]
```
I am getting the same error today, please send tips to fix it, thanks

```

Original issue reported on code.google.com by `mulberrygardenD4` on 2015-01-16 13:06:49

**Comment by orwant** [comment]
```
having the same issue for couple of days. I guess it is something google should fix.
```

Original issue reported on code.google.com by `yalcindaglar` on 2015-01-17 11:02:57

**Comment by orwant** [comment]
```
I have gotten this recently too, cross platform issue. View map by continent still works
but it is fairly useless in comparison to by country.
```

Original issue reported on code.google.com by `berglund.morgan` on 2015-02-27 19:07:41

**Comment by orwant** [comment]
```
I got this issue chrome Version 41.0.2272.101 m on windows 8.1 but I fixed it by turning
off uBlock uBlock v0.9.2.3 ad block extension 
```

Original issue reported on code.google.com by `jasonssiegel` on 2015-03-27 12:58:46

**Comment by orwant** [comment]
```
I've just suddenly started getting the error today
```

Original issue reported on code.google.com by `nicomon` on 2015-04-07 09:21:49

**Comment by orwant** [comment]
```
I've got the issue "(not set)" in the following reporting,
Geo -> Language & Location
Technology -> Network
Mobile -> Devices
```

Original issue reported on code.google.com by `Naveenrajpalanisamy` on 2015-04-10 07:16:53

**Comment by orwant** [comment]
```
Had the same problem. Can we get this fixed? it's one of my biggest missing locations.
```

Original issue reported on code.google.com by `abbie@gallantairconditioning.com` on 2015-04-17 10:10:38

**Comment by orwant** [comment]
```
Hello everyone,

There isn't any way for us to fix this because it's not a problem on our end. We are
unable to reproduce this issue, even with a slow connection. There isn't any way for
us to improve the way we host the data.

If you are seeing this issue, it is probably because some software or hardware that
is preventing you from accessing the map data. Apparently, as posted by a previous
user, certain ad block software may prevent them from being loaded.

If you are consistently seeing this issue, please post a screenshot of the network
tab with the failing request selected. This will at least help us find out what kinds
of failures you're seeing.
```

Original issue reported on code.google.com by `grabks@google.com` on 2015-04-17 14:10:23

**Comment by orwant** [comment]
```
We had this issue in our website. This happened consistently when we display around
> 20 line, pie charts & 1 (or more than 1) geochart (country). This may be related
to loading of geocharts lib simultaneously with other libs (corecharts).
And it is certainly not network issue, since there is no error in Network tab & it
happens consistently in above case. 

Test environment:Google charts library, Chrome 42.0.2311.135 (64-bit) Mac OS X

p.s.: We solved this issue by adding some delay (15 seconds) before drawing geo chart.
So that every other chart else is drawn properly before geo chart. 

```

Original issue reported on code.google.com by `piyuesh` on 2015-05-01 12:04:04

**Comment by bgazzera** [comment]
Hi, was having this issue on Chrome Version 43.0.2357.125 (64-bit) running on Ubuntu.
I configured my AdBlock extension not to run on the page and the error went away.

Hope it helps

**Comment by fmedinamm** [comment]
Maybe it helps, or maybe not, but I started seeing this problem on Ubuntu 15.10, Chrome Version 44.0.2403.155 (64-bit), but we jsut started using Round Robin on firewall, so maybe the map connection goes out on another Internet provider?  Could different IP cause this?

**Comment by shawnkelshaw** [comment]
I fixed this issue by turning off my Kaespersky Chrome extension. Refreshed and the Geo map was visible.

**Comment by nbering** [comment]
Haven't checked, but I seem to recall some complaints about http being used to retrieve some resources when on https sites at the last major feature update. Maybe it would help to know which version your are fetching, @shawnkelshaw.

**Comment by shawnkelshaw** [comment]
Let's see... I may not understand your question clearly. My apologies if I fumble around... yes, I've told Google/Chrome to use Https. when you ask about version, I assume you're asking about Chrome? I'm using Version 47.0.2526.106 m (the latest at the time of this post). Does this help?

**Comment by grabks** [comment]
Hello all,

I am happy to say that we have an update on this issue!

After investigating for a little bit, we found that we had timeouts in place for loading the map data that were far too low for users on slow connections (we had timeouts of 5 seconds). In our upcoming release (version 44), we have raised the timeouts to be 30 seconds, which according to our tests should be enough even for people on slow 2G (250 kb/s).

For those of you, who have experienced this problem, and are itching to get it fixed, you can load version 44 today (!) by explicitly specifying it in your google.charts.load call, like `google.charts.load('44', {packages: ...})`. Keep in mind that this particular snippet will /always/ load version 44, even a year down the line (assuming we don't need to pull it because of security issues at some point), so you would have to update this to load either `'current'` or `'upcoming'` when we promote version 44 (probably in a week or so, assuming everything goes perfectly). If you weren't aware that we have changed our loading method, you may find the documentation [here](https://developers.google.com/chart/interactive/docs/basic_load_libs?hl=en).

It makes sense to me that this issue would be fixed by disabling extensions, since those extensions that intercept network requests will certainly slow down the response time. Hopefully, this will no longer be necessary with version 44.

@nbering I believe the issues are timeouts, not content-policy blocks. If they were the latter, they would have been a lot easier for us to reproduce in the first place.

**Comment by shawnkelshaw** [comment]
Fantastic. Many thanks for the hard work and update!

**Comment by grabks** [comment]
We suspect that this issue has been fixed with our latest update, so closing this bug until someone says otherwise.

**Comment by nothinman** [comment]
@grabks I get that a lot on chromium/raspberry pi 2 in kiosk mode (Chromium 22.0.1229.94 Built on Debian 7.0, running on Debian 7.8). I suspect this is because of the slow CPU (I see 100% core use in `top`). Comments here helped me actually understand what's causing this.
I have added this dirty hack, and it seems to be the doing the trick:

``` javascript
var firstGeoRun = 1;
setInterval(function() { 
  if (firstGeoRun) {
    firstGeoRun = 0;
    google.charts.setOnLoadCallback(drawWorldSales);
  }
}, 30000);
```

however... I'm not a big fan of this - would be much better if there was a better way to solve this.
I get this on desktop occasionaly too :-( (Windows 10, Chrome)

**Comment by grabks** [comment]
@nothinman Are you using the latest version? Are you loading via `google.charts.load` instead of `google.load`? CPU shouldn't have much to do with this, since the issue I was able to reproduce has to do with network load.

**Comment by nothinman** [comment]
@grabks sorry for the late response.
`google.charts.load` is what I'm using.
CPU has a lot to do with it when the system, browser, and javascript eat up all the clock cycles.
I'm not sure how geochart works behind the scenes, but it just simply times out - looks like the browser doesn't execute json in time, or something like that.
When I use 30 second setInterval/setTimeout, it renders the geochart as expected...
