### ISSUE TITLE
Gauge chart value display 

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#858]
```
What would you like to see us add to this API?
Would be good if we can add or allow display of extra label along with the gauge value,
currently I cannot display if the gauge value is %,$ or any other format 

What component is this issue related to (PieChart, LineChart, DataTable,Query, etc)?

GaugeChart


*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************

```

Original issue reported on code.google.com by `attribo.VS` on 2012-03-21 03:02:41

**Comment by orwant** [comment]
```
Why not use NumberFormat? Then you can add whatever suffix, prefix you want. % and $
works fine with me when I do Gauge that way =) Good luck.

        var formatter = new google.visualization.NumberFormat(
                  {prefix: '$', suffix: '%'});
              formatter.format(dataGauge, 1); // Apply formatter to second column 
```

Original issue reported on code.google.com by `bassam.safar` on 2012-04-02 11:39:07

**Comment by orwant** [comment]
```
yes doing the same now, was not aware of the formatter but great help
```

Original issue reported on code.google.com by `attribo.VS` on 2012-04-02 12:26:18

**Comment by orwant** [comment]
```
Glad to hear things are solved.
```

Original issue reported on code.google.com by `jinji.viz` on 2012-04-02 14:17:10

**Comment by sebashb** [comment]
I have came across this, anyone no why using the formatter prevent the gauge from changing the bottom label? My gauge gets data dynamically from a database, but if I set a formatter, old the pointer will move to the new value the bottom label stays the same...

**Comment by nbering** [comment]
@sebasqure Sounds like you're updating the numeric value, but not that string-formatted value. Values are represented with an object that looks like this:

```
{ v: 100, f: "$100" }
```

If you update the value without running the formatter again, or explicitly updating the formatted string you'd get something like this:

```
{ v: 63, f: "$100" }
```

To update the value programatically, you can use `dataTable.setCell`, which also has an argument for the formatted value.

[dataTable.setCell(rowIndex, columnIndex, value, formattedValue, properties)](https://developers.google.com/chart/interactive/docs/reference#DataTable_setCell)

**Comment by sebashb** [comment]
I have manage to put it to work by calling `formatter.format(data, 1);` after using `data.setValue(0, 1, xxxx );`. 

I prefere to use call `formatter.format` after changing the data because your method receives a string in the formattedValue and this one formatter is an object.

Tank you very much!
