### ISSUE TITLE
Bug: Data column(s) for axis #0 cannot be of type string (if all data points are null)

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#866]
```
Please see attached files:

"t1.htm" works fine
"t2.htm" doesn't work -- returns error: "Data column(s) for axis #0 cannot be of type
string"

Difference is that in "t2.htm" all data points are null.  

I would expect "t2.htm" to show an empty chart, instead of returning the error.


```

Original issue reported on code.google.com by `mark.d.cotugno` on 2012-04-04 23:40:58

<hr>
- _Attachment: [t1.htm](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-866/comment-0/t1.htm)_
- _Attachment: [t2.htm](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-866/comment-0/t2.htm)_

**Comment by orwant** [comment]
```
It's because you're using arrayToDataTable, instead of providing the column types explicitly.
arrayToDataTable tries to guess the types from the data, but null gives no type information.
You can use the addColumn/addRow/addRows functions of DataTable, instead of arrayToDataTable.
```

Original issue reported on code.google.com by `jinji.viz` on 2012-04-08 08:48:42

**Comment by orwant** [comment]
```
Thanks for clarification
```

Original issue reported on code.google.com by `mark.d.cotugno` on 2012-04-08 20:52:45

**Comment by eduardodallmann** [comment]
error has not yet been fixed
