### ISSUE TITLE
Bug: Charts are not displayed in IE8 Standards

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#936]
```
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.
1. Open IE9, set Browser Mode: IE8, set Document Mode: IE8 Standards (or open IE8).
2. Navigate to Chart Gallery: https://developers.google.com/chart/interactive/docs/gallery
3. Observe how all non-table charts are not displayed.

The issue, it seems, is related to ALL chart types, and NOT DataTable,
Query, etc.

I am NOT using the test environment (version 1.1).

What operating system and browser are you using?
Windows 7 64 + IE9

Investigation:
The reason, or one of the reasons, that causes the bug is an incorrect schema for the
document using VML: xmlns:v="urn:scheman-microsoft-com:vml" (INCORRECT) instead of
xmlns:v="urn:schemas-microsoft-com:vml" (CORRECT).

*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************
```

Original issue reported on code.google.com by `arevinsky` on 2012-06-26 13:14:36

**Comment by orwant** [comment]
```
Works for me...
```

Original issue reported on code.google.com by `jinji.viz` on 2012-06-26 16:49:57

**Comment by orwant** [comment]
```
Please provide more info. My results are backed up by a QA team that I work with. I
myself checked it on another PC (true-for-my-PC rule is broken here, since there's
more than myself).

So, please recheck or provide more info.

Thanks.
```

Original issue reported on code.google.com by `arevinsky` on 2012-06-26 19:36:18

**Comment by orwant** [comment]
```
I think the "Please provide more info" comment should be applied to you...
This API is widely used around the world, and such a major bug would certainly be noticed
by many. Yet we have no other such reports.

Don't get me wrong, I completely believe you it's not working for you. IE8 has caused
us many problems in the past, such as charts working on 32bit but not on 64bit or vice
versa, not working on a Windows/IE in a specific language, and so on. If we want to
do anything with that bug, we'll need more info (and even then, frankly, most chances
we won't be able to do anything. Damn IE8).

```

Original issue reported on code.google.com by `jinji.viz` on 2012-06-27 10:48:16

**Comment by orwant** [comment]
```
Right, but what about the misspelled namespace for VML? It can be checked
easily: there's this 'scheman' instead of 'schemas' in the 'corechart'
file, there's that namespace in IFRAME (open IE inspector, locate the
<HTML..> copy outerHTML, paste into notepad++). Maybe it is what influences
these tiny slice of cases I fall in?

Thanks.

On Wed, Jun 27, 2012 at 2:48 PM, <
google-visualization-api-issues@googlecode.com> wrote:
```

Original issue reported on code.google.com by `arevinsky` on 2012-06-27 10:54:53

**Comment by orwant** [comment]
```
This is a valid bug, please reopen.
Win7 64bit IE9 in IE8 mode.

```

Original issue reported on code.google.com by `timothypratley` on 2012-09-25 01:09:22

<hr>
- _Attachment: IE8_mode.PNG<br>![IE8_mode.PNG](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-936/comment-5/IE8_mode.PNG)_

**Comment by orwant** [comment]
```
I am facing the same issue in IE8 standards mode only. The charts show up in Quirks
mode, IE7 and IE9 but fail to load on IE8 standards mode without any error or warning.
The security settings in the browser are at the lowest to allow maximum scripts to
be run.

There is usually a blank white space where the chart is supposed to be.

Environment: WIndows 7
```

Original issue reported on code.google.com by `amanjeev` on 2013-01-09 20:41:12

**Comment by orwant** [comment]
```
I am currently facing the same problems. Is there any way to be notified when there
is a fix for this bug?
```

Original issue reported on code.google.com by `Benito.Warez` on 2013-02-20 18:41:37

**Comment by orwant** [comment]
```
@Benito You can star the issue to be notified.
There is a workaround to encourage IE not to use IE8 standards mode:
<html><head><meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">

```

Original issue reported on code.google.com by `timothypratley` on 2013-02-20 18:47:28

**Comment by orwant** [comment]
```
Does this work when the client only has IE8? My company keeps IE version pretty strict
and most of them only have IE8.
```

Original issue reported on code.google.com by `Benito.Warez` on 2013-02-20 18:49:54

**Comment by orwant** [comment]
```
Yes.  I ran into the issue because when you access an intranet site using IE8 it defaults
to standards mode.  However including that line above encourages the browser to use
compatibility mode which renders Google charts well.
```

Original issue reported on code.google.com by `timothypratley` on 2013-02-20 18:56:21

**Comment by orwant** [comment]
```
I appreciate the workaround but adding "<meta content="IE=edge,chrome=1"
http-equiv="X-UA-Compatible">" is not acceptable. I personally have
requirements to run IE in standards mode rather.
```

Original issue reported on code.google.com by `amanjeev` on 2013-02-20 20:40:45

**Comment by orwant** [comment]
```
I'm having the same issue with ie9 and ie10 both in document mode ie8.

I'm using windows 7 professional 64 bit
```

Original issue reported on code.google.com by `Zoppi.Nicola` on 2014-03-05 09:38:05

**Comment by orwant** [comment]
```
I am facing the same problem , can google engineers tell me its solution ?
```

Original issue reported on code.google.com by `ishanarorase` on 2014-06-17 06:19:48

**Comment by orwant** [comment]
```
Not sure but it seems to be a IE document mode problem. When I used another tool like
IE Tester, it works fine. Somebody try it on a VM with native IE8 ?
```

Original issue reported on code.google.com by `pierre.mihawk` on 2014-06-17 08:14:14

**Comment by orwant** [comment]
```
For what it's worth, I can verify that the chart gallery doesn't work at all in a VirtualBox
VM running IE8 on Windows XP, Service Pack 3. We're investigating whether to use this
library, and now we have to try to figure out if it's just not working because of a
bug on the website, or if the library itself is no longer compatible with IE8. 
```

Original issue reported on code.google.com by `StriplingWarrior` on 2014-07-22 23:10:36

<hr>
- _Attachment: Capture.PNG<br>![Capture.PNG](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-936/comment-16/Capture.PNG)_

**Comment by orwant** [comment]
```
What is the solution for this?
```

Original issue reported on code.google.com by `devikumardonthamsetti` on 2014-08-07 13:14:16

**Comment by unosadmin** [comment]
I have the same issue. The Google Charts don't work in IE8 on Windows 7 64-bit.
Javascript error received:

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E)
Timestamp: Tue, 19 May 2015 11:57:07 UTC

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://www.google.com/uds/api/visualization/1.0/abbdd6ab2d343a51d49841bf93d022fb/format+en,default+en,ui+en,corechart+en.I.js

**Comment by dlaliberte** [comment]
unosadmin, can you give us an actual script (or better, a link to a page) that shows the problem you are seeing.  Your error message and URI only shows us you got some error, but no clue about how.

**Comment by membersound** [comment]
Is there any solution on this? I'm facing the same problem that IE8 is not working with google charts.

**Comment by dlaliberte** [comment]
IE8 will soon be dead even to Microsoft, but there are some fixes to support IE8 that might help in version 43, especially if you use the frozen version loader.  See documentation on how to set that up at https://google-developers.appspot.com/chart/interactive/docs/library_loading_enhancements#frozen-versions

**Comment by membersound** [comment]
@dlaliberte thanks I tried it, but unfortunately this does not fix the issue, and the chart is not showing up at all (it is in newer browsers).

So probably there is no solution for IE8?

**Comment by grabks** [comment]
@sddakoty Could you link to a jsfiddle that reproduces the issue? Or attach an HTML page that reproduces the issue? While we won't work extra hard to support IE8 (as @dlaliberte implied), we do expect CoreCharts to work on it. However, we can't investigate the issue unless we can reproduce the issue.

**Comment by membersound** [comment]
![linechart html](https://cloud.githubusercontent.com/assets/5269630/10686344/722ef276-7963-11e5-9fcc-edb461b68525.png)
![linechart_frozen html](https://cloud.githubusercontent.com/assets/5269630/10686348/7a109bf2-7963-11e5-93e3-711e8bcb2c7f.png)

Please find attached both a normal and a frozen example. Important: download and rename them to *.html, as I do not have writepermissions to this repository and thus cannot upload html or txt files.

I cannot upload it to plunkr or jsfiddle, as these tools themselves have problems in IE8 mode, and thus cannot be cleanly inspected.

To emulate a real IE8, I'm using Safari (Developer > User Agent > IE8). But also tested it in IE8 itself and can confirm the same behaviour:

Both the normal and frozen version work in normal modern browsers. But in IE8, the frozen version just shows an empty div tag, and the normal version shows the following error message:
`Result of expression 'a.runtimeStyle' [undefined] is not an object.`

With html generated:
`<div id="google-visualization-errors-all-1" style="padding-top: 2px; display: block; "><div id="google-visualization-errors-0" style="font: normal normal normal 0.8em/normal arial, sans-serif; margin-bottom: 5px; "><span style="background-color: rgb(192, 0, 0); color: white; padding-top: 2px; padding-right: 2px; padding-bottom: 2px; padding-left: 2px; ">Result of expression 'a.runtimeStyle' [undefined] is not an object.<span style="font-size: 1.1em; font-weight: bold; cursor: pointer; padding-left: 10px; color: black; text-align: right; vertical-align: top; ">×</span></span></div></div>`

**Comment by grabks** [comment]
I imagine that setting the user agent to IE8 in Safari isn't the best method of testing this. IE8 doesn't support SVG, so when we detect IE8, we switch to rendering via VML, which is Microsoft's own way of rendering vector graphics. I'm willing to bet that Safari doesn't support VML, and that would be why it fails to render there.

That said, I downloaded both your files, copied them character for character and executed them inside of a virtual machine with IE8 on it. As you can see from my screenshot, both pages work perfectly in IE8.
![screen shot 2015-10-23 at 9 48 47 am](https://cloud.githubusercontent.com/assets/11892394/10694308/66f51f36-796b-11e5-8e8d-07d6bda38024.png)

**Comment by membersound** [comment]
Thanks for your investigation. I must have made a mistake in testing a real IE8, great that it works.

Anyways I should probably go a bit more into detail:
We're having an application written in Adobe Actionscript `Flex`, and want to embed the html page. Flex therefore has a component that internally uses a browser engine that is very similar to a Safari in IE8 Agent Mode. At least the webpages look the same.

The Agent of this internal browser is:
WebKit version: 533.19.4
Browser name: Adobe Air 13.0
User Agent: Mozilla/5.0 (Windows; U; de-DE) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/13.0

It's not IE8, but behaves like a Safari in IE8 mode.

As flex development is not continued by adobe, this internal browser will never get updates in the future. For backwards compatibility we have to support this mode still for quite some time, while the to be embeded webpages will continue to evolve, eg with google-charts.

And with this WebKit version we're experiencing the problems written above.

**Comment by grabks** [comment]
I have never even heard of Adobe Air. After trying to install it, I don't see any browser-like thing that I can run. It appears to be an application runtime. Given that I have never made an Air application, I don't intend to start now. If you'd like to provide some source for an Adobe Air application that renders that chart, with instructions for how to debug the executing JavaScript, I can take a look at what's going on.

From the user agent, it looks like it's more similar to early Firefox than to IE8. Looking online, it doesn't appear like Air supports SVG. However, it also doesn't support VML (which is what we use to render in IE8). This also means that we don't support their rendering method (presumably SWF).

According to [this StackOverflow post](http://stackoverflow.com/questions/88481/can-adobe-air-display-svg), there are tools that will translate SVG into SWF. This is one possible solution to your problem. However, this solution assumes that the SVG elements are properly generated and that you can read the generated DOM and load it into these tools. I don't see why not, but I also don't have any experience with Air.

An alternate solution might be to use getImageURI(), which renders the chart via the HTML5 Canvas, and returns a data URL that encodes an image. This solution assumes that Air supports the HTML5 Canvas API, and data URLs for displaying images. Using this solution also means that you will lose interactivity for the charts (assuming you ever had it).

And of course, all of the above assumes that JavaScript executes in a predictable manner and that Air can properly manipulate its DOM (and that there aren't any other issues, like unsupported or missing methods, or not fully supported APIs).

**Comment by membersound** [comment]
Actually there wouldn't be any benefit of providing an AIR application with embedded html page, because you cannot debug the javascript/html inside!

But we use the `Safari 5.0.3` in IE8 Agent Mode to debug the pages, as the behaviour is exactly the same (most important also the google charts error message). You might get it from here: http://filehippo.com/de/download_safari/8757/

Maybe you could have a look into this?

**Comment by grabks** [comment]
The behavior cannot be the same. The browsers are fundamentally different and have fundamentally different capabilities. And in fact, both of those browsers have fundamentally different capabilities from what Adobe AIR provides (judging by what I was reading).

Here's the issue at its most basic: we use user agent sniffing to determine rendering capabilities. This means that when Safari tells us it's IE8, we will use whatever code paths we'd use for IE8. One of the things we do differently is use VML instead of SVG. **Safari does not support and has never supported VML**. For this reason, and this reason alone, you cannot test our charts in IE8 mode in Safari. It simply cannot be done because it won't work.

Part of why it won't work is because perhaps we should be using feature detection, instead of user agent sniffing, to detect the browser's capabilities; but this doesn't really matter for your case, since all that would do is cause us to use SVG, which is not supported by Adobe AIR.

Let me reiterate: **Adobe AIR does not support either SVG or VML. Therefore, neither of the primary ways in which we render our charts will work on it.**

Your testing/debugging method is inherently flawed, because even though the error might look the same, that doesn't mean that the capabilities and other behaviors in the browser will be also be the same.
